/**
 * Read-only access to a patient's rendered "working" view images.
 *
 * The `working/` directory (`clinic1/working/`, beside the per-patient timepoint
 * folders) is a FLAT folder shared by every patient (Dolphin's convention): each
 * rendered view is `{personId}0{tpCode}.{view}`, e.g. `688201.i12`. This module
 * lists/serves ONLY the exact filenames this patient's own timepoints can
 * produce — it never enumerates the directory to the caller and never accepts a
 * path separator, so it cannot traverse out of `working/` or leak another
 * patient's files.
 *
 * EXACT names, never a `{personId}0…` prefix match. Decimal ids prefix each
 * other, so a prefix pattern is ambiguous ACROSS PATIENTS: patient 5's `^50\d+`
 * also matches patient 50's `5001.i12` and patient 5012's `501201.i12`. Nothing in the
 * filename resolves that ambiguity — only the patient's real set of
 * `time_points.tp_code` values does, so callers pass their tpCodes in and we
 * enumerate the (tpCode × view) names those can generate. The delete path
 * (photo-cleanup.service.ts#deleteWorkingFilesForPatient) is built the same way.
 *
 * Deliberately read-only: working images are (re)generated by the photo editor
 * and removed via the time-point "delete cropped" action — they are not managed
 * as free-form files here.
 */
import path from 'path';
import fs from 'fs/promises';
import { FileExplorerError, type FileEntry } from './file-explorer.service.js';
import { workingDir, workingFileName, workingFilePath } from './clinic-paths.js';
import { VIEW_CODES } from '../../shared/photo-views.js';

/**
 * Every filename this patient's timepoints can legitimately produce, lowercased
 * for case-insensitive lookup (the renderer writes lowercase `.iNN`, but the
 * share is NTFS and older files may carry `.INN`). Membership in this set is the
 * whole authorization check: the names are SERVER-BUILT from validated digits, so
 * a match also guarantees no separator and no traversal.
 */
function expectedWorkingNames(
  personId: string | number,
  tpCodes: readonly (string | number)[]
): Set<string> {
  const names = new Set<string>();
  for (const tpCode of tpCodes) {
    if (!/^\d+$/.test(String(tpCode))) continue; // ignore junk rather than fail the listing
    for (const view of VIEW_CODES) {
      names.add(workingFileName(personId, tpCode, view).toLowerCase());
    }
  }
  return names;
}

/**
 * List the patient's rendered working images out of the shared dir.
 * `tpCodes` is the patient's own `time_points.tp_code` set — see the module note
 * on why a prefix match would cross patients.
 */
export async function listPatientWorkingFiles(
  personId: string | number,
  tpCodes: readonly (string | number)[]
): Promise<FileEntry[]> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);

  const expected = expectedWorkingNames(personId, tpCodes);
  if (expected.size === 0) return []; // no timepoints ⇒ no rendered views

  const dir = workingDir();
  let names: string[];
  try {
    names = await fs.readdir(dir);
  } catch {
    return []; // working/ may not exist yet on a fresh share
  }

  const entries = await Promise.all(
    names
      .filter((n) => expected.has(n.toLowerCase()))
      .map(async (name): Promise<FileEntry | null> => {
        try {
          const st = await fs.stat(workingFilePath(name));
          if (!st.isFile()) return null;
          return {
            name,
            relPath: name, // bare filename — addressed by `name`, never a path
            type: 'file',
            size: st.size,
            modified: st.mtime.toISOString(),
            ext: path.extname(name).toLowerCase(),
            category: 'image', // .iNN are JPEG bytes (sharp-rendered)
          };
        } catch {
          return null;
        }
      })
  );
  return entries.filter((e): e is FileEntry => e !== null);
}

/** Resolve + stat a single working file, strictly validated to this patient. */
export async function resolveWorkingFile(
  personId: string | number,
  name: string,
  tpCodes: readonly (string | number)[]
): Promise<{ abs: string; mtimeMs: number; size: number }> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);
  if (!expectedWorkingNames(personId, tpCodes).has(name.toLowerCase())) {
    // The name must be one this patient's own timepoints can generate ⇒ no
    // separators, no traversal, and no other patient's files.
    throw new FileExplorerError('Invalid working file', 400);
  }

  const abs = workingFilePath(name);
  try {
    const st = await fs.stat(abs);
    if (!st.isFile()) throw new FileExplorerError('Working file not found', 404);
    return { abs, mtimeMs: st.mtimeMs, size: st.size };
  } catch (err) {
    if (err instanceof FileExplorerError) throw err;
    throw new FileExplorerError('Working file not found', 404);
  }
}
