/**
 * Read-only access to a patient's rendered "working" view images.
 *
 * The `working/` directory (`clinic1/working/`, beside the per-patient timepoint
 * folders) is a FLAT folder shared by every patient (Dolphin's convention): each
 * rendered view is `{personId}0{tpCode}.{view}`,
 * e.g. `688201.i12`. This module lists/serves ONLY the files whose name matches
 * the requesting patient's prefix — it never enumerates the directory to the
 * caller and never accepts a path separator, so it cannot traverse out of
 * `working/` or leak another patient's files.
 *
 * Deliberately read-only: working images are (re)generated by the photo editor
 * and removed via the time-point "delete cropped" action — they are not managed
 * as free-form files here.
 */
import path from 'path';
import fs from 'fs/promises';
import { FileExplorerError, type FileEntry } from './file-explorer.service.js';
import { workingDir, workingFilePath } from './clinic-paths.js';

/**
 * Working-file name for one patient: `{personId}0{tpCode}.{view}` where view is
 * `iNN` (i10..i24). Anchored + digit/letter-only ⇒ no separators, no traversal.
 */
function patientWorkingNameRe(personId: string | number): RegExp {
  return new RegExp(`^${personId}0\\d+\\.[iI]\\d{2}$`);
}

/** List the patient's rendered working images (filtered out of the shared dir). */
export async function listPatientWorkingFiles(personId: string | number): Promise<FileEntry[]> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);

  const dir = workingDir();
  let names: string[];
  try {
    names = await fs.readdir(dir);
  } catch {
    return []; // working/ may not exist yet on a fresh share
  }

  const re = patientWorkingNameRe(personId);
  const entries = await Promise.all(
    names
      .filter((n) => re.test(n))
      .map(async (name): Promise<FileEntry | null> => {
        try {
          const st = await fs.stat(workingFilePath(name));
          if (!st.isFile()) return null;
          return {
            name,
            relPath: name, // bare filename — addressed by `name`, never a path
            type: 'file',
            size: st.size,
            modified: st.mtime.toISOString(),
            ext: path.extname(name).toLowerCase(),
            category: 'image', // .iNN are JPEG bytes (sharp-rendered)
          };
        } catch {
          return null;
        }
      })
  );
  return entries.filter((e): e is FileEntry => e !== null);
}

/** Resolve + stat a single working file, strictly validated to this patient. */
export async function resolveWorkingFile(
  personId: string | number,
  name: string
): Promise<{ abs: string; mtimeMs: number; size: number }> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);
  if (!patientWorkingNameRe(personId).test(name)) {
    // Strict pattern ⇒ no separators, no traversal, only this patient's files.
    throw new FileExplorerError('Invalid working file', 400);
  }

  const abs = workingFilePath(name);
  try {
    const st = await fs.stat(abs);
    if (!st.isFile()) throw new FileExplorerError('Working file not found', 404);
    return { abs, mtimeMs: st.mtimeMs, size: st.size };
  } catch (err) {
    if (err instanceof FileExplorerError) throw err;
    throw new FileExplorerError('Working file not found', 404);
  }
}
