/**
 * Access to a patient's images in Dolphin's "working" gallery.
 *
 * The `working/` directory (`clinic1/working/`, beside the per-patient timepoint
 * folders) is a FLAT folder shared by every patient (Dolphin's convention): each
 * image is `{personId}{tpCode:02}.{slot}`, e.g. `688201.i12`. The slot is one of the
 * 8 photo views the grid shows or any other Dolphin slot of the session (OPG `i51`,
 * ceph `i50`, … — see shared/photo-views.ts). This module lists/serves ONLY names
 * whose stem is one of this patient's own sessions — it never enumerates the
 * directory to the caller and never accepts a path separator, so it cannot traverse
 * out of `working/` or leak another patient's files.
 *
 * A slot Dolphin filled has TWO files: the image (`.iNN`, cropped/rotated, what every
 * screen shows) and Dolphin's untouched original of it (`.vNN`: the full camera frame
 * or X-ray, before any edit; JPEG, sometimes TIFF/BMP/PNG). The photo editor writes
 * only the image. The two are a pair: whatever deletes one deletes the other, so a
 * `.vNN` is never left without its image (an orphan nothing shows or cleans up). Every
 * delete here moves the files to the patient's trash, never removes them.
 *
 * EXACT stems, never a `{personId}…` prefix match. Decimal ids prefix each
 * other, so a prefix pattern is ambiguous ACROSS PATIENTS: patient 5's `^50\d+`
 * also matches patient 50's `5001.i12` and patient 5012's `501201.i12`. Nothing in the
 * filename resolves that ambiguity — only the patient's real set of
 * `time_points.tp_code` values does, so callers pass their tpCodes in and a name
 * belongs to the patient only when everything before its dot is one of the stems
 * those codes build. The delete paths (photo-cleanup.service.ts) are built the same way.
 *
 * Not a free-form folder: working images are (re)generated by the photo editor (or
 * were put there by Dolphin), so nothing here renames or uploads. The writes are the
 * deletes — the Working files page's, the photo editor's Remove and a session's — and
 * each moves a whole slot (both files) to the patient's trash.
 */
import path from 'path';
import fs from 'fs/promises';
import { log } from '../../utils/logger.js';
import { FileExplorerError, type FileEntry } from './file-explorer.service.js';
import { newTrashDir, workingDir, workingFileName, workingFileStem, workingFilePath } from './clinic-paths.js';

/** A working image, with the session and Dolphin slot its name encodes. */
export type WorkingFileEntry = FileEntry & {
  tpCode: number;
  /** Dolphin slot code, lower-case, the same for both files of a slot: `i12` (a grid view), `i51` (an OPG), … */
  view: string;
  /** Dolphin's untouched original of the slot (`.vNN`), not the image itself (`.iNN`). */
  original: boolean;
};

/**
 * A Dolphin slot file: a digit stem, a dot, `i` (the image) or `v` (Dolphin's original
 * of it), and a two-digit slot, in either case.
 */
const SLOT_FILE_NAME_RE = /^(\d+)\.([iv])(\d{2})$/i;

/** A slot file's stem, slot (as its `iNN` code, for either file) and which file it is. */
function parseSlotFileName(name: string): { stem: string; view: string; original: boolean } | null {
  const m = SLOT_FILE_NAME_RE.exec(name);
  return m ? { stem: m[1], view: `i${m[3]}`, original: m[2].toLowerCase() === 'v' } : null;
}

/**
 * This patient's session stems (`{personId}{tpCode:02}`) → tp code. Membership is the
 * whole authorization check: the stems are SERVER-BUILT from validated digits and the
 * name regex admits nothing but digits, one dot and `iNN`/`vNN`, so a match also
 * guarantees no separator and no traversal. Distinct tp codes give distinct stems (the
 * padding is to two digits, never more), so a name maps to exactly one session.
 */
function sessionStems(
  personId: string | number,
  tpCodes: readonly (string | number)[]
): Map<string, number> {
  const stems = new Map<string, number>();
  for (const tpCode of tpCodes) {
    if (!/^\d+$/.test(String(tpCode))) continue; // ignore junk rather than fail the listing
    stems.set(workingFileStem(personId, tpCode), Number(tpCode));
  }
  return stems;
}

/** The session + slot a working-dir name belongs to, or null when it isn't this patient's. */
function matchWorkingName(
  name: string,
  stems: ReadonlyMap<string, number>
): { tpCode: number; view: string; original: boolean } | null {
  const parsed = parseSlotFileName(name);
  if (!parsed) return null;
  const tpCode = stems.get(parsed.stem);
  return tpCode === undefined ? null : { tpCode, view: parsed.view, original: parsed.original };
}

/** The working dir's names; empty when it doesn't exist yet (a fresh share). */
async function readWorkingDir(): Promise<string[]> {
  try {
    return await fs.readdir(workingDir());
  } catch {
    return [];
  }
}

/**
 * The first session's Smile (`{id}00.i13`) for each patient, by its REAL on-disk name
 * — one directory read for the whole list, no per-file stat. Editor renders are
 * lower-case `.i13` and Dolphin's upper-case `.I13`; on a case-sensitive volume the
 * guessed lower-case name 404s for the latter (25 of 79 aligner patients), and a
 * patient with no such file cost a failed request and a console error per card
 * (FE-F18-8). A patient without one maps to null.
 */
export async function findFirstSmiles(personIds: readonly number[]): Promise<Map<number, string>> {
  const found = new Map<number, string>();
  if (personIds.length === 0) return found;
  const names = await readWorkingDir();
  const wanted = new Map<string, number>();
  for (const id of personIds) wanted.set(workingFileName(id, 0, 'i13').toLowerCase(), id);
  for (const name of names) {
    const id = wanted.get(name.toLowerCase());
    // Canonical lower-case first, if both spellings exist.
    if (id !== undefined && (!found.has(id) || name === workingFileName(id, 0, 'i13'))) found.set(id, name);
  }
  return found;
}

/**
 * List the patient's images out of the shared dir: every Dolphin slot of every
 * session, the 8 grid views and the rest (OPG, ceph, …), each slot's image and
 * Dolphin's original of it. `tpCodes` is the patient's own `time_points.tp_code` set
 * — see the module note on why a prefix match would cross patients.
 */
export async function listPatientWorkingFiles(
  personId: string | number,
  tpCodes: readonly (string | number)[]
): Promise<WorkingFileEntry[]> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);

  const stems = sessionStems(personId, tpCodes);
  if (stems.size === 0) return []; // no timepoints ⇒ no images

  const names = await readWorkingDir();
  const entries = await Promise.all(
    names.map(async (name): Promise<WorkingFileEntry | null> => {
      const match = matchWorkingName(name, stems);
      if (!match) return null;
      try {
        const st = await fs.stat(workingFilePath(name));
        if (!st.isFile()) return null;
        return {
          name,
          relPath: name, // bare filename — addressed by `name`, never a path
          type: 'file',
          size: st.size,
          modified: st.mtime.toISOString(),
          ext: path.extname(name).toLowerCase(),
          // Every slot file is an image; its bytes, not the extension, say which kind
          // (the content route sniffs them).
          category: 'image',
          tpCode: match.tpCode,
          view: match.view,
          original: match.original,
        };
      } catch {
        return null;
      }
    })
  );
  return entries.filter((e): e is WorkingFileEntry => e !== null);
}

/** Resolve + stat a single working file (an image or an original), strictly validated to this patient. */
export async function resolveWorkingFile(
  personId: string | number,
  name: string,
  tpCodes: readonly (string | number)[]
): Promise<{ abs: string; mtimeMs: number; size: number }> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);
  if (!matchWorkingName(name, sessionStems(personId, tpCodes))) {
    // The name must be a Dolphin slot file of one of this patient's own sessions ⇒ no
    // separators, no traversal, and no other patient's files.
    throw new FileExplorerError('Invalid working file', 400);
  }

  const abs = workingFilePath(name);
  try {
    const st = await fs.stat(abs);
    if (!st.isFile()) throw new FileExplorerError('Working file not found', 404);
    return { abs, mtimeMs: st.mtimeMs, size: st.size };
  } catch (err) {
    if (err instanceof FileExplorerError) throw err;
    throw new FileExplorerError('Working file not found', 404);
  }
}

/**
 * Every file of the given sessions' slots, by its REAL on-disk name: each slot's image
 * and Dolphin's original of it, in any spelling, from one directory read. `views`
 * limits it to those slots (`iNN` codes); without it, every slot of the session.
 */
export async function listSlotFiles(
  personId: string | number,
  tpCodes: readonly (string | number)[],
  views?: readonly string[]
): Promise<string[]> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);
  const stems = sessionStems(personId, tpCodes);
  if (stems.size === 0) return [];
  const wanted = views ? new Set(views.map((v) => v.toLowerCase())) : null;
  return (await readWorkingDir()).filter((name) => {
    const match = matchWorkingName(name, stems);
    return !!match && (!wanted || wanted.has(match.view));
  });
}

/** A file another program holds open: Windows refuses to move it. */
function isLockedFileError(err: unknown): boolean {
  const code = (err as NodeJS.ErrnoException).code;
  return code === 'EBUSY' || code === 'EPERM' || code === 'EACCES';
}

/**
 * Move working files (real names, already checked to be the patient's) into ONE fresh
 * trash folder of the patient, `clinic1/.trash/{personId}/{stamp}/working/`, where they
 * can be restored from. Same volume as `working/`, so each move is a rename.
 *
 * `allOrNothing`: a file that won't move (Dolphin holding it open) puts back the ones
 * already moved and fails, so a slot is never left with one file of its pair. Without
 * it, each failure is logged and the rest still move (a session's delete, which must
 * not fail on one file). A name that is already gone is skipped either way. Returns
 * the names moved.
 */
export async function moveWorkingFilesToTrash(
  personId: string | number,
  names: readonly string[],
  { allOrNothing }: { allOrNothing: boolean }
): Promise<string[]> {
  const dest = path.join(newTrashDir(personId), 'working');
  const moved: string[] = [];
  for (const name of names) {
    const abs = workingFilePath(name);
    const st = await fs.stat(abs).catch(() => null);
    if (!st?.isFile()) continue; // already gone
    try {
      if (moved.length === 0) await fs.mkdir(dest, { recursive: true });
      await fs.rename(abs, path.join(dest, name));
      moved.push(name);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') continue; // gone since the stat
      if (!allOrNothing) {
        log.warn('[Files] working file not moved to trash', { personId, name, error: (err as Error).message });
        continue;
      }
      for (const back of [...moved].reverse()) {
        await fs.rename(path.join(dest, back), workingFilePath(back)).catch((undoErr: Error) => {
          log.error('[Files] could not put a working file back from the trash', {
            personId,
            name: back,
            trash: dest,
            error: undoErr.message,
          });
        });
      }
      if (isLockedFileError(err)) {
        throw new FileExplorerError(`${name} is open in another program (Dolphin?). Close it and try again.`, 409);
      }
      throw err;
    }
  }
  return moved;
}

/**
 * Move one slot's files — the image AND Dolphin's original of it — to the patient's
 * trash: the photo editor's Remove. Both or neither (see moveWorkingFilesToTrash).
 * Idempotent: a slot with no files moves nothing. Returns the names moved.
 */
export async function trashWorkingSlot(personId: number, tpCode: number, view: string): Promise<string[]> {
  const names = await listSlotFiles(personId, [tpCode], [view]);
  return moveWorkingFilesToTrash(personId, names, { allOrNothing: true });
}

/**
 * The Working files page's Delete, for either file of a slot: the image and Dolphin's
 * original of it go to the patient's trash together (both or neither). The name is
 * checked exactly as `resolveWorkingFile` checks it.
 *
 * Returns the session and slot the name encodes, for the caller's record delete, and
 * the names moved.
 */
export async function trashWorkingFile(
  personId: string | number,
  name: string,
  tpCodes: readonly (string | number)[]
): Promise<{ tpCode: number; view: string; removed: string[] }> {
  if (!/^\d+$/.test(String(personId))) throw new FileExplorerError('Invalid patient id', 400);
  const match = matchWorkingName(name, sessionStems(personId, tpCodes));
  if (!match) throw new FileExplorerError('Invalid working file', 400);

  // The requested file first, so it is the one a failure names.
  const pair = await listSlotFiles(personId, [match.tpCode], [match.view]);
  const names = [...pair.filter((n) => n === name), ...pair.filter((n) => n !== name)];
  const removed = await moveWorkingFilesToTrash(personId, names, { allOrNothing: true });
  if (removed.length === 0) throw new FileExplorerError('Working file not found', 404);
  return { tpCode: match.tpCode, view: match.view, removed };
}
