/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlignerDoctors {
  DoctorEmail: string | null;
  DoctorName: string;
  DrID: Generated<number>;
  LogoPath: string | null;
}

export interface DocumentTemplates {
  background_color: Generated<string | null>;
  created_by: string | null;
  created_date: Generated<Timestamp | null>;
  description: string | null;
  document_type_id: number;
  grid_size: Generated<number | null>;
  is_active: Generated<boolean | null>;
  is_default: Generated<boolean | null>;
  is_system: Generated<boolean | null>;
  last_used_date: Timestamp | null;
  modified_by: string | null;
  modified_date: Timestamp | null;
  paper_height: number;
  paper_margin_bottom: Generated<number | null>;
  paper_margin_left: Generated<number | null>;
  paper_margin_right: Generated<number | null>;
  paper_margin_top: Generated<number | null>;
  paper_orientation: Generated<string | null>;
  paper_width: number;
  parent_template_id: number | null;
  show_grid: Generated<boolean | null>;
  template_file_path: string | null;
  template_id: Generated<number>;
  template_name: string;
  template_version: Generated<number | null>;
}

export interface DocumentTypes {
  default_orientation: Generated<string | null>;
  default_paper_height: Generated<number | null>;
  default_paper_width: Generated<number | null>;
  description: string | null;
  icon: string | null;
  is_active: Generated<boolean | null>;
  sort_order: Generated<number | null>;
  type_code: string;
  type_id: Generated<number>;
  type_name: string;
}

export interface Patients {
  patBirthdate: Timestamp | null;
  patFirstName: string | null;
  patGender: string | null;
  patID: string;
  patLastName: string | null;
  patName: string | null;
  patOtherID: string | null;
  patPhone1: string | null;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface SyncQueue {
  Attempts: Generated<number | null>;
  CreatedAt: Generated<Timestamp | null>;
  JsonData: string | null;
  LastAttempt: Timestamp | null;
  LastError: string | null;
  Operation: string;
  QueueID: Generated<number>;
  RecordID: number;
  Status: Generated<string | null>;
  TableName: string;
}

export interface TbCities {
  City: string | null;
  ID: Generated<number>;
}

export interface TblAddress {
  CityID: number | null;
  ID: Generated<number>;
  Zone: string | null;
}

export interface TblAlerts {
  AlertDetails: string | null;
  AlertID: Generated<number>;
  AlertSeverity: number;
  AlertTypeID: number;
  CreationDate: Generated<Timestamp>;
  IsActive: Generated<boolean>;
  PersonID: number;
}

export interface TblAlertTypes {
  AlertTypeID: Generated<number>;
  TypeName: string;
}

export interface TblAlignerActivityFlags {
  ActivityDescription: string;
  ActivityID: Generated<number>;
  ActivityType: string;
  AlignerSetID: number;
  CreatedAt: Generated<Timestamp | null>;
  IsRead: Generated<boolean | null>;
  ReadAt: Timestamp | null;
  RelatedRecordID: number | null;
}

export interface TblAlignerBatches {
  AlignerBatchID: Generated<number>;
  AlignerSetID: number;
  BatchExpiryDate: Generated<Timestamp | null>;
  BatchSequence: number;
  CreationDate: Generated<Timestamp>;
  Days: number | null;
  DeliveredToPatientDate: Timestamp | null;
  HasLowerTemplate: Generated<boolean>;
  HasUpperTemplate: Generated<boolean>;
  IsActive: Generated<boolean | null>;
  IsLast: Generated<boolean>;
  LowerAlignerCount: number;
  LowerAlignerEndSequence: Generated<number | null>;
  LowerAlignerStartSequence: number | null;
  ManufactureDate: Timestamp | null;
  Notes: string | null;
  UpperAlignerCount: number;
  UpperAlignerEndSequence: Generated<number | null>;
  UpperAlignerStartSequence: number | null;
  ValidityPeriod: Generated<number | null>;
}

export interface TblAlignerNotes {
  AlignerSetID: number;
  CreatedAt: Generated<Timestamp | null>;
  EditedAt: Timestamp | null;
  IsEdited: Generated<boolean | null>;
  IsRead: Generated<boolean>;
  NoteID: Generated<number>;
  NoteText: string;
  NoteType: string;
}

export interface TblAlignerSets {
  AlignerDrID: number;
  AlignerSetID: Generated<number>;
  ArchformID: number | null;
  CreationDate: Timestamp | null;
  Currency: Generated<string | null>;
  Days: number | null;
  DriveFileId: string | null;
  FolderPath: string | null;
  IsActive: Generated<boolean | null>;
  LowerAlignersCount: number | null;
  Notes: string | null;
  PdfUploadedAt: Timestamp | null;
  PdfUploadedBy: string | null;
  RemainingLowerAligners: number | null;
  RemainingUpperAligners: number | null;
  SetCost: Numeric | null;
  SetPdfUrl: string | null;
  SetSequence: number | null;
  SetUrl: string | null;
  SetVideo: string | null;
  Type: string | null;
  UpperAlignersCount: number | null;
  WorkID: number;
}

export interface Tblappointments {
  AppCost: string | null;
  AppDate: Timestamp;
  AppDay: Generated<Timestamp | null>;
  AppDetail: string | null;
  appointmentID: Generated<number>;
  AppTime: Generated<string | null>;
  DeliveredTimestamp: Timestamp | null;
  DeliveredWa: string | null;
  Dismissed: string | null;
  DrID: number | null;
  LastUpdated: Timestamp | null;
  Notified: Generated<boolean | null>;
  PersonID: number;
  Present: string | null;
  ReadTimestamp: Timestamp | null;
  Seated: string | null;
  SentTimestamp: Timestamp | null;
  SentWa: boolean | null;
  sms_sid: string | null;
  SMSStatus: string | null;
  WaMessageID: string | null;
  WantNotify: Generated<boolean | null>;
  WantWa: Generated<boolean | null>;
}

export interface Tblbends {
  Bend: string;
  Bend_ID: Generated<number>;
}

export interface TblCalender {
  AppDate: Timestamp;
}

export interface TblCarriedWires {
  AdditionDate: Timestamp;
  Id: Generated<number>;
  PersonID: number;
  UpperLower: string;
  Wire_ID: number;
  WireBag: string;
  WireSlot: number;
}

export interface TblDetail {
  Detail: string | null;
  ID: Generated<number>;
}

export interface TblDiagnosis {
  Appliance: string | null;
  C_ANB: string | null;
  C_FMA: string | null;
  C_LAFH: string | null;
  C_LI_APo: string | null;
  C_LIMd: string | null;
  C_Llip_E: string | null;
  C_MMA: string | null;
  C_Naso_lip: string | null;
  C_PercentLAFH: string | null;
  C_SNA: string | null;
  C_SNB: string | null;
  C_SNMx: string | null;
  C_TAFH: string | null;
  C_UAFH: string | null;
  C_UI_LI: string | null;
  C_UIMX: string | null;
  C_Ulip_E: string | null;
  C_Wits: string | null;
  ChiefComplain: string | null;
  Diagnosis: string;
  DxDate: Timestamp | null;
  fAnteroPosterior: string | null;
  fLipCompetence: string | null;
  fNasoLabialAngle: string | null;
  fTransverse: string | null;
  fUpperIncisorShowRest: string | null;
  fUpperIncisorShowSmile: string | null;
  fVertical: string | null;
  ICurveofSpee: string | null;
  ID: Generated<number>;
  IDentalHealth: string | null;
  ILowerCrowding: string | null;
  ILowerIncisorInclination: string | null;
  ITeethPresent: string | null;
  IUpperCrowding: string | null;
  IUpperIncisorInclination: string | null;
  OCanineRelation: string | null;
  OCenterlines: string | null;
  OFunctionalOcclusion: string | null;
  OIncisorRelation: string | null;
  OMolarRelation: string | null;
  OOverbite: string | null;
  OOverjet: string | null;
  TreatmentPlan: string;
  WorkID: number;
}

export interface TblElastics {
  Elastic: string;
  Elastic_ID: Generated<number>;
}

export interface TblEmployees {
  AppointmentColor: string | null;
  Email: string | null;
  employeeName: string;
  getAppointments: Generated<boolean>;
  ID: Generated<number>;
  Percentage: Generated<boolean>;
  Phone: string | null;
  Position: number | null;
  receiveEmail: Generated<boolean>;
  SortOrder: Generated<number>;
}

export interface TblEndo {
  Canal: string | null;
  Curvature: string | null;
  DetailID: number | null;
  ID: Generated<number>;
  Note: string | null;
  RefrencePoint: string | null;
  WorkingLength: Numeric | null;
}

export interface TblEstimatedCostPresets {
  Amount: Numeric;
  Currency: string;
  DisplayOrder: Generated<number | null>;
  PresetID: Generated<number>;
}

export interface TblExpenseCategories {
  CategoryID: Generated<number>;
  CategoryName: string;
}

export interface TblExpenses {
  Amount: number;
  CategoryID: number | null;
  Currency: string | null;
  expenseDate: Timestamp;
  ID: Generated<number>;
  Note: string | null;
  SubcategoryID: number | null;
}

export interface TblExpenseSubcategories {
  CategoryID: number;
  SubcategoryID: Generated<number>;
  SubcategoryName: string;
}

export interface TblGender {
  Gender: string;
  Gender_ID: number;
}

export interface Tblholidays {
  Description: string | null;
  Holidaydate: Timestamp;
  HolidayName: Generated<string>;
  ID: Generated<number>;
}

export interface TblImageTypes {
  Description: string | null;
  DolphinItypID: string | null;
  ImageTypeCode: string;
}

export interface TblImplant {
  ID: Generated<number>;
  ImplantCompany: string | null;
  ImplantDiameter: Numeric | null;
  ImplantLength: Numeric | null;
  Note: string | null;
  Tooth: string | null;
  WorkID: number;
}

export interface TblImplantManufacturer {
  ID: Generated<number>;
  ManufacturerName: string;
}

export interface TblInvoice {
  ActualAmount: number | null;
  ActualCur: string | null;
  AlignerSetID: number | null;
  Amountpaid: number;
  Change: number | null;
  Dateofpayment: Timestamp;
  invoiceID: Generated<number>;
  IQDReceived: Generated<number>;
  SysStartTime: Generated<Timestamp>;
  USDReceived: Generated<number>;
  workid: number;
}

export interface TblKeyWord {
  ID: Generated<number>;
  KeyWord: string | null;
}

export interface TblMessageStatusHistory {
  AppointmentID: number;
  StatusCode: number;
  StatusHistoryID: Generated<number>;
  StatusText: string;
  Timestamp: Generated<Timestamp>;
  WaMessageID: string;
}

export interface Tblnumbers {
  Mynumber: Generated<number>;
}

export interface TblOldOPG {
  birth_date: Timestamp | null;
  directory: string;
  first_name: string;
  ID: number;
  last_name: string;
  sex: string;
}

export interface Tbloptions {
  OptionName: string;
  OptionValue: string | null;
}

export interface TblPatientPortalAuth {
  CreatedAt: Generated<Timestamp>;
  Enabled: Generated<boolean>;
  FailedAttempts: Generated<number>;
  LastLoginAt: Timestamp | null;
  LockedUntil: Timestamp | null;
  PersonID: number;
  PinHash: string;
  UpdatedAt: Generated<Timestamp>;
}

export interface Tblpatients {
  AddressID: number | null;
  CountryCode: string | null;
  Currency: string | null;
  DateAdded: Generated<Timestamp | null>;
  DateofBirth: Timestamp | null;
  Email: string | null;
  EstimatedCost: number | null;
  FirstName: string | null;
  Gender: number | null;
  Language: Generated<number | null>;
  LastName: string | null;
  Notes: string | null;
  patientID: string | null;
  PatientName: string;
  PatientTypeID: number | null;
  PersonID: Generated<number>;
  Phone: string | null;
  Phone2: string | null;
  ReferralSourceID: number | null;
  TagID: number | null;
  WebCephCreatedAt: Timestamp | null;
  WebCephLink: string | null;
  WebCephPatientID: string | null;
}

export interface TblPatientType {
  ID: Generated<number>;
  PatientType: string | null;
}

export interface TblPositions {
  ID: Generated<number>;
  PositionName: string | null;
}

export interface TblPrivatePhotos {
  ImageName: string;
  MarkedAt: Generated<Timestamp>;
  MarkedBy: number | null;
  PersonID: number;
  TimepointCode: string;
}

export interface TblReferrals {
  ID: Generated<number>;
  Referral: string | null;
}

export interface Tblscrews {
  ID: Generated<number>;
  PersonID: Generated<number>;
  PlacementDate: Timestamp | null;
  Position: string | null;
  State: string | null;
  WorkID: Generated<number | null>;
}

export interface Tblsms {
  date: Timestamp;
  emailsent: Generated<boolean>;
  ExchangeRate: number | null;
  id: Generated<number>;
  SMSID: string | null;
  smssent: Generated<boolean>;
}

export interface TblStandCategories {
  CategoryID: Generated<number>;
  CategoryName: string;
  IsActive: Generated<boolean>;
}

export interface TblStandItems {
  Barcode: string | null;
  CategoryID: number | null;
  CostPrice: number;
  CreatedBy: number | null;
  CurrentStock: Generated<number>;
  DateAdded: Generated<Timestamp>;
  ExpiryDate: Timestamp | null;
  IsActive: Generated<boolean>;
  ItemID: Generated<number>;
  ItemName: string;
  ModifiedDate: Timestamp | null;
  Notes: string | null;
  ReorderLevel: Generated<number>;
  SellPrice: number;
  SKU: string | null;
  Unit: string | null;
}

export interface TblStandSaleItems {
  ItemID: number;
  LineTotal: number;
  Quantity: number;
  SaleID: number;
  SaleItemID: Generated<number>;
  UnitCost: number;
  UnitPrice: number;
}

export interface TblStandSales {
  AmountPaid: number;
  CashierID: number | null;
  Change: Generated<number>;
  CustomerNote: string | null;
  PaymentMethod: Generated<string>;
  PersonID: number | null;
  SaleDate: Generated<Timestamp>;
  SaleID: Generated<number>;
  TotalAmount: number;
  TotalCost: number;
  TotalProfit: number;
  VoidedBy: number | null;
  VoidedDate: Timestamp | null;
  VoidReason: string | null;
}

export interface TblStandStockMovements {
  ItemID: number;
  MovementDate: Generated<Timestamp>;
  MovementID: Generated<number>;
  MovementType: string;
  PerformedBy: number | null;
  Quantity: number;
  Reason: string | null;
  RelatedSaleID: number | null;
  TotalCost: number | null;
  UnitCost: number | null;
}

export interface TblTagOptions {
  ID: Generated<number>;
  Tag: string;
}

export interface TblTimePointImages {
  DolphinTpiID: string | null;
  ImageDate: Timestamp | null;
  ImageFile: string | null;
  ImageType: string | null;
  PersonID: number;
  TimePointID: number;
  TimePointImageID: Generated<number>;
  Title: string | null;
}

export interface TblTimePoints {
  CreatedDate: Generated<Timestamp>;
  DolphinPatID: string | null;
  DolphinTpID: string | null;
  PersonID: number;
  TimePointID: Generated<number>;
  tpCode: number;
  tpDateTime: Timestamp | null;
  tpDescription: string | null;
}

export interface Tbltimes {
  MyTime: string | null;
  TimeID: Generated<number>;
}

export interface TblToothNumber {
  ID: Generated<number>;
  IsPermanent: Generated<boolean>;
  Quadrant: string;
  SortOrder: number;
  ToothCode: string;
  ToothName: string;
  ToothNumber: string;
}

export interface TblUsers {
  CreatedAt: Generated<Timestamp | null>;
  CreatedBy: string | null;
  FullName: string | null;
  IsActive: Generated<boolean | null>;
  LastLogin: Timestamp | null;
  PasswordHash: string;
  Role: Generated<string | null>;
  UserID: Generated<number>;
  Username: string;
}

export interface TblVidCat {
  Category: string | null;
  VidCatID: Generated<number>;
}

export interface Tblvideos {
  Category: number | null;
  Description: string;
  Details: string | null;
  FileName: string | null;
  ID: Generated<number>;
  URL: string | null;
  VideoExtension: string | null;
}

export interface Tblvisits {
  ApplianceRemoved: Generated<boolean | null>;
  BracketChange: string | null;
  CreatedAt: Timestamp | null;
  Elastics: string | null;
  FPhoto: Generated<boolean | null>;
  ID: Generated<number>;
  IPhoto: Generated<boolean | null>;
  LowerWireID: number | null;
  NextVisit: string | null;
  OperatorID: number | null;
  OPG: Generated<boolean | null>;
  Others: string | null;
  PPhoto: Generated<boolean | null>;
  UpperWireID: number | null;
  VisitDate: Timestamp;
  WireBending: string | null;
  WorkID: number;
}

export interface TblWaiting {
  Creation_Date: Timestamp;
  ID: Generated<number>;
  PersonID: number;
  TypeID: number | null;
}

export interface TblWaitReason {
  ID: Generated<number>;
  WaitType: string | null;
}

export interface TblWires {
  Wire: string;
  Wire_ID: Generated<number>;
}

export interface Tblwork {
  AdditionDate: Generated<Timestamp | null>;
  Currency: string | null;
  DebondDate: Timestamp | null;
  Discount: number | null;
  DiscountDate: Timestamp | null;
  DiscountReason: string | null;
  DrID: number;
  EstimatedDuration: number | null;
  FPhotoDate: Timestamp | null;
  IPhotoDate: Timestamp | null;
  KeyWordID1: number | null;
  KeyWordID2: number | null;
  KeywordID3: number | null;
  KeywordID4: number | null;
  KeywordID5: number | null;
  Notes: string | null;
  NotesDate: Timestamp | null;
  PersonID: number;
  StartDate: Timestamp | null;
  Status: Generated<number>;
  TotalRequired: number;
  Typeofwork: number;
  workid: Generated<number>;
}

export interface TblWorkItems {
  CanalsNo: number | null;
  CompletedDate: Timestamp | null;
  FillingDepth: string | null;
  FillingType: string | null;
  ID: Generated<number>;
  ImplantDiameter: Numeric | null;
  ImplantLength: Numeric | null;
  ImplantManufacturerID: number | null;
  ItemCost: number | null;
  LabName: string | null;
  Material: string | null;
  Note: string | null;
  StartDate: Timestamp | null;
  WorkID: number;
  WorkingLength: string | null;
}

export interface TblWorkItemTeeth {
  ID: Generated<number>;
  ToothID: number;
  WorkItemID: number;
}

export interface TblWorkStatus {
  StatusID: number;
  StatusName: string;
}

export interface TblWorkType {
  ID: Generated<number>;
  WorkType: string;
}

export interface DB {
  AlignerDoctors: AlignerDoctors;
  DocumentTemplates: DocumentTemplates;
  DocumentTypes: DocumentTypes;
  Patients: Patients;
  pgmigrations: Pgmigrations;
  SyncQueue: SyncQueue;
  tbCities: TbCities;
  tblAddress: TblAddress;
  tblAlerts: TblAlerts;
  tblAlertTypes: TblAlertTypes;
  tblAlignerActivityFlags: TblAlignerActivityFlags;
  tblAlignerBatches: TblAlignerBatches;
  tblAlignerNotes: TblAlignerNotes;
  tblAlignerSets: TblAlignerSets;
  tblappointments: Tblappointments;
  tblbends: Tblbends;
  tblCalender: TblCalender;
  tblCarriedWires: TblCarriedWires;
  tblDetail: TblDetail;
  tblDiagnosis: TblDiagnosis;
  tblElastics: TblElastics;
  tblEmployees: TblEmployees;
  tblEndo: TblEndo;
  tblEstimatedCostPresets: TblEstimatedCostPresets;
  tblExpenseCategories: TblExpenseCategories;
  tblExpenses: TblExpenses;
  tblExpenseSubcategories: TblExpenseSubcategories;
  tblGender: TblGender;
  tblholidays: Tblholidays;
  tblImageTypes: TblImageTypes;
  tblImplant: TblImplant;
  tblImplantManufacturer: TblImplantManufacturer;
  tblInvoice: TblInvoice;
  tblKeyWord: TblKeyWord;
  tblMessageStatusHistory: TblMessageStatusHistory;
  tblnumbers: Tblnumbers;
  tblOldOPG: TblOldOPG;
  tbloptions: Tbloptions;
  tblPatientPortalAuth: TblPatientPortalAuth;
  tblpatients: Tblpatients;
  tblPatientType: TblPatientType;
  tblPositions: TblPositions;
  tblPrivatePhotos: TblPrivatePhotos;
  tblReferrals: TblReferrals;
  tblscrews: Tblscrews;
  tblsms: Tblsms;
  tblStandCategories: TblStandCategories;
  tblStandItems: TblStandItems;
  tblStandSaleItems: TblStandSaleItems;
  tblStandSales: TblStandSales;
  tblStandStockMovements: TblStandStockMovements;
  tblTagOptions: TblTagOptions;
  tblTimePointImages: TblTimePointImages;
  tblTimePoints: TblTimePoints;
  tbltimes: Tbltimes;
  tblToothNumber: TblToothNumber;
  tblUsers: TblUsers;
  tblVidCat: TblVidCat;
  tblvideos: Tblvideos;
  tblvisits: Tblvisits;
  tblWaiting: TblWaiting;
  tblWaitReason: TblWaitReason;
  tblWires: TblWires;
  tblwork: Tblwork;
  tblWorkItems: TblWorkItems;
  tblWorkItemTeeth: TblWorkItemTeeth;
  tblWorkStatus: TblWorkStatus;
  tblWorkType: TblWorkType;
}
