/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Addresses {
  city_id: number | null;
  id: Generated<number>;
  zone: string | null;
}

export interface Alerts {
  alert_details: string | null;
  alert_id: Generated<number>;
  alert_severity: number;
  alert_type_id: number;
  creation_date: Generated<Timestamp>;
  is_active: Generated<boolean>;
  person_id: number;
}

export interface AlertTypes {
  alert_type_id: Generated<number>;
  type_name: string;
}

export interface AlignerActivityFlags {
  activity_description: string;
  activity_id: Generated<number>;
  activity_type: string;
  aligner_set_id: number;
  created_at: Generated<Timestamp | null>;
  is_read: Generated<boolean | null>;
  read_at: Timestamp | null;
  related_record_id: number | null;
}

export interface AlignerBatches {
  aligner_batch_id: Generated<number>;
  aligner_set_id: number;
  batch_expiry_date: Generated<Timestamp | null>;
  batch_sequence: number;
  creation_date: Generated<Timestamp>;
  days: number | null;
  delivered_to_patient_date: Timestamp | null;
  has_lower_template: Generated<boolean>;
  has_upper_template: Generated<boolean>;
  is_active: Generated<boolean | null>;
  is_last: Generated<boolean>;
  lower_aligner_count: number;
  lower_aligner_end_sequence: Generated<number | null>;
  lower_aligner_start_sequence: number | null;
  manufacture_date: Timestamp | null;
  notes: string | null;
  upper_aligner_count: number;
  upper_aligner_end_sequence: Generated<number | null>;
  upper_aligner_start_sequence: number | null;
  validity_period: Generated<number | null>;
}

export interface AlignerDoctors {
  doctor_email: string | null;
  doctor_name: string;
  dr_id: Generated<number>;
  logo_path: string | null;
}

export interface AlignerNotes {
  aligner_set_id: number;
  created_at: Generated<Timestamp | null>;
  edited_at: Timestamp | null;
  is_edited: Generated<boolean | null>;
  is_read: Generated<boolean>;
  note_id: Generated<number>;
  note_text: string;
  note_type: string;
}

export interface AlignerSets {
  aligner_dr_id: number;
  aligner_set_id: Generated<number>;
  archform_id: number | null;
  creation_date: Timestamp | null;
  currency: Generated<string | null>;
  days: number | null;
  drive_file_id: string | null;
  folder_path: string | null;
  is_active: Generated<boolean | null>;
  lower_aligners_count: number | null;
  notes: string | null;
  pdf_uploaded_at: Timestamp | null;
  pdf_uploaded_by: string | null;
  remaining_lower_aligners: number | null;
  remaining_upper_aligners: number | null;
  set_cost: Numeric | null;
  set_pdf_url: string | null;
  set_sequence: number | null;
  set_url: string | null;
  set_video: string | null;
  type: string | null;
  upper_aligners_count: number | null;
  work_id: number;
}

export interface Appointments {
  app_cost: string | null;
  app_date: Timestamp;
  app_day: Generated<Timestamp | null>;
  app_detail: string | null;
  app_time: Generated<string | null>;
  appointment_id: Generated<number>;
  delivered_timestamp: Timestamp | null;
  delivered_wa: string | null;
  dismissed: string | null;
  dr_id: number | null;
  last_updated: Timestamp | null;
  notified: Generated<boolean | null>;
  person_id: number;
  present: string | null;
  read_timestamp: Timestamp | null;
  seated: string | null;
  sent_timestamp: Timestamp | null;
  sent_wa: boolean | null;
  sms_sid: string | null;
  sms_status: string | null;
  wa_message_id: string | null;
  want_notify: Generated<boolean | null>;
  want_wa: Generated<boolean | null>;
}

export interface Bends {
  bend: string;
  bend_id: Generated<number>;
}

export interface Calendar {
  app_date: Timestamp;
}

export interface CarriedWires {
  addition_date: Timestamp;
  id: Generated<number>;
  person_id: number;
  upper_lower: string;
  wire_bag: string;
  wire_id: number;
  wire_slot: number;
}

export interface CdcSinkControl {
  enabled: Generated<boolean>;
  note: string | null;
  sink: string;
  stale: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface ChangeLog {
  changed_at: Generated<Timestamp>;
  id: Generated<Int8>;
  op: string;
  pk: string;
  sink: string;
  tbl: string;
}

export interface Cities {
  city: string | null;
  id: Generated<number>;
}

export interface Details {
  detail: string | null;
  id: Generated<number>;
}

export interface Diagnoses {
  appliance: string | null;
  c_anb: string | null;
  c_fma: string | null;
  c_lafh: string | null;
  c_li_a_po: string | null;
  c_li_md: string | null;
  c_llip_e: string | null;
  c_mma: string | null;
  c_naso_lip: string | null;
  c_percent_lafh: string | null;
  c_sn_mx: string | null;
  c_sna: string | null;
  c_snb: string | null;
  c_tafh: string | null;
  c_uafh: string | null;
  c_ui_li: string | null;
  c_uimx: string | null;
  c_ulip_e: string | null;
  c_wits: string | null;
  chief_complain: string | null;
  diagnosis: string;
  dx_date: Timestamp | null;
  f_antero_posterior: string | null;
  f_lip_competence: string | null;
  f_naso_labial_angle: string | null;
  f_transverse: string | null;
  f_upper_incisor_show_rest: string | null;
  f_upper_incisor_show_smile: string | null;
  f_vertical: string | null;
  i_curveof_spee: string | null;
  i_dental_health: string | null;
  i_lower_crowding: string | null;
  i_lower_incisor_inclination: string | null;
  i_teeth_present: string | null;
  i_upper_crowding: string | null;
  i_upper_incisor_inclination: string | null;
  id: Generated<number>;
  o_canine_relation: string | null;
  o_centerlines: string | null;
  o_functional_occlusion: string | null;
  o_incisor_relation: string | null;
  o_molar_relation: string | null;
  o_overbite: string | null;
  o_overjet: string | null;
  treatment_plan: string;
  work_id: number;
}

export interface DocumentTemplates {
  background_color: Generated<string | null>;
  created_by: string | null;
  created_date: Generated<Timestamp | null>;
  description: string | null;
  document_type_id: number;
  grid_size: Generated<number | null>;
  is_active: Generated<boolean | null>;
  is_default: Generated<boolean | null>;
  is_system: Generated<boolean | null>;
  last_used_date: Timestamp | null;
  modified_by: string | null;
  modified_date: Timestamp | null;
  paper_height: number;
  paper_margin_bottom: Generated<number | null>;
  paper_margin_left: Generated<number | null>;
  paper_margin_right: Generated<number | null>;
  paper_margin_top: Generated<number | null>;
  paper_orientation: Generated<string | null>;
  paper_width: number;
  parent_template_id: number | null;
  show_grid: Generated<boolean | null>;
  template_file_path: string | null;
  template_id: Generated<number>;
  template_name: string;
  template_version: Generated<number | null>;
}

export interface DocumentTypes {
  default_orientation: Generated<string | null>;
  default_paper_height: Generated<number | null>;
  default_paper_width: Generated<number | null>;
  description: string | null;
  icon: string | null;
  is_active: Generated<boolean | null>;
  sort_order: Generated<number | null>;
  type_code: string;
  type_id: Generated<number>;
  type_name: string;
}

export interface DolphinSyncMap {
  created_at: Generated<Timestamp>;
  dolphin_id: string;
  local_pk: string;
  local_table: string;
}

export interface Elastics {
  elastic: string;
  elastic_id: Generated<number>;
}

export interface Employees {
  appointment_color: string | null;
  email: string | null;
  employee_name: string;
  get_appointments: Generated<boolean>;
  id: Generated<number>;
  percentage: Generated<boolean>;
  phone: string | null;
  position: number | null;
  receive_email: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface Endo {
  canal: string | null;
  curvature: string | null;
  detail_id: number | null;
  id: Generated<number>;
  note: string | null;
  refrence_point: string | null;
  working_length: Numeric | null;
}

export interface EstimatedCostPresets {
  amount: Numeric;
  currency: string;
  display_order: Generated<number | null>;
  preset_id: Generated<number>;
}

export interface ExpenseCategories {
  category_id: Generated<number>;
  category_name: string;
}

export interface Expenses {
  amount: number;
  category_id: number | null;
  currency: string | null;
  expense_date: Timestamp;
  id: Generated<number>;
  note: string | null;
  subcategory_id: number | null;
}

export interface ExpenseSubcategories {
  category_id: number;
  subcategory_id: Generated<number>;
  subcategory_name: string;
}

export interface Genders {
  gender: string;
  gender_id: number;
}

export interface Holidays {
  description: string | null;
  holiday_date: Timestamp;
  holiday_name: Generated<string>;
  id: Generated<number>;
}

export interface ImageTypes {
  description: string | null;
  dolphin_ityp_id: string | null;
  image_type_code: string;
}

export interface ImplantManufacturers {
  id: Generated<number>;
  manufacturer_name: string;
}

export interface Implants {
  id: Generated<number>;
  implant_company: string | null;
  implant_diameter: Numeric | null;
  implant_length: Numeric | null;
  note: string | null;
  tooth: string | null;
  work_id: number;
}

export interface Invoices {
  actual_amount: number | null;
  actual_cur: string | null;
  aligner_set_id: number | null;
  amount_paid: number;
  change: number | null;
  date_of_payment: Timestamp;
  invoice_id: Generated<number>;
  iqd_received: Generated<number>;
  sys_start_time: Generated<Timestamp>;
  usd_received: Generated<number>;
  work_id: number;
}

export interface Keywords {
  id: Generated<number>;
  key_word: string | null;
}

export interface MessageStatusHistory {
  appointment_id: number;
  status_code: number;
  status_history_id: Generated<number>;
  status_text: string;
  timestamp: Generated<Timestamp>;
  wa_message_id: string;
}

export interface Numbers {
  my_number: Generated<number>;
}

export interface OldOpg {
  birth_date: Timestamp | null;
  directory: string;
  first_name: string;
  id: number;
  last_name: string;
  sex: string;
}

export interface Options {
  option_name: string;
  option_value: string | null;
}

export interface PatientPortalAuth {
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  failed_attempts: Generated<number>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  person_id: number;
  pin_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface Patients {
  address_id: number | null;
  country_code: string | null;
  currency: string | null;
  date_added: Generated<Timestamp | null>;
  date_of_birth: Timestamp | null;
  email: string | null;
  estimated_cost: number | null;
  first_name: string | null;
  gender: number | null;
  language: Generated<number | null>;
  last_name: string | null;
  notes: string | null;
  patient_id: string | null;
  patient_name: string;
  patient_type_id: number | null;
  person_id: Generated<number>;
  phone: string | null;
  phone2: string | null;
  referral_source_id: number | null;
  tag_id: number | null;
  web_ceph_created_at: Timestamp | null;
  web_ceph_link: string | null;
  web_ceph_patient_id: string | null;
}

export interface PatientsDolphin {
  pat_birthdate: Timestamp | null;
  pat_first_name: string | null;
  pat_gender: string | null;
  pat_id: string;
  pat_last_name: string | null;
  pat_name: string | null;
  pat_other_id: string | null;
  pat_phone1: string | null;
}

export interface PatientTypes {
  id: Generated<number>;
  patient_type: string | null;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PortalSessions {
  expire: Timestamp;
  sess: Json;
  sid: string;
}

export interface Positions {
  id: Generated<number>;
  position_name: string | null;
}

export interface PrivatePhotos {
  image_name: string;
  marked_at: Generated<Timestamp>;
  marked_by: number | null;
  person_id: number;
  timepoint_code: string;
}

export interface Referrals {
  id: Generated<number>;
  referral: string | null;
}

export interface Screws {
  id: Generated<number>;
  person_id: Generated<number>;
  placement_date: Timestamp | null;
  position: string | null;
  state: string | null;
  work_id: Generated<number | null>;
}

export interface Sms {
  date: Timestamp;
  email_sent: Generated<boolean>;
  exchange_rate: number | null;
  id: Generated<number>;
  sms_id: string | null;
  sms_sent: Generated<boolean>;
}

export interface StaffSessions {
  expire: Timestamp;
  sess: Json;
  sid: string;
}

export interface StandCategories {
  category_id: Generated<number>;
  category_name: string;
  is_active: Generated<boolean>;
}

export interface StandItems {
  barcode: string | null;
  category_id: number | null;
  cost_price: number;
  created_by: number | null;
  current_stock: Generated<number>;
  date_added: Generated<Timestamp>;
  expiry_date: Timestamp | null;
  is_active: Generated<boolean>;
  item_id: Generated<number>;
  item_name: string;
  modified_date: Timestamp | null;
  notes: string | null;
  reorder_level: Generated<number>;
  sell_price: number;
  sku: string | null;
  unit: string | null;
}

export interface StandSaleItems {
  item_id: number;
  line_total: number;
  quantity: number;
  sale_id: number;
  sale_item_id: Generated<number>;
  unit_cost: number;
  unit_price: number;
}

export interface StandSales {
  amount_paid: number;
  cashier_id: number | null;
  change: Generated<number>;
  customer_note: string | null;
  payment_method: Generated<string>;
  person_id: number | null;
  sale_date: Generated<Timestamp>;
  sale_id: Generated<number>;
  total_amount: number;
  total_cost: number;
  total_profit: number;
  void_reason: string | null;
  voided_by: number | null;
  voided_date: Timestamp | null;
}

export interface StandStockMovements {
  item_id: number;
  movement_date: Generated<Timestamp>;
  movement_id: Generated<number>;
  movement_type: string;
  performed_by: number | null;
  quantity: number;
  reason: string | null;
  related_sale_id: number | null;
  total_cost: number | null;
  unit_cost: number | null;
}

export interface SyncQueue {
  attempts: Generated<number | null>;
  created_at: Generated<Timestamp | null>;
  json_data: string | null;
  last_attempt: Timestamp | null;
  last_error: string | null;
  operation: string;
  queue_id: Generated<number>;
  record_id: number;
  status: Generated<string | null>;
  table_name: string;
}

export interface TagOptions {
  id: Generated<number>;
  tag: string;
}

export interface TimePointImages {
  dolphin_tpi_id: string | null;
  image_date: Timestamp | null;
  image_file: string | null;
  image_type: string | null;
  person_id: number;
  time_point_id: number;
  time_point_image_id: Generated<number>;
  title: string | null;
}

export interface TimePoints {
  created_date: Generated<Timestamp>;
  dolphin_pat_id: string | null;
  dolphin_tp_id: string | null;
  person_id: number;
  time_point_id: Generated<number>;
  tp_code: number;
  tp_date_time: Timestamp | null;
  tp_description: string | null;
}

export interface Times {
  my_time: string | null;
  time_id: Generated<number>;
}

export interface ToothNumbers {
  id: Generated<number>;
  is_permanent: Generated<boolean>;
  quadrant: string;
  sort_order: number;
  tooth_code: string;
  tooth_name: string;
  tooth_number: string;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  full_name: string | null;
  is_active: Generated<boolean | null>;
  last_login: Timestamp | null;
  password_hash: string;
  role: Generated<string | null>;
  user_id: Generated<number>;
  username: string;
}

export interface VideoCategories {
  category: string | null;
  vid_cat_id: Generated<number>;
}

export interface Videos {
  category: number | null;
  description: string;
  details: string | null;
  file_name: string | null;
  id: Generated<number>;
  url: string | null;
  video_extension: string | null;
}

export interface Visits {
  appliance_removed: Generated<boolean | null>;
  bracket_change: string | null;
  created_at: Timestamp | null;
  elastics: string | null;
  f_photo: Generated<boolean | null>;
  i_photo: Generated<boolean | null>;
  id: Generated<number>;
  lower_wire_id: number | null;
  next_visit: string | null;
  operator_id: number | null;
  opg: Generated<boolean | null>;
  others: string | null;
  p_photo: Generated<boolean | null>;
  upper_wire_id: number | null;
  visit_date: Timestamp;
  wire_bending: string | null;
  work_id: number;
}

export interface Waiting {
  creation_date: Timestamp;
  id: Generated<number>;
  person_id: number;
  type_id: number | null;
}

export interface WaitReasons {
  id: Generated<number>;
  wait_type: string | null;
}

export interface Wires {
  wire: string;
  wire_id: Generated<number>;
}

export interface WorkItems {
  canals_no: number | null;
  completed_date: Timestamp | null;
  filling_depth: string | null;
  filling_type: string | null;
  id: Generated<number>;
  implant_diameter: Numeric | null;
  implant_length: Numeric | null;
  implant_manufacturer_id: number | null;
  item_cost: number | null;
  lab_name: string | null;
  material: string | null;
  note: string | null;
  start_date: Timestamp | null;
  work_id: number;
  working_length: string | null;
}

export interface WorkItemTeeth {
  id: Generated<number>;
  tooth_id: number;
  work_item_id: number;
}

export interface Works {
  addition_date: Generated<Timestamp | null>;
  currency: string | null;
  debond_date: Timestamp | null;
  discount: number | null;
  discount_date: Timestamp | null;
  discount_reason: string | null;
  dr_id: number;
  estimated_duration: number | null;
  f_photo_date: Timestamp | null;
  i_photo_date: Timestamp | null;
  keyword_id_1: number | null;
  keyword_id_2: number | null;
  keyword_id_3: number | null;
  keyword_id_4: number | null;
  keyword_id_5: number | null;
  notes: string | null;
  notes_date: Timestamp | null;
  person_id: number;
  start_date: Timestamp | null;
  status: Generated<number>;
  total_required: number;
  type_of_work: number;
  work_id: Generated<number>;
}

export interface WorkStatuses {
  status_id: number;
  status_name: string;
}

export interface WorkTypes {
  id: Generated<number>;
  work_type: string;
}

export interface DB {
  addresses: Addresses;
  alert_types: AlertTypes;
  alerts: Alerts;
  aligner_activity_flags: AlignerActivityFlags;
  aligner_batches: AlignerBatches;
  aligner_doctors: AlignerDoctors;
  aligner_notes: AlignerNotes;
  aligner_sets: AlignerSets;
  appointments: Appointments;
  bends: Bends;
  calendar: Calendar;
  carried_wires: CarriedWires;
  cdc_sink_control: CdcSinkControl;
  change_log: ChangeLog;
  cities: Cities;
  details: Details;
  diagnoses: Diagnoses;
  document_templates: DocumentTemplates;
  document_types: DocumentTypes;
  dolphin_sync_map: DolphinSyncMap;
  elastics: Elastics;
  employees: Employees;
  endo: Endo;
  estimated_cost_presets: EstimatedCostPresets;
  expense_categories: ExpenseCategories;
  expense_subcategories: ExpenseSubcategories;
  expenses: Expenses;
  genders: Genders;
  holidays: Holidays;
  image_types: ImageTypes;
  implant_manufacturers: ImplantManufacturers;
  implants: Implants;
  invoices: Invoices;
  keywords: Keywords;
  message_status_history: MessageStatusHistory;
  numbers: Numbers;
  old_opg: OldOpg;
  options: Options;
  patient_portal_auth: PatientPortalAuth;
  patient_types: PatientTypes;
  patients: Patients;
  patients_dolphin: PatientsDolphin;
  pgmigrations: Pgmigrations;
  portal_sessions: PortalSessions;
  positions: Positions;
  private_photos: PrivatePhotos;
  referrals: Referrals;
  screws: Screws;
  sms: Sms;
  staff_sessions: StaffSessions;
  stand_categories: StandCategories;
  stand_items: StandItems;
  stand_sale_items: StandSaleItems;
  stand_sales: StandSales;
  stand_stock_movements: StandStockMovements;
  sync_queue: SyncQueue;
  tag_options: TagOptions;
  time_point_images: TimePointImages;
  time_points: TimePoints;
  times: Times;
  tooth_numbers: ToothNumbers;
  users: Users;
  video_categories: VideoCategories;
  videos: Videos;
  visits: Visits;
  wait_reasons: WaitReasons;
  waiting: Waiting;
  wires: Wires;
  work_item_teeth: WorkItemTeeth;
  work_items: WorkItems;
  work_statuses: WorkStatuses;
  work_types: WorkTypes;
  works: Works;
}
