/**
 * Email API Routes
 * Handles appointment email notifications with PDF attachments
 */

import express from 'express';
import emailService from '../services/email/email-service.js';
import pdfGenerator from '../services/pdf/appointment-pdf-generator.js';

const router = express.Router();

/**
 * POST /api/email/send-appointments
 * Send appointment email to staff with PDF attachment
 * Query params: date (YYYY-MM-DD)
 */
router.post('/send-appointments', async (req, res) => {
    try {
        const { date } = req.query;

        if (!date) {
            return res.status(400).json({
                success: false,
                error: 'Date parameter is required (format: YYYY-MM-DD)'
            });
        }

        // Validate date format
        const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
        if (!dateRegex.test(date)) {
            return res.status(400).json({
                success: false,
                error: 'Invalid date format. Use YYYY-MM-DD'
            });
        }

        console.log(`Sending appointment email for ${date}`);

        // Generate PDF
        const pdfResult = await pdfGenerator.generateAppointmentPDF(date);

        if (!pdfResult.success) {
            return res.status(500).json({
                success: false,
                error: 'Failed to generate PDF'
            });
        }

        // Format date for email
        const dateObj = new Date(date);
        const formattedDate = dateObj.toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        // Email content
        const subject = `Daily Appointments - ${formattedDate}`;
        const html = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background-color: #0066cc; color: white; padding: 20px; text-align: center;">
                    <h1 style="margin: 0;">Shwan Orthodontics</h1>
                    <p style="margin: 5px 0 0 0;">Daily Appointments Report</p>
                </div>

                <div style="padding: 20px; background-color: #f9f9f9;">
                    <h2 style="color: #333;">Appointments for ${formattedDate}</h2>
                    <p style="font-size: 16px; color: #666;">
                        Total appointments scheduled: <strong>${pdfResult.appointmentCount}</strong>
                    </p>

                    ${pdfResult.appointmentCount > 0 ? `
                        <p style="color: #666;">
                            Please find the detailed appointment list attached as a PDF document.
                        </p>
                    ` : `
                        <p style="color: #ff6600; font-style: italic;">
                            No appointments are scheduled for this date.
                        </p>
                    `}
                </div>

                <div style="padding: 20px; background-color: #fff; border-top: 1px solid #ddd;">
                    <p style="font-size: 12px; color: #999; margin: 0;">
                        This email was automatically generated by the Shwan Orthodontics clinic management system.
                    </p>
                    <p style="font-size: 12px; color: #999; margin: 5px 0 0 0;">
                        Generated on: ${new Date().toLocaleString()}
                    </p>
                </div>
            </div>
        `;

        const text = `
Daily Appointments Report - Shwan Orthodontics

Date: ${formattedDate}
Total Appointments: ${pdfResult.appointmentCount}

${pdfResult.appointmentCount > 0 ? 'Please see the attached PDF for the detailed appointment list.' : 'No appointments are scheduled for this date.'}

---
This email was automatically generated on ${new Date().toLocaleString()}
        `.trim();

        // Send email
        const emailResult = await emailService.sendEmail({
            subject,
            html,
            text,
            pdfBuffer: pdfResult.buffer,
            pdfFilename: `appointments-${date}.pdf`
        });

        res.json({
            success: true,
            message: 'Appointment email sent successfully',
            date: date,
            appointmentCount: pdfResult.appointmentCount,
            messageId: emailResult.messageId
        });

    } catch (error) {
        console.error('Failed to send appointment email:', error);
        res.status(500).json({
            success: false,
            error: error.message || 'Failed to send appointment email',
            details: error.toString()
        });
    }
});

/**
 * GET /api/email/config
 * Get current email configuration (password masked)
 */
router.get('/config', async (req, res) => {
    try {
        await emailService.loadConfig();
        const config = emailService.getConfig();

        if (!config) {
            return res.status(404).json({
                success: false,
                error: 'Email configuration not found'
            });
        }

        res.json({
            success: true,
            config: config
        });
    } catch (error) {
        console.error('Failed to get email configuration:', error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * POST /api/email/config
 * Update email configuration
 */
router.post('/config', async (req, res) => {
    try {
        const newConfig = req.body;

        if (!newConfig || Object.keys(newConfig).length === 0) {
            return res.status(400).json({
                success: false,
                error: 'Configuration data is required'
            });
        }

        const result = await emailService.updateConfig(newConfig);

        res.json({
            success: true,
            message: result.message,
            updated: result.updated
        });
    } catch (error) {
        console.error('Failed to update email configuration:', error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * GET /api/email/test
 * Test email configuration and connection
 */
router.get('/test', async (req, res) => {
    try {
        const result = await emailService.testConnection();

        res.json({
            success: result.success,
            message: result.message,
            error: result.error
        });
    } catch (error) {
        console.error('Email test failed:', error);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.toString()
        });
    }
});

/**
 * POST /api/email/test-send
 * Send a test email
 */
router.post('/test-send', async (req, res) => {
    try {
        const { to } = req.body;

        const testEmail = {
            to: to || undefined, // Use default if not provided
            subject: 'Test Email - Shwan Orthodontics',
            html: `
                <div style="font-family: Arial, sans-serif; padding: 20px;">
                    <h2 style="color: #0066cc;">Email Configuration Test</h2>
                    <p>This is a test email from Shwan Orthodontics clinic management system.</p>
                    <p>If you received this email, your email configuration is working correctly!</p>
                    <hr>
                    <p style="font-size: 12px; color: #999;">Sent at: ${new Date().toLocaleString()}</p>
                </div>
            `,
            text: `Email Configuration Test\n\nThis is a test email from Shwan Orthodontics.\nIf you received this, your configuration is working!\n\nSent at: ${new Date().toLocaleString()}`
        };

        const result = await emailService.sendEmail(testEmail);

        res.json({
            success: true,
            message: 'Test email sent successfully',
            messageId: result.messageId,
            to: to || emailService.config.to_staff
        });
    } catch (error) {
        console.error('Test email failed:', error);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.toString()
        });
    }
});

export default router;
