/**
 * Email API Routes
 * Handles appointment email notifications with PDF attachments
 */

import { Router, type Request, type Response } from 'express';
import { log } from '../utils/logger.js';
import emailService from '../services/email/email-service.js';
import pdfGenerator from '../services/pdf/appointment-pdf-generator.js';
import { validate } from '../middleware/validate.js';
import { sendData, ErrorResponses } from '../utils/error-response.js';
import * as emailApi from '../shared/contracts/email-api.contract.js';

const router = Router();

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

interface SendAppointmentsQuery {
  date?: string;
}


/**
 * POST /api/email/send-appointments
 * Send appointment email to staff with PDF attachment
 * Query params: date (YYYY-MM-DD)
 *
 * NOTE (Phase 14): deliberately NOT migrated to `sendData`. Its consumer is the
 * RAW whatsapp `apiClient` (WhatsAppSend.tsx), which reads `appointmentCount`/
 * `success` at the TOP LEVEL and does NOT unwrap the `{success,data}` envelope —
 * nesting the payload would hide those fields. Stays a top-level manual envelope.
 */
router.post(
  '/send-appointments',
  async (
    req: Request<unknown, unknown, unknown, SendAppointmentsQuery>,
    res: Response
  ): Promise<void> => {
    try {
      const { date } = req.query;

      if (!date) {
        res.status(400).json({
          success: false,
          error: 'Date parameter is required (format: YYYY-MM-DD)'
        });
        return;
      }

      // Validate date format
      const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
      if (!dateRegex.test(date)) {
        res.status(400).json({
          success: false,
          error: 'Invalid date format. Use YYYY-MM-DD'
        });
        return;
      }

      log.info(`Sending appointment email for ${date}`);

      // Generate PDF
      const pdfResult = await pdfGenerator.generateAppointmentPDF(date);

      if (!pdfResult.success) {
        res.status(500).json({
          success: false,
          error: 'Failed to generate PDF'
        });
        return;
      }

      // Format date for email
      const dateObj = new Date(date);
      const formattedDate = dateObj.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });

      // Email content
      const subject = `Daily Appointments - ${formattedDate}`;
      const html = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background-color: #0066cc; color: white; padding: 20px; text-align: center;">
                    <h1 style="margin: 0;">Shwan Orthodontics</h1>
                    <p style="margin: 5px 0 0 0;">Daily Appointments Report</p>
                </div>

                <div style="padding: 20px; background-color: #f9f9f9;">
                    <h2 style="color: #333;">Appointments for ${formattedDate}</h2>
                    <p style="font-size: 16px; color: #666;">
                        Total appointments scheduled: <strong>${pdfResult.appointmentCount}</strong>
                    </p>

                    ${
                      pdfResult.appointmentCount > 0
                        ? `
                        <p style="color: #666;">
                            Please find the detailed appointment list attached as a PDF document.
                        </p>
                    `
                        : `
                        <p style="color: #ff6600; font-style: italic;">
                            No appointments are scheduled for this date.
                        </p>
                    `
                    }
                </div>

                <div style="padding: 20px; background-color: #fff; border-top: 1px solid #ddd;">
                    <p style="font-size: 12px; color: #999; margin: 0;">
                        This email was automatically generated by the Shwan Orthodontics clinic management system.
                    </p>
                    <p style="font-size: 12px; color: #999; margin: 5px 0 0 0;">
                        Generated on: ${new Date().toLocaleString()}
                    </p>
                </div>
            </div>
        `;

      const text = `
Daily Appointments Report - Shwan Orthodontics

Date: ${formattedDate}
Total Appointments: ${pdfResult.appointmentCount}

${pdfResult.appointmentCount > 0 ? 'Please see the attached PDF for the detailed appointment list.' : 'No appointments are scheduled for this date.'}

---
This email was automatically generated on ${new Date().toLocaleString()}
        `.trim();

      // Send email
      const emailResult = await emailService.sendEmail({
        subject,
        html,
        text,
        pdfBuffer: pdfResult.buffer,
        pdfFilename: `appointments-${date}.pdf`
      });

      res.json({
        success: true,
        message: 'Appointment email sent successfully',
        date: date,
        appointmentCount: pdfResult.appointmentCount,
        messageId: emailResult.messageId
      });
    } catch (error) {
      log.error('Failed to send appointment email', { error: (error as Error).message });
      res.status(500).json({
        success: false,
        error: (error as Error).message || 'Failed to send appointment email',
        details: (error as Error).toString()
      });
    }
  }
);

/**
 * GET /api/email/config
 * Get current email configuration (password masked)
 */
router.get(
  '/config',
  async (_req: Request, res: Response): Promise<void> => {
    try {
      await emailService.loadConfig();
      const currentConfig = emailService.getConfig();

      if (!currentConfig) {
        ErrorResponses.notFound(res, 'Email configuration');
        return;
      }

      sendData(res, emailApi.config.response, { config: currentConfig });
    } catch (error) {
      log.error('Failed to get email configuration', { error: (error as Error).message });
      ErrorResponses.internalError(res, (error as Error).message);
    }
  }
);

/**
 * POST /api/email/config
 * Update email configuration
 */
router.post(
  '/config',
  validate({ body: emailApi.updateConfig.body }),
  async (
    req: Request<unknown, unknown, emailApi.EmailConfigBody>,
    res: Response
  ): Promise<void> => {
    try {
      const newConfig = req.body;

      if (!newConfig || Object.keys(newConfig).length === 0) {
        ErrorResponses.badRequest(res, 'Configuration data is required');
        return;
      }

      const result = await emailService.updateConfig(newConfig);

      sendData(res, emailApi.updateConfig.response, {
        message: result.message,
        updated: result.updated
      });
    } catch (error) {
      log.error('Failed to update email configuration', { error: (error as Error).message });
      ErrorResponses.internalError(res, (error as Error).message);
    }
  }
);

/**
 * GET /api/email/test
 * Test email configuration and connection
 */
router.get(
  '/test',
  async (_req: Request, res: Response): Promise<void> => {
    try {
      const result = await emailService.testConnection();

      res.json({
        success: result.success,
        message: result.message,
        error: result.error
      });
    } catch (error) {
      log.error('Email test failed', { error: (error as Error).message });
      res.status(500).json({
        success: false,
        error: (error as Error).message,
        details: (error as Error).toString()
      });
    }
  }
);

/**
 * POST /api/email/test-send
 * Send a test email
 */
router.post(
  '/test-send',
  validate({ body: emailApi.testSend.body }),
  async (
    req: Request<unknown, unknown, emailApi.TestSendBody>,
    res: Response
  ): Promise<void> => {
    try {
      const { to } = req.body;

      const testEmail = {
        to: to || undefined, // Use default if not provided
        subject: 'Test Email - Shwan Orthodontics',
        html: `
                <div style="font-family: Arial, sans-serif; padding: 20px;">
                    <h2 style="color: #0066cc;">Email Configuration Test</h2>
                    <p>This is a test email from Shwan Orthodontics clinic management system.</p>
                    <p>If you received this email, your email configuration is working correctly!</p>
                    <hr>
                    <p style="font-size: 12px; color: #999;">Sent at: ${new Date().toLocaleString()}</p>
                </div>
            `,
        text: `Email Configuration Test\n\nThis is a test email from Shwan Orthodontics.\nIf you received this, your configuration is working!\n\nSent at: ${new Date().toLocaleString()}`
      };

      const result = await emailService.sendEmail(testEmail);

      sendData(res, emailApi.testSend.response, {
        message: 'Test email sent successfully',
        messageId: result.messageId
      });
    } catch (error) {
      log.error('Test email failed', { error: (error as Error).message });
      ErrorResponses.internalError(res, (error as Error).message);
    }
  }
);

export default router;
