-- Up Migration
--
-- Make private_photos CDC-capturable. The unified change feed (change_log.pk) is a single text
-- value and cdc_capture() takes ONE pk column, and the failover sink only mirrors tables whose
-- PRIMARY KEY is a single column (failover-sink.ts loadPks → array_length(indkey,1)=1, upsert keys
-- on ON CONFLICT (pkCol)). private_photos had a 3-column composite PK, so it was excluded.
--
-- Fix: add a surrogate single-column identity PK ("id"), demote the natural key to a UNIQUE
-- constraint (same dedup/integrity, and it remains the ON CONFLICT target used by markPrivate() in
-- services/database/queries/private-photos-queries.ts), then attach the capture trigger.
--
-- SIDE EFFECT (intentional, accepted): going-forward capture only. The Supabase mirror must be given
-- the matching "id"-PK schema and the existing rows loaded BY THE USER (C:\pg18-migration). Until
-- then the failover sink logs an upsert error on each private_photos change.

ALTER TABLE "private_photos" ADD COLUMN "id" bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "private_photos" DROP CONSTRAINT "pk_privatephotos";
ALTER TABLE "private_photos" ADD CONSTRAINT "pk_privatephotos_id" PRIMARY KEY ("id");
ALTER TABLE "private_photos" ADD CONSTRAINT "uq_privatephotos_natural"
  UNIQUE ("person_id", "timepoint_code", "image_name");

CREATE TRIGGER "trg_cdc_capture" AFTER INSERT OR UPDATE OR DELETE ON "private_photos"
  FOR EACH ROW EXECUTE FUNCTION "cdc_capture"('id', 'failover');

-- Down Migration

DROP TRIGGER IF EXISTS "trg_cdc_capture" ON "private_photos";
ALTER TABLE "private_photos" DROP CONSTRAINT IF EXISTS "uq_privatephotos_natural";
ALTER TABLE "private_photos" DROP CONSTRAINT IF EXISTS "pk_privatephotos_id";
ALTER TABLE "private_photos" DROP COLUMN IF EXISTS "id";
ALTER TABLE "private_photos" ADD CONSTRAINT "pk_privatephotos"
  PRIMARY KEY ("person_id", "timepoint_code", "image_name");
