-- Up Migration
--
-- PostgreSQL baseline schema for Shwan Orthodontics (Phase 2 of the SQL Server -> PG migration).
-- Hand-authored from migrations/init_script.sql (live ShwanNew_Test dump, 2026-05-28).
-- Tables + types + constraints + indexes ONLY. No procs/triggers/functions/views (those move to
-- TypeScript in Phase 5; views recreated later). Identifiers are double-quoted to preserve the
-- exact SQL Server casing so kysely-codegen output matches the existing CamelCase query code.
--
-- Locked type/collation decisions (see docs/postgres-migration-plan.md):
--   * Arabic_CI_AS text  -> citext (case-insensitive =, LIKE, unique; accent-sensitive). Exception:
--     the 2-char Dolphin image-type codes stay char(2) (load-bearing fixed codes).
--   * datetime/datetime2 -> timestamp WITHOUT time zone (wall-clock; never timestamptz / useUTC:false).
--   * bit -> boolean, uniqueidentifier -> uuid, tinyint -> smallint.
--   * IDENTITY -> GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT so ETL can insert explicit PKs).
--   * deterministic computed cols -> GENERATED ALWAYS ... STORED; getdate()-based ones dropped.
--   * getdate()/sysdatetime() default -> LOCALTIMESTAMP; sysutcdatetime() -> (now() AT TIME ZONE 'UTC').
--
-- Intentional deviations from a 1:1 port (flagged for review):
--   * tblInvoice was a SYSTEM_VERSIONED temporal table. System-versioning + History.tblInvoice are
--     dropped (no app consumer of the history). SysStartTime is kept as a plain created-at timestamp
--     (the app reads it as the payment time in DailyInvoicesModal); SysEndTime is dropped (unused).
--   * tblappointments.SSMA_TimeStamp (rowversion) dropped (verified unused).
--   * tblpatients.Age computed column dropped (used getdate() -> non-immutable; compute in app/view).
--   * Two CHECKs wrapping scalar fns (CK_MoreThanTotal, CK_MoreThanTotalW) and the getdate()-based
--     DOB CHECK are dropped; that logic moves to TypeScript in Phase 5.
--   * NEW unique constraints for Phase-4 ON CONFLICT upserts: tblsms(date), tblTimePointImages(TimePointID,ImageType).
--   * Redundant indexes that merely duplicate a PK / a sibling index are not recreated.

CREATE EXTENSION IF NOT EXISTS citext;

-- ========================================================================================
-- TABLES
-- ========================================================================================

CREATE TABLE "tblvisits" (
  "ID"               integer GENERATED BY DEFAULT AS IDENTITY,
  "WorkID"           integer NOT NULL,
  "VisitDate"        date NOT NULL,
  "BracketChange"    citext,
  "WireBending"      citext,
  "OPG"              boolean DEFAULT false,
  "Others"           citext,
  "NextVisit"        citext,
  "Elastics"         citext,
  "UpperWireID"      integer,
  "LowerWireID"      integer,
  "PPhoto"           boolean DEFAULT false,
  "IPhoto"           boolean DEFAULT false,
  "FPhoto"           boolean DEFAULT false,
  "ApplianceRemoved" boolean DEFAULT false,
  "OperatorID"       integer,
  "CreatedAt"        timestamp,
  CONSTRAINT "tblvisits$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblAlignerSets" (
  "AlignerSetID"           integer GENERATED BY DEFAULT AS IDENTITY,
  "WorkID"                 integer NOT NULL,
  "UpperAlignersCount"     integer,
  "LowerAlignersCount"     integer,
  "CreationDate"           date,
  "Notes"                  citext,
  "IsActive"               boolean DEFAULT true,
  "Days"                   integer,
  "FolderPath"             citext,
  "AlignerDrID"            integer NOT NULL,
  "Type"                   citext,
  "SetSequence"            integer,
  "RemainingUpperAligners" integer,
  "RemainingLowerAligners" integer,
  "SetUrl"                 citext,
  "SetPdfUrl"              citext,
  "SetCost"                numeric(10,2),
  "Currency"               citext DEFAULT 'USD',
  "PdfUploadedAt"          timestamp,
  "PdfUploadedBy"          citext,
  "DriveFileId"            citext,
  "SetVideo"               citext,
  "ArchformID"             integer,
  CONSTRAINT "PK__tblAlign__8C6E8FA44F19A436" PRIMARY KEY ("AlignerSetID"),
  CONSTRAINT "UQ_SetSequence_WorkID" UNIQUE NULLS NOT DISTINCT ("WorkID","SetSequence")
);

CREATE TABLE "tblInvoice" (
  "invoiceID"     integer GENERATED BY DEFAULT AS IDENTITY,
  "Amountpaid"    integer NOT NULL,
  "Dateofpayment" date NOT NULL,
  "workid"        integer NOT NULL,
  "SysStartTime"  timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  "ActualAmount"  integer,
  "ActualCur"     citext,
  "Change"        integer,
  "AlignerSetID"  integer,
  "USDReceived"   integer NOT NULL DEFAULT 0,
  "IQDReceived"   integer NOT NULL DEFAULT 0,
  CONSTRAINT "tblInvoice$PrimaryKey" PRIMARY KEY ("invoiceID"),
  CONSTRAINT "CHK_Invoice_AmountPaidPositive" CHECK ("Amountpaid" > 0),
  CONSTRAINT "CHK_Invoice_ChangeNonNegative"  CHECK ("Change" >= 0 OR "Change" IS NULL),
  CONSTRAINT "CHK_Invoice_IQDNonNegative"     CHECK ("IQDReceived" >= 0),
  CONSTRAINT "CHK_Invoice_MustReceiveCash"    CHECK ("USDReceived" > 0 OR "IQDReceived" > 0),
  CONSTRAINT "CHK_Invoice_USDNonNegative"     CHECK ("USDReceived" >= 0)
);

CREATE TABLE "tblwork" (
  "workid"            integer GENERATED BY DEFAULT AS IDENTITY,
  "PersonID"          integer NOT NULL,
  "TotalRequired"     integer NOT NULL,
  "Currency"          citext,
  "Typeofwork"        integer NOT NULL,
  "Notes"             citext,
  "AdditionDate"      timestamp DEFAULT LOCALTIMESTAMP,
  "KeyWordID1"        integer,
  "KeyWordID2"        integer,
  "KeywordID3"        integer,
  "StartDate"         date,
  "DebondDate"        date,
  "FPhotoDate"        date,
  "IPhotoDate"        date,
  "EstimatedDuration" smallint,
  "DrID"              integer NOT NULL,
  "KeywordID4"        integer,
  "NotesDate"         date,
  "KeywordID5"        integer,
  "Status"            smallint NOT NULL DEFAULT 1,
  "Discount"          integer,
  "DiscountDate"      date,
  "DiscountReason"    citext,
  CONSTRAINT "tblwork$PrimaryKey" PRIMARY KEY ("workid"),
  CONSTRAINT "CK_tblwork"        CHECK ("FPhotoDate" > "IPhotoDate"),
  CONSTRAINT "CK_tblwork_Cur"    CHECK ("Currency" IS NOT NULL OR "TotalRequired" IS NULL),
  CONSTRAINT "CK_tblwork_Deb"    CHECK ("FPhotoDate" >= "DebondDate"),
  CONSTRAINT "CK_tblwork_DebIPh" CHECK ("DebondDate" > "IPhotoDate")
);

CREATE TABLE "tblAlignerBatches" (
  "AlignerBatchID"            integer GENERATED BY DEFAULT AS IDENTITY,
  "AlignerSetID"              integer NOT NULL,
  "UpperAlignerCount"         integer NOT NULL,
  "LowerAlignerCount"         integer NOT NULL,
  "ManufactureDate"           date,
  "DeliveredToPatientDate"    date,
  "Notes"                     citext,
  "IsActive"                  boolean DEFAULT false,
  "BatchSequence"             integer NOT NULL,
  "UpperAlignerStartSequence" integer,
  "LowerAlignerStartSequence" integer,
  "UpperAlignerEndSequence"   integer GENERATED ALWAYS AS (
      CASE WHEN "UpperAlignerStartSequence" IS NULL THEN NULL
           ELSE ("UpperAlignerStartSequence" + "UpperAlignerCount") - 1 END) STORED,
  "LowerAlignerEndSequence"   integer GENERATED ALWAYS AS (
      CASE WHEN "LowerAlignerStartSequence" IS NULL THEN NULL
           ELSE ("LowerAlignerStartSequence" + "LowerAlignerCount") - 1 END) STORED,
  "Days"                      integer,
  "IsLast"                    boolean NOT NULL DEFAULT false,
  "CreationDate"              timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  "HasUpperTemplate"          boolean NOT NULL DEFAULT false,
  "HasLowerTemplate"          boolean NOT NULL DEFAULT false,
  "ValidityPeriod"            integer GENERATED ALWAYS AS (
      CASE WHEN "Days" IS NULL THEN NULL
           WHEN ("UpperAlignerCount" - CASE WHEN "HasUpperTemplate" THEN 1 ELSE 0 END)
              >= ("LowerAlignerCount" - CASE WHEN "HasLowerTemplate" THEN 1 ELSE 0 END)
             THEN ("UpperAlignerCount" - CASE WHEN "HasUpperTemplate" THEN 1 ELSE 0 END) * "Days"
             ELSE ("LowerAlignerCount" - CASE WHEN "HasLowerTemplate" THEN 1 ELSE 0 END) * "Days"
      END) STORED,
  "BatchExpiryDate"           date GENERATED ALWAYS AS (
      "DeliveredToPatientDate" + (
        CASE WHEN "Days" IS NULL THEN NULL
             WHEN ("UpperAlignerCount" - CASE WHEN "HasUpperTemplate" THEN 1 ELSE 0 END)
                >= ("LowerAlignerCount" - CASE WHEN "HasLowerTemplate" THEN 1 ELSE 0 END)
               THEN ("UpperAlignerCount" - CASE WHEN "HasUpperTemplate" THEN 1 ELSE 0 END) * "Days"
               ELSE ("LowerAlignerCount" - CASE WHEN "HasLowerTemplate" THEN 1 ELSE 0 END) * "Days"
        END)) STORED,
  CONSTRAINT "PK__tblAlign__1C222425A57BE68E" PRIMARY KEY ("AlignerBatchID"),
  CONSTRAINT "UQ_BatchSequence_AlignerSetID" UNIQUE ("AlignerSetID","BatchSequence"),
  CONSTRAINT "CK_AlignerBatches_Active_Requires_Delivery"
      CHECK ("IsActive" = false OR "DeliveredToPatientDate" IS NOT NULL)
);

CREATE TABLE "tblpatients" (
  "PersonID"         integer GENERATED BY DEFAULT AS IDENTITY,
  "patientID"        citext,
  "PatientName"      citext NOT NULL,
  "Phone"            citext,
  "FirstName"        citext,
  "LastName"         citext,
  "DateofBirth"      date,
  "Gender"           integer,
  "Phone2"           citext,
  "AddressID"        integer,
  "DateAdded"        timestamp DEFAULT LOCALTIMESTAMP,
  "ReferralSourceID" integer,
  "EstimatedCost"    integer,
  "Currency"         citext,
  "PatientTypeID"    integer,
  "Notes"            citext,
  "Email"            citext,
  "Language"         smallint DEFAULT 0,
  "TagID"            integer,
  "CountryCode"      citext,
  "WebCephPatientID" citext,
  "WebCephLink"      citext,
  "WebCephCreatedAt" timestamp,
  CONSTRAINT "tblpatients$PrimaryKey" PRIMARY KEY ("PersonID"),
  CONSTRAINT "SSMA_CC$tblpatients$Gender$validation_rule"
      CHECK ("Gender" IS NULL OR "Gender" = 1 OR "Gender" = 2),
  CONSTRAINT "SSMA_CC$tblpatients$patientID$disallow_zero_length"   CHECK ("patientID" <> ''),
  CONSTRAINT "SSMA_CC$tblpatients$PatientName$disallow_zero_length" CHECK ("PatientName" <> '')
);

CREATE TABLE "tblappointments" (
  "appointmentID"      integer GENERATED BY DEFAULT AS IDENTITY,
  "PersonID"           integer NOT NULL,
  "AppDetail"          citext,
  "WantNotify"         boolean DEFAULT true,
  "Notified"           boolean DEFAULT false,
  "SMSStatus"          citext,
  "Present"            time,
  "Seated"             time,
  "Dismissed"          time,
  "AppDate"            timestamp NOT NULL,
  "AppDay"             date GENERATED ALWAYS AS (("AppDate")::date) STORED,
  "AppCost"            citext,
  "SentWa"             boolean,
  "DeliveredWa"        citext,
  "WantWa"             boolean DEFAULT true,
  "WaMessageID"        citext,
  "sms_sid"            citext,
  "AppTime"            time GENERATED ALWAYS AS (("AppDate")::time) STORED,
  "DrID"               integer,
  "LastUpdated"        timestamp,
  "SentTimestamp"      timestamp,
  "DeliveredTimestamp" timestamp,
  "ReadTimestamp"      timestamp,
  CONSTRAINT "PK_tblappointments" PRIMARY KEY ("appointmentID")
);

CREATE TABLE "tblExpenses" (
  "ID"            integer GENERATED BY DEFAULT AS IDENTITY,
  "expenseDate"   date NOT NULL,
  "Amount"        integer NOT NULL,
  "Currency"      citext,
  "Note"          citext,
  "CategoryID"    integer,
  "SubcategoryID" integer,
  CONSTRAINT "PK_tblExpenses" PRIMARY KEY ("ID")
);

CREATE TABLE "tblvideos" (
  "ID"             integer GENERATED BY DEFAULT AS IDENTITY,
  "Description"    citext NOT NULL,
  "Category"       integer,
  "URL"            citext,
  "Details"        citext,
  "FileName"       citext,
  "VideoExtension" citext,
  CONSTRAINT "tblvideos$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tbloptions" (
  "OptionName"  citext NOT NULL,
  "OptionValue" citext,
  CONSTRAINT "tbloptions$PrimaryKey" PRIMARY KEY ("OptionName")
);

CREATE TABLE "tblnumbers" (
  "Mynumber" integer NOT NULL DEFAULT 0,
  CONSTRAINT "tblnumbers$PrimaryKey" PRIMARY KEY ("Mynumber")
);

CREATE TABLE "tblholidays" (
  "Holidaydate" date NOT NULL,
  "Description" citext,
  "ID"          integer GENERATED BY DEFAULT AS IDENTITY,
  "HolidayName" citext NOT NULL DEFAULT 'Holiday',
  CONSTRAINT "tblholidays$PrimaryKey" PRIMARY KEY ("Holidaydate")
);

CREATE TABLE "tbltimes" (
  "TimeID" integer GENERATED BY DEFAULT AS IDENTITY,
  "MyTime" time,
  CONSTRAINT "tbltimes$PrimaryKey" PRIMARY KEY ("TimeID")
);

CREATE TABLE "tblWires" (
  "Wire_ID" integer GENERATED BY DEFAULT AS IDENTITY,
  "Wire"    citext NOT NULL,
  CONSTRAINT "tblWires$PrimaryKey" PRIMARY KEY ("Wire_ID")
);

CREATE TABLE "AlignerDoctors" (
  "DrID"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DoctorName"  citext NOT NULL,
  "LogoPath"    citext,
  "DoctorEmail" citext
);

CREATE TABLE "DocumentTemplates" (
  "template_id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_name"      citext NOT NULL,
  "description"        citext,
  "document_type_id"   integer NOT NULL,
  "paper_width"        integer NOT NULL,
  "paper_height"       integer NOT NULL,
  "paper_orientation"  citext DEFAULT 'portrait',
  "paper_margin_top"   integer DEFAULT 10,
  "paper_margin_right" integer DEFAULT 10,
  "paper_margin_bottom" integer DEFAULT 10,
  "paper_margin_left"  integer DEFAULT 10,
  "background_color"   citext DEFAULT '#FFFFFF',
  "show_grid"          boolean DEFAULT false,
  "grid_size"          integer DEFAULT 10,
  "is_default"         boolean DEFAULT false,
  "is_active"          boolean DEFAULT true,
  "is_system"          boolean DEFAULT false,
  "template_version"   integer DEFAULT 1,
  "parent_template_id" integer,
  "created_by"         citext,
  "created_date"       timestamp DEFAULT LOCALTIMESTAMP,
  "modified_by"        citext,
  "modified_date"      timestamp,
  "last_used_date"     timestamp,
  "template_file_path" citext
);

CREATE TABLE "DocumentTypes" (
  "type_id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_code"             citext NOT NULL,
  "type_name"             citext NOT NULL,
  "description"           citext,
  "icon"                  citext,
  "default_paper_width"   integer DEFAULT 210,
  "default_paper_height"  integer DEFAULT 297,
  "default_orientation"   citext DEFAULT 'portrait',
  "is_active"             boolean DEFAULT true,
  "sort_order"            integer DEFAULT 0,
  CONSTRAINT "DocumentTypes_type_code_key" UNIQUE ("type_code")
);

CREATE TABLE "Patients" (
  "patID"        uuid NOT NULL PRIMARY KEY,
  "patName"      citext,
  "patFirstName" citext,
  "patLastName"  citext,
  "patPhone1"    citext,
  "patGender"    citext,
  "patBirthdate" timestamp,
  "patOtherID"   citext
);

CREATE TABLE "SyncQueue" (
  "QueueID"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TableName"   citext NOT NULL,
  "RecordID"    integer NOT NULL,
  "Operation"   citext NOT NULL,
  "JsonData"    citext,
  "CreatedAt"   timestamp DEFAULT LOCALTIMESTAMP,
  "Attempts"    integer DEFAULT 0,
  "LastAttempt" timestamp,
  "LastError"   citext,
  "Status"      citext DEFAULT 'Pending',
  CONSTRAINT "SyncQueue_Operation_check" CHECK ("Operation" IN ('DELETE','UPDATE','INSERT')),
  CONSTRAINT "SyncQueue_Status_check"    CHECK ("Status" IN ('Failed','Synced','Pending'))
);

CREATE TABLE "tbCities" (
  "ID"   integer GENERATED BY DEFAULT AS IDENTITY,
  "City" citext,
  CONSTRAINT "tbCities$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblAddress" (
  "ID"     integer GENERATED BY DEFAULT AS IDENTITY,
  "Zone"   citext,
  "CityID" integer,
  CONSTRAINT "tblAddress$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblAlerts" (
  "AlertID"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PersonID"     integer NOT NULL,
  "AlertTypeID"  integer NOT NULL,
  "AlertSeverity" integer NOT NULL,
  "AlertDetails" citext,
  "CreationDate" timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  "IsActive"     boolean NOT NULL DEFAULT true,
  CONSTRAINT "CHK_AlertSeverity" CHECK ("AlertSeverity" IN (1,2,3))
);

CREATE TABLE "tblAlertTypes" (
  "AlertTypeID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TypeName"    citext NOT NULL,
  CONSTRAINT "tblAlertTypes_TypeName_key" UNIQUE ("TypeName")
);

CREATE TABLE "tblAlignerActivityFlags" (
  "ActivityID"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AlignerSetID"        integer NOT NULL,
  "ActivityType"        citext NOT NULL,
  "ActivityDescription" citext NOT NULL,
  "CreatedAt"           timestamp DEFAULT LOCALTIMESTAMP,
  "IsRead"              boolean DEFAULT false,
  "ReadAt"              timestamp,
  "RelatedRecordID"     integer,
  CONSTRAINT "CK_ActivityType" CHECK ("ActivityType" IN ('DaysChanged','DoctorNote'))
);

CREATE TABLE "tblAlignerNotes" (
  "NoteID"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AlignerSetID" integer NOT NULL,
  "NoteType"     citext NOT NULL,
  "NoteText"     citext NOT NULL,
  "CreatedAt"    timestamp DEFAULT LOCALTIMESTAMP,
  "IsEdited"     boolean DEFAULT false,
  "EditedAt"     timestamp,
  "IsRead"       boolean NOT NULL DEFAULT true
);

CREATE TABLE "tblbends" (
  "Bend_ID" integer GENERATED BY DEFAULT AS IDENTITY,
  "Bend"    citext NOT NULL,
  CONSTRAINT "tblbends$Bends_ID" PRIMARY KEY ("Bend_ID")
);

CREATE TABLE "tblCalender" (
  "AppDate" timestamp NOT NULL,
  CONSTRAINT "IX_Calender" PRIMARY KEY ("AppDate")
);

CREATE TABLE "tblCarriedWires" (
  "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
  "PersonID"     integer NOT NULL,
  "WireBag"      citext NOT NULL,
  "WireSlot"     integer NOT NULL,
  "Wire_ID"      integer NOT NULL,
  "UpperLower"   citext NOT NULL,
  "AdditionDate" date NOT NULL,
  CONSTRAINT "PK_tblCarriedWires" PRIMARY KEY ("Id")
);

CREATE TABLE "tblDetail" (
  "ID"     integer GENERATED BY DEFAULT AS IDENTITY,
  "Detail" citext,
  CONSTRAINT "tblDetail$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblDiagnosis" (
  "ID"                       integer GENERATED BY DEFAULT AS IDENTITY,
  "DxDate"                   timestamp,
  "WorkID"                   integer NOT NULL,
  "Diagnosis"                citext NOT NULL,
  "TreatmentPlan"            citext NOT NULL,
  "ChiefComplain"            citext,
  "fAnteroPosterior"         citext,
  "fVertical"                citext,
  "fTransverse"              citext,
  "fLipCompetence"           citext,
  "fNasoLabialAngle"         citext,
  "fUpperIncisorShowRest"    citext,
  "fUpperIncisorShowSmile"   citext,
  "ITeethPresent"            citext,
  "IDentalHealth"            citext,
  "ILowerCrowding"           citext,
  "ILowerIncisorInclination" citext,
  "ICurveofSpee"             citext,
  "IUpperCrowding"           citext,
  "IUpperIncisorInclination" citext,
  "OIncisorRelation"         citext,
  "OOverjet"                 citext,
  "OOverbite"                citext,
  "OCenterlines"             citext,
  "OMolarRelation"           citext,
  "OCanineRelation"          citext,
  "OFunctionalOcclusion"     citext,
  "C_SNA"                    citext,
  "C_SNB"                    citext,
  "C_ANB"                    citext,
  "C_SNMx"                   citext,
  "C_Wits"                   citext,
  "C_FMA"                    citext,
  "C_MMA"                    citext,
  "C_UIMX"                   citext,
  "C_LIMd"                   citext,
  "C_UI_LI"                  citext,
  "C_LI_APo"                 citext,
  "C_Ulip_E"                 citext,
  "C_Llip_E"                 citext,
  "C_Naso_lip"               citext,
  "C_TAFH"                   citext,
  "C_UAFH"                   citext,
  "C_LAFH"                   citext,
  "C_PercentLAFH"            citext,
  "Appliance"                citext,
  CONSTRAINT "tblDiagnosis$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblElastics" (
  "Elastic_ID" integer GENERATED BY DEFAULT AS IDENTITY,
  "Elastic"    citext NOT NULL,
  CONSTRAINT "tblElastics$PrimaryKey" PRIMARY KEY ("Elastic_ID")
);

CREATE TABLE "tblEmployees" (
  "ID"               integer GENERATED BY DEFAULT AS IDENTITY,
  "employeeName"     citext NOT NULL,
  "Position"         integer,
  "Email"            citext,
  "Phone"            citext,
  "Percentage"       boolean NOT NULL DEFAULT false,
  "receiveEmail"     boolean NOT NULL DEFAULT false,
  "getAppointments"  boolean NOT NULL DEFAULT false,
  "SortOrder"        integer NOT NULL DEFAULT 999,
  "AppointmentColor" citext,
  CONSTRAINT "PK__tblEmplo__3214EC2785CA47DB" PRIMARY KEY ("ID")
);

CREATE TABLE "tblEndo" (
  "ID"            integer GENERATED BY DEFAULT AS IDENTITY,
  "DetailID"      integer,
  "Canal"         citext,
  "RefrencePoint" citext,
  "WorkingLength" numeric(3,1),
  "Curvature"     citext,
  "Note"          citext,
  CONSTRAINT "PK_tblEndo" PRIMARY KEY ("ID")
);

CREATE TABLE "tblEstimatedCostPresets" (
  "PresetID"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Amount"       numeric(18,2) NOT NULL,
  "Currency"     citext NOT NULL,
  "DisplayOrder" integer DEFAULT 0
);

CREATE TABLE "tblExpenseCategories" (
  "CategoryID"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CategoryName" citext NOT NULL
);

CREATE TABLE "tblExpenseSubcategories" (
  "SubcategoryID"   integer GENERATED BY DEFAULT AS IDENTITY,
  "SubcategoryName" citext NOT NULL,
  "CategoryID"      integer NOT NULL,
  CONSTRAINT "PK__tblExpen__9C4E707D6C548634" PRIMARY KEY ("SubcategoryID"),
  CONSTRAINT "UQ_Category_Subcategory"       UNIQUE ("SubcategoryID","CategoryID"),
  CONSTRAINT "UQ_ExpenseSubcat_Category_Name" UNIQUE ("CategoryID","SubcategoryName")
);

CREATE TABLE "tblGender" (
  "Gender_ID" integer NOT NULL,
  "Gender"    citext NOT NULL,
  CONSTRAINT "tblGender$PrimaryKey1" PRIMARY KEY ("Gender_ID")
);

CREATE TABLE "tblImageTypes" (
  "ImageTypeCode" char(2) NOT NULL,
  "Description"   citext,
  "DolphinItypID" uuid,
  CONSTRAINT "PK_tblImageTypes" PRIMARY KEY ("ImageTypeCode")
);

CREATE TABLE "tblImplant" (
  "ID"              integer GENERATED BY DEFAULT AS IDENTITY,
  "WorkID"          integer NOT NULL,
  "Tooth"           citext,
  "ImplantLength"   numeric(3,1),
  "ImplantDiameter" numeric(3,1),
  "ImplantCompany"  citext,
  "Note"            citext,
  CONSTRAINT "PK_tblImplant" PRIMARY KEY ("ID")
);

CREATE TABLE "tblImplantManufacturer" (
  "ID"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ManufacturerName" citext NOT NULL
);

CREATE TABLE "tblKeyWord" (
  "ID"      integer GENERATED BY DEFAULT AS IDENTITY,
  "KeyWord" citext,
  CONSTRAINT "tblKeyWord$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblMessageStatusHistory" (
  "StatusHistoryID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AppointmentID"   integer NOT NULL,
  "WaMessageID"     citext NOT NULL,
  "StatusCode"      integer NOT NULL,
  "StatusText"      citext NOT NULL,
  "Timestamp"       timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE TABLE "tblOldOPG" (
  "ID"         integer NOT NULL,
  "last_name"  citext NOT NULL,
  "first_name" citext NOT NULL,
  "sex"        citext NOT NULL,
  "birth_date" timestamp,
  "directory"  citext NOT NULL,
  CONSTRAINT "PK_tblFiles" PRIMARY KEY ("ID")
);

CREATE TABLE "tblPatientPortalAuth" (
  "PersonID"       integer NOT NULL,
  "PinHash"        citext NOT NULL,
  "Enabled"        boolean NOT NULL DEFAULT true,
  "FailedAttempts" integer NOT NULL DEFAULT 0,
  "LockedUntil"    timestamp,
  "LastLoginAt"    timestamp,
  "CreatedAt"      timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  "UpdatedAt"      timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  CONSTRAINT "tblPatientPortalAuth_pkey" PRIMARY KEY ("PersonID")
);

CREATE TABLE "tblPatientType" (
  "ID"          integer GENERATED BY DEFAULT AS IDENTITY,
  "PatientType" citext,
  CONSTRAINT "PK_tblPatientType" PRIMARY KEY ("ID")
);

CREATE TABLE "tblPositions" (
  "ID"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PositionName" citext,
  CONSTRAINT "tblPositions_PositionName_check"
      CHECK ("PositionName" IN ('Worker','Receptionist','Assistant','Doctor'))
);

CREATE TABLE "tblPrivatePhotos" (
  "PersonID"      integer NOT NULL,
  "TimepointCode" citext NOT NULL,
  "ImageName"     citext NOT NULL,
  "MarkedBy"      integer,
  "MarkedAt"      timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  CONSTRAINT "PK_PrivatePhotos" PRIMARY KEY ("PersonID","TimepointCode","ImageName")
);

CREATE TABLE "tblReferrals" (
  "ID"       integer GENERATED BY DEFAULT AS IDENTITY,
  "Referral" citext,
  CONSTRAINT "tblReferrals$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblscrews" (
  "ID"            integer GENERATED BY DEFAULT AS IDENTITY,
  "WorkID"        integer DEFAULT 0,
  "PersonID"      integer NOT NULL DEFAULT 0,
  "PlacementDate" timestamp,
  "Position"      citext,
  "State"         citext,
  CONSTRAINT "tblscrews$PrimaryKey" PRIMARY KEY ("ID")
);

CREATE TABLE "tblsms" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY,
  "date"         date NOT NULL,
  "smssent"      boolean NOT NULL DEFAULT false,
  "SMSID"        citext,
  "emailsent"    boolean NOT NULL DEFAULT false,
  "ExchangeRate" integer,
  CONSTRAINT "tblsms$PrimaryKey" PRIMARY KEY ("id"),
  CONSTRAINT "UQ_tblsms_date" UNIQUE ("date")
);

CREATE TABLE "tblStandCategories" (
  "CategoryID"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CategoryName" citext NOT NULL,
  "IsActive"     boolean NOT NULL DEFAULT true,
  CONSTRAINT "tblStandCategories_CategoryName_key" UNIQUE ("CategoryName")
);

CREATE TABLE "tblStandItems" (
  "ItemID"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ItemName"     citext NOT NULL,
  "SKU"          citext,
  "Barcode"      citext,
  "CategoryID"   integer,
  "CostPrice"    integer NOT NULL,
  "SellPrice"    integer NOT NULL,
  "CurrentStock" integer NOT NULL DEFAULT 0,
  "ReorderLevel" integer NOT NULL DEFAULT 5,
  "ExpiryDate"   date,
  "Unit"         citext,
  "Notes"        citext,
  "IsActive"     boolean NOT NULL DEFAULT true,
  "DateAdded"    timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  "ModifiedDate" timestamp,
  "CreatedBy"    integer,
  CONSTRAINT "CK_StandItems_CostPrice"    CHECK ("CostPrice" >= 0),
  CONSTRAINT "CK_StandItems_CurrentStock" CHECK ("CurrentStock" >= 0),
  CONSTRAINT "CK_StandItems_ReorderLevel" CHECK ("ReorderLevel" >= 0),
  CONSTRAINT "CK_StandItems_SellPrice"    CHECK ("SellPrice" >= 0)
);

CREATE TABLE "tblStandSaleItems" (
  "SaleItemID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SaleID"     integer NOT NULL,
  "ItemID"     integer NOT NULL,
  "Quantity"   integer NOT NULL,
  "UnitPrice"  integer NOT NULL,
  "UnitCost"   integer NOT NULL,
  "LineTotal"  integer NOT NULL,
  CONSTRAINT "CK_StandSaleItems_Quantity" CHECK ("Quantity" > 0)
);

CREATE TABLE "tblStandSales" (
  "SaleID"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SaleDate"      timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  "TotalAmount"   integer NOT NULL,
  "TotalCost"     integer NOT NULL,
  "TotalProfit"   integer NOT NULL,
  "AmountPaid"    integer NOT NULL,
  "Change"        integer NOT NULL DEFAULT 0,
  "PaymentMethod" citext NOT NULL DEFAULT 'cash',
  "CustomerNote"  citext,
  "PersonID"      integer,
  "CashierID"     integer,
  "VoidedDate"    timestamp,
  "VoidedBy"      integer,
  "VoidReason"    citext
);

CREATE TABLE "tblStandStockMovements" (
  "MovementID"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ItemID"        integer NOT NULL,
  "MovementType"  citext NOT NULL,
  "Quantity"      integer NOT NULL,
  "UnitCost"      integer,
  "TotalCost"     integer,
  "RelatedSaleID" integer,
  "Reason"        citext,
  "MovementDate"  timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  "PerformedBy"   integer
);

CREATE TABLE "tblTagOptions" (
  "ID"  integer GENERATED BY DEFAULT AS IDENTITY,
  "Tag" citext NOT NULL,
  CONSTRAINT "PK_tblTagOptions" PRIMARY KEY ("ID")
);

CREATE TABLE "tblTimePointImages" (
  "TimePointImageID" integer GENERATED BY DEFAULT AS IDENTITY,
  "TimePointID"      integer NOT NULL,
  "PersonID"         integer NOT NULL,
  "ImageType"        char(2),
  "ImageFile"        citext,
  "ImageDate"        date,
  "Title"            citext,
  "DolphinTpiID"     uuid,
  CONSTRAINT "PK_tblTimePointImages" PRIMARY KEY ("TimePointImageID"),
  CONSTRAINT "UQ_tblTimePointImages_TP_Type" UNIQUE ("TimePointID","ImageType")
);

CREATE TABLE "tblTimePoints" (
  "TimePointID"   integer GENERATED BY DEFAULT AS IDENTITY,
  "PersonID"      integer NOT NULL,
  "tpCode"        integer NOT NULL,
  "tpDescription" citext,
  "tpDateTime"    date,
  "CreatedDate"   timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  "DolphinTpID"   uuid,
  "DolphinPatID"  uuid,
  CONSTRAINT "PK_tblTimePoints" PRIMARY KEY ("TimePointID"),
  CONSTRAINT "UX_tblTimePoints_Person_tpCode" UNIQUE ("PersonID","tpCode")
);

CREATE TABLE "tblToothNumber" (
  "ID"          integer GENERATED BY DEFAULT AS IDENTITY,
  "ToothCode"   citext NOT NULL,
  "ToothName"   citext NOT NULL,
  "Quadrant"    citext NOT NULL,
  "ToothNumber" citext NOT NULL,
  "IsPermanent" boolean NOT NULL DEFAULT true,
  "SortOrder"   integer NOT NULL,
  CONSTRAINT "tblToothNumber_pkey" PRIMARY KEY ("ID"),
  CONSTRAINT "tblToothNumber_ToothCode_key" UNIQUE ("ToothCode")
);

CREATE TABLE "tblUsers" (
  "UserID"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Username"     citext NOT NULL,
  "PasswordHash" citext NOT NULL,
  "FullName"     citext,
  "Role"         citext DEFAULT 'user',
  "IsActive"     boolean DEFAULT true,
  "LastLogin"    timestamp,
  "CreatedAt"    timestamp DEFAULT LOCALTIMESTAMP,
  "CreatedBy"    citext,
  CONSTRAINT "tblUsers_Username_key" UNIQUE ("Username")
);

CREATE TABLE "tblVidCat" (
  "VidCatID" integer GENERATED BY DEFAULT AS IDENTITY,
  "Category" citext,
  CONSTRAINT "PK_tblVidCat" PRIMARY KEY ("VidCatID")
);

CREATE TABLE "tblWaiting" (
  "ID"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PersonID"      integer NOT NULL,
  "Creation_Date" date NOT NULL,
  "TypeID"        integer
);

CREATE TABLE "tblWaitReason" (
  "ID"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "WaitType" citext
);

CREATE TABLE "tblWorkItems" (
  "ID"                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "WorkID"                integer NOT NULL,
  "FillingType"           citext,
  "FillingDepth"          citext,
  "CanalsNo"              integer,
  "ItemCost"              integer,
  "StartDate"             date,
  "CompletedDate"         date,
  "Note"                  citext,
  "WorkingLength"         citext,
  "ImplantLength"         numeric(5,2),
  "ImplantDiameter"       numeric(5,2),
  "Material"              citext,
  "LabName"               citext,
  "ImplantManufacturerID" integer
);

CREATE TABLE "tblWorkItemTeeth" (
  "ID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "WorkItemID" integer NOT NULL,
  "ToothID"    integer NOT NULL,
  CONSTRAINT "UQ_WorkItemTeeth" UNIQUE ("WorkItemID","ToothID")
);

CREATE TABLE "tblWorkStatus" (
  "StatusID"   smallint NOT NULL,
  "StatusName" citext NOT NULL,
  CONSTRAINT "tblWorkStatus_pkey" PRIMARY KEY ("StatusID")
);

CREATE TABLE "tblWorkType" (
  "ID"       integer GENERATED BY DEFAULT AS IDENTITY,
  "WorkType" citext NOT NULL,
  CONSTRAINT "PK_tblWorkType" PRIMARY KEY ("ID")
);

-- ========================================================================================
-- FOREIGN KEYS (added after all tables so creation order is irrelevant)
-- ========================================================================================

ALTER TABLE "DocumentTemplates" ADD CONSTRAINT "FK_DocumentTemplates_Parent"
  FOREIGN KEY ("parent_template_id") REFERENCES "DocumentTemplates" ("template_id");
ALTER TABLE "DocumentTemplates" ADD CONSTRAINT "FK_DocumentTemplates_Type"
  FOREIGN KEY ("document_type_id") REFERENCES "DocumentTypes" ("type_id");
ALTER TABLE "tblAddress" ADD CONSTRAINT "tblAddress$tbCitiestblAddress"
  FOREIGN KEY ("CityID") REFERENCES "tbCities" ("ID") ON UPDATE CASCADE;
ALTER TABLE "tblAlerts" ADD CONSTRAINT "FK_Alerts_AlertType"
  FOREIGN KEY ("AlertTypeID") REFERENCES "tblAlertTypes" ("AlertTypeID");
ALTER TABLE "tblAlerts" ADD CONSTRAINT "FK_Alerts_Patient"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID") ON DELETE CASCADE;
ALTER TABLE "tblAlignerActivityFlags" ADD CONSTRAINT "FK_ActivityFlags_AlignerSet"
  FOREIGN KEY ("AlignerSetID") REFERENCES "tblAlignerSets" ("AlignerSetID") ON DELETE CASCADE;
ALTER TABLE "tblAlignerBatches" ADD CONSTRAINT "FK_tblAlignerBatches_AlignerSet"
  FOREIGN KEY ("AlignerSetID") REFERENCES "tblAlignerSets" ("AlignerSetID") ON DELETE CASCADE;
ALTER TABLE "tblAlignerNotes" ADD CONSTRAINT "FK_tblAlignerNotes_AlignerSet"
  FOREIGN KEY ("AlignerSetID") REFERENCES "tblAlignerSets" ("AlignerSetID") ON DELETE CASCADE;
ALTER TABLE "tblAlignerSets" ADD CONSTRAINT "FK_tblAlignerSets_AlignerDoctors"
  FOREIGN KEY ("AlignerDrID") REFERENCES "AlignerDoctors" ("DrID");
ALTER TABLE "tblappointments" ADD CONSTRAINT "FK_tblappointments_tblDoctors"
  FOREIGN KEY ("DrID") REFERENCES "tblEmployees" ("ID");
ALTER TABLE "tblappointments" ADD CONSTRAINT "tblappointments$tblpatientstblappointments"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tblCarriedWires" ADD CONSTRAINT "FK_tblCarriedWires_tblpatients"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID");
ALTER TABLE "tblCarriedWires" ADD CONSTRAINT "FK_tblCarriedWires_tblWires"
  FOREIGN KEY ("Wire_ID") REFERENCES "tblWires" ("Wire_ID");
ALTER TABLE "tblDiagnosis" ADD CONSTRAINT "tblDiagnosis$tblworktblDiagnosis"
  FOREIGN KEY ("WorkID") REFERENCES "tblwork" ("workid") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tblEmployees" ADD CONSTRAINT "FK__tblEmploy__Posit__5B196B42"
  FOREIGN KEY ("Position") REFERENCES "tblPositions" ("ID");
ALTER TABLE "tblExpenses" ADD CONSTRAINT "FK_tblExpenses_tblExpenseCategories"
  FOREIGN KEY ("CategoryID") REFERENCES "tblExpenseCategories" ("CategoryID");
ALTER TABLE "tblExpenses" ADD CONSTRAINT "FK_tblExpenses_tblExpenseSubcategories"
  FOREIGN KEY ("SubcategoryID") REFERENCES "tblExpenseSubcategories" ("SubcategoryID");
ALTER TABLE "tblExpenseSubcategories" ADD CONSTRAINT "FK_subcategory_category"
  FOREIGN KEY ("CategoryID") REFERENCES "tblExpenseCategories" ("CategoryID");
ALTER TABLE "tblImplant" ADD CONSTRAINT "FK_tblImplant_tblwork"
  FOREIGN KEY ("WorkID") REFERENCES "tblwork" ("workid") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tblInvoice" ADD CONSTRAINT "FK_Invoice_AlignerSet"
  FOREIGN KEY ("AlignerSetID") REFERENCES "tblAlignerSets" ("AlignerSetID");
ALTER TABLE "tblInvoice" ADD CONSTRAINT "tblInvoice$tblworktblInvoice"
  FOREIGN KEY ("workid") REFERENCES "tblwork" ("workid") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tblMessageStatusHistory" ADD CONSTRAINT "FK__tblMessag__Appoi__308412F8"
  FOREIGN KEY ("AppointmentID") REFERENCES "tblappointments" ("appointmentID") ON DELETE CASCADE;
ALTER TABLE "tblPatientPortalAuth" ADD CONSTRAINT "FK_PortalAuth_Patient"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID");
ALTER TABLE "tblpatients" ADD CONSTRAINT "FK_tblpatients_tblpatienttype"
  FOREIGN KEY ("PatientTypeID") REFERENCES "tblPatientType" ("ID");
ALTER TABLE "tblpatients" ADD CONSTRAINT "FK_tblpatients_tblReferrals"
  FOREIGN KEY ("ReferralSourceID") REFERENCES "tblReferrals" ("ID");
ALTER TABLE "tblpatients" ADD CONSTRAINT "FK_tblpatients_tblTagOptions"
  FOREIGN KEY ("TagID") REFERENCES "tblTagOptions" ("ID");
ALTER TABLE "tblpatients" ADD CONSTRAINT "tblpatients$tblAddresstblpatients"
  FOREIGN KEY ("AddressID") REFERENCES "tblAddress" ("ID") ON UPDATE CASCADE;
ALTER TABLE "tblpatients" ADD CONSTRAINT "tblpatients$tblGendertblpatients"
  FOREIGN KEY ("Gender") REFERENCES "tblGender" ("Gender_ID");
ALTER TABLE "tblPrivatePhotos" ADD CONSTRAINT "FK_PrivatePhotos_Patient"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID");
ALTER TABLE "tblscrews" ADD CONSTRAINT "tblscrews$tblpatientstblscrews"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tblscrews" ADD CONSTRAINT "tblscrews$tblworktblscrews"
  FOREIGN KEY ("WorkID") REFERENCES "tblwork" ("workid");
ALTER TABLE "tblStandItems" ADD CONSTRAINT "FK_tblStandItems_Category"
  FOREIGN KEY ("CategoryID") REFERENCES "tblStandCategories" ("CategoryID");
ALTER TABLE "tblStandSaleItems" ADD CONSTRAINT "FK_tblStandSaleItems_Item"
  FOREIGN KEY ("ItemID") REFERENCES "tblStandItems" ("ItemID");
ALTER TABLE "tblStandSaleItems" ADD CONSTRAINT "FK_tblStandSaleItems_Sale"
  FOREIGN KEY ("SaleID") REFERENCES "tblStandSales" ("SaleID") ON DELETE CASCADE;
ALTER TABLE "tblStandSales" ADD CONSTRAINT "FK_tblStandSales_Cashier"
  FOREIGN KEY ("CashierID") REFERENCES "tblUsers" ("UserID");
ALTER TABLE "tblStandSales" ADD CONSTRAINT "FK_tblStandSales_Person"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID");
ALTER TABLE "tblStandSales" ADD CONSTRAINT "FK_tblStandSales_VoidedBy"
  FOREIGN KEY ("VoidedBy") REFERENCES "tblUsers" ("UserID");
ALTER TABLE "tblStandStockMovements" ADD CONSTRAINT "FK_tblStandStockMovements_Item"
  FOREIGN KEY ("ItemID") REFERENCES "tblStandItems" ("ItemID");
ALTER TABLE "tblStandStockMovements" ADD CONSTRAINT "FK_tblStandStockMovements_PerformedBy"
  FOREIGN KEY ("PerformedBy") REFERENCES "tblUsers" ("UserID");
ALTER TABLE "tblStandStockMovements" ADD CONSTRAINT "FK_tblStandStockMovements_RelatedSale"
  FOREIGN KEY ("RelatedSaleID") REFERENCES "tblStandSales" ("SaleID");
ALTER TABLE "tblTimePointImages" ADD CONSTRAINT "FK_tblTPImages_TP"
  FOREIGN KEY ("TimePointID") REFERENCES "tblTimePoints" ("TimePointID") ON DELETE CASCADE;
ALTER TABLE "tblvideos" ADD CONSTRAINT "FK_tblvideos_tblVidCat"
  FOREIGN KEY ("Category") REFERENCES "tblVidCat" ("VidCatID");
ALTER TABLE "tblvisits" ADD CONSTRAINT "FK_tblvisits_tblWires"
  FOREIGN KEY ("LowerWireID") REFERENCES "tblWires" ("Wire_ID");
ALTER TABLE "tblvisits" ADD CONSTRAINT "tblvisits$tblWirestblvisits"
  FOREIGN KEY ("UpperWireID") REFERENCES "tblWires" ("Wire_ID");
ALTER TABLE "tblvisits" ADD CONSTRAINT "tblvisits$tblworktblvisits"
  FOREIGN KEY ("WorkID") REFERENCES "tblwork" ("workid") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tblWaiting" ADD CONSTRAINT "FK_tblWaiting_tblpatients"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID");
ALTER TABLE "tblWaiting" ADD CONSTRAINT "FK_tblWaiting_tblWaitReason"
  FOREIGN KEY ("TypeID") REFERENCES "tblWaitReason" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblEmployees"
  FOREIGN KEY ("DrID") REFERENCES "tblEmployees" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblKeyWord"
  FOREIGN KEY ("KeyWordID1") REFERENCES "tblKeyWord" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblKeyWord2"
  FOREIGN KEY ("KeyWordID2") REFERENCES "tblKeyWord" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblKeyWord3"
  FOREIGN KEY ("KeywordID3") REFERENCES "tblKeyWord" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblKeyWord4"
  FOREIGN KEY ("KeywordID4") REFERENCES "tblKeyWord" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblKeyWord5"
  FOREIGN KEY ("KeywordID5") REFERENCES "tblKeyWord" ("ID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_tblwork_tblpatients"
  FOREIGN KEY ("PersonID") REFERENCES "tblpatients" ("PersonID");
ALTER TABLE "tblwork" ADD CONSTRAINT "FK_Work_Status"
  FOREIGN KEY ("Status") REFERENCES "tblWorkStatus" ("StatusID");
ALTER TABLE "tblWorkItems" ADD CONSTRAINT "FK_WorkItems_Work"
  FOREIGN KEY ("WorkID") REFERENCES "tblwork" ("workid");
ALTER TABLE "tblWorkItemTeeth" ADD CONSTRAINT "FK_WorkItemTeeth_Tooth"
  FOREIGN KEY ("ToothID") REFERENCES "tblToothNumber" ("ID");
ALTER TABLE "tblWorkItemTeeth" ADD CONSTRAINT "FK_WorkItemTeeth_WorkItem"
  FOREIGN KEY ("WorkItemID") REFERENCES "tblWorkItems" ("ID") ON DELETE CASCADE;

-- ========================================================================================
-- INDEXES
-- Partial / filtered unique indexes (correctness-critical) + the source's performance indexes.
-- Indexes that merely duplicate a PK or an identical sibling index were intentionally skipped.
-- ========================================================================================

-- Unique (filtered) — enforce business rules from the source schema.
CREATE UNIQUE INDEX "IX_tblAlignerBatches_OneActivePerSet" ON "tblAlignerBatches" ("AlignerSetID") WHERE ("IsActive");
CREATE UNIQUE INDEX "IX_tblAlignerSets_OneActivePerWork"   ON "tblAlignerSets"   ("WorkID")       WHERE ("IsActive");
CREATE UNIQUE INDEX "UX_StandItems_Barcode"                ON "tblStandItems"    ("Barcode")      WHERE ("Barcode" IS NOT NULL);
CREATE UNIQUE INDEX "UX_StandItems_SKU"                    ON "tblStandItems"    ("SKU")          WHERE ("SKU" IS NOT NULL);
CREATE UNIQUE INDEX "UX_tblTimePoints_DolphinTpID"         ON "tblTimePoints"    ("DolphinTpID")  WHERE ("DolphinTpID" IS NOT NULL);
CREATE UNIQUE INDEX "Photo_index"                          ON "tblvisits"        ("WorkID","IPhoto") WHERE ("IPhoto");
CREATE UNIQUE INDEX "PhotoF_index"                         ON "tblvisits"        ("WorkID","FPhoto") WHERE ("FPhoto");
CREATE UNIQUE INDEX "UNQ_tblWork_Active"                   ON "tblwork"          ("PersonID")     WHERE ("Status" = 1);

-- Unique (non-filtered, with INCLUDE / on generated columns) — expressed as unique indexes.
CREATE UNIQUE INDEX "IX_SingleApp"   ON "tblappointments" ("PersonID","AppDay");
CREATE UNIQUE INDEX "IX_PID_All"     ON "tblappointments" ("PersonID","AppDate") INCLUDE ("appointmentID","AppDetail");
CREATE UNIQUE INDEX "Ind_UniqueDate" ON "tblInvoice" ("Dateofpayment","workid") INCLUDE ("Amountpaid");
CREATE UNIQUE INDEX "IX_Statistics"  ON "tblInvoice" ("workid","Dateofpayment") INCLUDE ("Amountpaid");
CREATE UNIQUE INDEX "IX_Name_ID"     ON "tblpatients" ("PatientName") INCLUDE ("PersonID");
CREATE UNIQUE INDEX "tblDiagnosis$CompIndex" ON "tblDiagnosis" ("ID","WorkID");
CREATE UNIQUE INDEX "IX_Currency"    ON "tblwork" ("Currency","workid") NULLS NOT DISTINCT;
CREATE UNIQUE INDEX "tblvisits$UniqueVisit" ON "tblvisits"
  ("ID","BracketChange","WireBending","OPG","Others","NextVisit","Elastics","UpperWireID",
   "LowerWireID","PPhoto","IPhoto","FPhoto","ApplianceRemoved","OperatorID","WorkID","VisitDate")
  NULLS NOT DISTINCT;

-- Non-unique performance indexes (carried over from the source schema).
CREATE INDEX "IX_DocumentTemplates_Default" ON "DocumentTemplates" ("is_default","document_type_id");
CREATE INDEX "IX_DocumentTemplates_Type"    ON "DocumentTemplates" ("document_type_id","is_active");
CREATE INDEX "idx_sync_status"              ON "SyncQueue" ("Status","CreatedAt");
CREATE INDEX "idx_sync_table"               ON "SyncQueue" ("TableName","RecordID");
CREATE INDEX "tblAddress$CityID"            ON "tblAddress" ("CityID");
CREATE INDEX "idx_activity_created"         ON "tblAlignerActivityFlags" ("CreatedAt" DESC);
CREATE INDEX "idx_activity_set_unread"      ON "tblAlignerActivityFlags" ("AlignerSetID","IsRead");
CREATE INDEX "IX_tblAlignerBatches_AlignerSetID" ON "tblAlignerBatches" ("AlignerSetID")
  INCLUDE ("UpperAlignerCount","LowerAlignerCount","ManufactureDate","AlignerBatchID");
CREATE INDEX "IX_tblAlignerBatches_IsLast"  ON "tblAlignerBatches" ("AlignerSetID","IsLast") WHERE ("IsLast");
CREATE INDEX "IX_tblAlignerBatches_SetID_MfgDate_BatchID" ON "tblAlignerBatches"
  ("AlignerSetID","ManufactureDate","AlignerBatchID")
  INCLUDE ("UpperAlignerCount","LowerAlignerCount","UpperAlignerStartSequence","LowerAlignerStartSequence");
CREATE INDEX "IX_AlignerNotes_CreatedAt"    ON "tblAlignerNotes" ("CreatedAt" DESC);
CREATE INDEX "IX_AlignerNotes_SetID"        ON "tblAlignerNotes" ("AlignerSetID");
CREATE INDEX "IX_Appdate_PID"               ON "tblappointments" ("AppDate")
  INCLUDE ("PersonID","appointmentID","AppDetail","AppCost");
CREATE INDEX "IX_AppDay"                    ON "tblappointments" ("AppDay")
  INCLUDE ("appointmentID","Present","PersonID","AppDetail","Seated","Dismissed","AppCost","AppDate","WantNotify","Notified","SMSStatus");
CREATE INDEX "IX_tblappointments_AppDate_Optimized" ON "tblappointments" ("AppDate")
  INCLUDE ("appointmentID","AppDetail","DrID","PersonID","Present","Seated","Dismissed");
CREATE INDEX "IX_tblappointments_DeliveryStatus" ON "tblappointments" ("AppDay","SentWa","DeliveredWa");
CREATE INDEX "IX_tblappointments_MessageID" ON "tblappointments" ("WaMessageID");
CREATE INDEX "tblDiagnosis$tblworktblDiagnosis" ON "tblDiagnosis" ("WorkID");
CREATE INDEX "IX_EstimatedCostPresets_Currency" ON "tblEstimatedCostPresets" ("Currency","DisplayOrder");
CREATE INDEX "tblGender$tblGenderGender"    ON "tblGender" ("Gender");
CREATE INDEX "IX_WID_Date_Sum"              ON "tblInvoice" ("workid") INCLUDE ("Amountpaid","Dateofpayment");
CREATE INDEX "tblKeyWord$KeyWord"           ON "tblKeyWord" ("KeyWord");
CREATE INDEX "IX_Patients_Phone"            ON "tblpatients" ("PersonID")
  INCLUDE ("PatientName","Phone","patientID","PatientTypeID","EstimatedCost","Currency");
CREATE INDEX "tblpatients$tblAddresstblpatients" ON "tblpatients" ("AddressID");
CREATE INDEX "tblpatients$tblGendertblpatients"  ON "tblpatients" ("Gender");
CREATE INDEX "IX_PrivatePhotos_Patient_TP"  ON "tblPrivatePhotos" ("PersonID","TimepointCode");
CREATE INDEX "tblscrews$PersonID"           ON "tblscrews" ("PersonID");
CREATE INDEX "tblscrews$WorkID"             ON "tblscrews" ("WorkID");
CREATE INDEX "tblsms$SMSID"                 ON "tblsms" ("SMSID");
CREATE INDEX "IX_StandItems_Active_Expiry"  ON "tblStandItems" ("IsActive","ExpiryDate");
CREATE INDEX "IX_StandItems_CategoryID"     ON "tblStandItems" ("CategoryID");
CREATE INDEX "IX_StandSaleItems_ItemID"     ON "tblStandSaleItems" ("ItemID");
CREATE INDEX "IX_StandSaleItems_SaleID"     ON "tblStandSaleItems" ("SaleID");
CREATE INDEX "IX_StandSales_CashierID"      ON "tblStandSales" ("CashierID") WHERE ("CashierID" IS NOT NULL);
CREATE INDEX "IX_StandSales_PersonID"       ON "tblStandSales" ("PersonID")  WHERE ("PersonID" IS NOT NULL);
CREATE INDEX "IX_StandSales_SaleDate"       ON "tblStandSales" ("SaleDate");
CREATE INDEX "IX_StandStockMovements_ItemID"       ON "tblStandStockMovements" ("ItemID");
CREATE INDEX "IX_StandStockMovements_MovementDate" ON "tblStandStockMovements" ("MovementDate");
CREATE INDEX "IX_StandStockMovements_MovementType" ON "tblStandStockMovements" ("MovementType");
CREATE INDEX "IX_tblTPImages_Person"        ON "tblTimePointImages" ("PersonID");
CREATE INDEX "IX_tblTPImages_TP"            ON "tblTimePointImages" ("TimePointID");
CREATE INDEX "IX_tblTimePoints_Person"      ON "tblTimePoints" ("PersonID");
CREATE INDEX "IDX_Users_IsActive"           ON "tblUsers" ("IsActive");
CREATE INDEX "tblvisits$LowerWireID"        ON "tblvisits" ("LowerWireID");
CREATE INDEX "tblvisits$UpperWireID"        ON "tblvisits" ("UpperWireID");
CREATE INDEX "tblvisits$WorkID"             ON "tblvisits" ("VisitDate","WorkID");
CREATE INDEX "IX_tblwork_Status"            ON "tblwork" ("Status");
CREATE INDEX "tblwork$KeyWordID1"           ON "tblwork" ("KeyWordID1");
CREATE INDEX "tblwork$KeyWordID2"           ON "tblwork" ("KeyWordID2");
CREATE INDEX "tblwork$KeywordID3"           ON "tblwork" ("KeywordID3");
CREATE INDEX "IX_WorkItems_WorkID"          ON "tblWorkItems" ("WorkID");
CREATE INDEX "IX_WorkItemTeeth_ToothID"     ON "tblWorkItemTeeth" ("ToothID");
CREATE INDEX "IX_WorkItemTeeth_WorkItemID"  ON "tblWorkItemTeeth" ("WorkItemID");

-- Down Migration

DROP TABLE IF EXISTS
  "tblWorkItemTeeth", "tblWorkItems", "tblWorkType", "tblWorkStatus", "tblWaitReason", "tblWaiting",
  "tblVidCat", "tblUsers", "tblToothNumber", "tblTimePointImages", "tblTimePoints", "tblTagOptions",
  "tblStandStockMovements", "tblStandSales", "tblStandSaleItems", "tblStandItems", "tblStandCategories",
  "tblsms", "tblscrews", "tblReferrals", "tblPrivatePhotos", "tblPositions", "tblPatientType",
  "tblPatientPortalAuth", "tblOldOPG", "tblMessageStatusHistory", "tblKeyWord", "tblImplantManufacturer",
  "tblImplant", "tblImageTypes", "tblGender", "tblExpenseSubcategories", "tblExpenseCategories",
  "tblEstimatedCostPresets", "tblEndo", "tblEmployees", "tblElastics", "tblDiagnosis", "tblDetail",
  "tblCarriedWires", "tblCalender", "tblbends", "tblAlignerNotes", "tblAlignerActivityFlags",
  "tblAlertTypes", "tblAlerts", "tblAddress", "tbCities", "SyncQueue", "Patients", "DocumentTypes",
  "DocumentTemplates", "AlignerDoctors", "tblWires", "tbltimes", "tblholidays", "tblnumbers",
  "tbloptions", "tblvideos", "tblExpenses", "tblappointments", "tblpatients", "tblAlignerBatches",
  "tblwork", "tblInvoice", "tblAlignerSets", "tblvisits"
  CASCADE;

DROP EXTENSION IF EXISTS citext;
