-- Up Migration
--
-- Unified CDC core. One change feed (change_log) captured by DB triggers, drained by N sinks
-- (services/sync/cdc/*): the raw "failover" replica and the transformed "portal" Supabase. Replaces
-- both the app-level SyncQueue enqueue (portal) and the old per-table failover changelog — one
-- capture mechanism, two sinks. See CLAUDE.md › "Sync (unified CDC)".
--
-- INERT until a sink is enabled in cdc_sink_control (the per-sink kill switch). The cdc engine
-- flips a sink on at boot when its env flag is set, off on shutdown — so the log never grows while
-- nothing drains it.

-- Per-sink master switch + health flag.
CREATE TABLE "cdc_sink_control" (
  "sink"       text PRIMARY KEY,                 -- 'failover' | 'portal'
  "enabled"    boolean NOT NULL DEFAULT false,   -- capture for this sink on/off (kill switch)
  "stale"      boolean NOT NULL DEFAULT false,   -- anti-bloat breaker tripped: sink needs a full reload
  "note"       text,
  "updated_at" timestamp NOT NULL DEFAULT now()
);
INSERT INTO "cdc_sink_control" ("sink") VALUES ('failover'), ('portal');

-- Coalescing change feed: at most ONE pending row per (sink, table, pk). Repeated edits collapse,
-- so during an outage the log grows by distinct rows touched, not by write count (anti-bloat).
CREATE TABLE "change_log" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sink"       text   NOT NULL,
  "tbl"        text   NOT NULL,
  "pk"         text   NOT NULL,                  -- PK value as text (generic across int/text PKs)
  "op"         char(1) NOT NULL,                 -- 'I' | 'U' | 'D'
  "changed_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "change_log_uq" UNIQUE ("sink", "tbl", "pk")
);
CREATE INDEX "IDX_change_log_drain" ON "change_log" ("sink", "changed_at", "id");

-- Generic capture function. TG_ARGV[0] = PK column; TG_ARGV[1..] = sink names this table feeds.
-- Skips writes originating from the reverse sync (Supabase → local) to avoid a forward↔reverse
-- loop — those writes set `app.cdc_origin = 'reverse'` (see services/sync/sync-engine.ts).
CREATE FUNCTION "cdc_capture"() RETURNS trigger AS $$
DECLARE
  pk_col text := TG_ARGV[0];
  pk_val text;
  v_op   char(1);
  i      int;
  s      text;
BEGIN
  IF current_setting('app.cdc_origin', true) = 'reverse' THEN
    RETURN NULL;                                  -- reverse-sync write: do not re-capture
  END IF;

  IF TG_OP = 'DELETE' THEN
    v_op := 'D'; pk_val := (to_jsonb(OLD) ->> pk_col);
  ELSIF TG_OP = 'UPDATE' THEN
    v_op := 'U'; pk_val := (to_jsonb(NEW) ->> pk_col);
  ELSE
    v_op := 'I'; pk_val := (to_jsonb(NEW) ->> pk_col);
  END IF;
  IF pk_val IS NULL THEN
    RETURN NULL;
  END IF;

  -- Fan out to each sink named on the trigger, if that sink's capture is enabled.
  FOR i IN 1 .. (TG_NARGS - 1) LOOP
    s := TG_ARGV[i];
    IF EXISTS (SELECT 1 FROM cdc_sink_control c WHERE c.sink = s AND c.enabled) THEN
      INSERT INTO change_log ("sink", "tbl", "pk", "op", "changed_at")
      VALUES (s, TG_TABLE_NAME, pk_val, v_op, now())
      ON CONFLICT ("sink", "tbl", "pk")
      DO UPDATE SET "op" = EXCLUDED."op", "changed_at" = EXCLUDED."changed_at";
    END IF;
  END LOOP;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Down Migration

DROP FUNCTION IF EXISTS "cdc_capture"();
DROP TABLE IF EXISTS "change_log";
DROP TABLE IF EXISTS "cdc_sink_control";
