-- Up Migration
--
-- Reverse CDC v2 (two-way sync) — LOCAL side. Two changes, both sync infra (LOCAL ONLY; the Supabase
-- mirror gets its symmetric counterparts from migrations/supabase/reverse-cdc.sql):
--
--   1. set_updated_at() — honour the origin guard. A reverse-sync apply runs under
--      `SET LOCAL app.cdc_origin='reverse'` and carries the incoming Supabase `updated_at` verbatim.
--      The BEFORE trigger must NOT re-stamp it, or whole-row LWW silently breaks: in
--      INSERT … ON CONFLICT DO UPDATE the BEFORE-INSERT trigger transforms NEW *before* EXCLUDED is
--      evaluated, so re-stamping would make the LWW `WHERE EXCLUDED.updated_at > target.updated_at`
--      compare "now" vs stored — reverse applies would always win and the stored timestamp would be
--      corrupted. The guard makes `updated_at` a single value stamped only at a genuine edit's
--      origin. Symmetric with cdc_capture()'s existing reverse-origin skip → the origin guard now
--      covers BOTH the capture trigger and the version trigger.
--
--   2. Odd identity sequences — give local a disjoint id space from Supabase so explicit sync inserts
--      (identity is GENERATED BY DEFAULT, so they don't advance the receiving sequence) can never mint
--      a colliding id. Local mints ODD, Supabase mints EVEN. Re-base each reverse-set table's identity
--      sequence to `INCREMENT BY 2 RESTART WITH <smallest odd > max(id)>`. Text-PK (options) and
--      shared-PK (patient_portal_auth) tables have no own sequence → auto-skipped (still LWW-reverse-
--      writable). This is the ONE intentional DDL-parity divergence between local and the mirror.
--
-- NO column/type change → `npm run db:codegen` output is UNCHANGED (run it to confirm a no-op diff).
-- APPLY DURING A QUIET WINDOW (app stopped, forward backlog 0) so local/Supabase max(id) agree —
-- run the even-sequence half (migrations/supabase/reverse-cdc.sql) in the SAME window.

-- ── 1. Version trigger: skip re-stamping on reverse-origin writes ──────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  -- Reverse-sync write: preserve the incoming Supabase updated_at verbatim (LWW keystone).
  IF current_setting('app.cdc_origin', true) = 'reverse' THEN
    RETURN NEW;
  END IF;
  NEW.updated_at := localtimestamp;
  RETURN NEW;
END;
$$;

-- ── 2. Odd identity sequences over the reverse set (captured ∧ has updated_at) ─────────────────────
DO $$
DECLARE
  r        record;
  seq      text;
  max_id   bigint;
  next_odd bigint;
BEGIN
  FOR r IN
    SELECT c.relname AS tbl, a.attname AS pk
      FROM pg_trigger tg
      JOIN pg_class c     ON c.oid = tg.tgrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      JOIN pg_index i     ON i.indrelid = c.oid AND i.indisprimary AND array_length(i.indkey::int[], 1) = 1
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
     WHERE tg.tgname = 'trg_cdc_capture'
       AND EXISTS (
         SELECT 1 FROM information_schema.columns col
          WHERE col.table_schema = 'public' AND col.table_name = c.relname AND col.column_name = 'updated_at'
       )
  LOOP
    seq := pg_get_serial_sequence('public.' || quote_ident(r.tbl), r.pk);
    IF seq IS NULL THEN
      RAISE NOTICE 'odd-seq: % has no identity sequence (PK %) — skipped', r.tbl, r.pk;
      CONTINUE; -- text PK (options) / shared PK (patient_portal_auth) — still LWW-reverse-writable
    END IF;
    EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I', r.pk, r.tbl) INTO max_id;
    next_odd := max_id + 1 + (max_id % 2); -- smallest odd strictly greater than max_id
    EXECUTE format('ALTER SEQUENCE %s INCREMENT BY 2 RESTART WITH %s', seq, next_odd);
    RAISE NOTICE 'odd-seq: % (%) → INCREMENT BY 2 RESTART WITH %', r.tbl, seq, next_odd;
  END LOOP;
END $$;

-- Down Migration
--
-- Restore the unconditional version trigger and best-effort reset increments to 1. (RESTART is left
-- as-is — the current odd value is a valid sequence position; only the parity stride is reverted.)

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := localtimestamp;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  r   record;
  seq text;
BEGIN
  FOR r IN
    SELECT c.relname AS tbl, a.attname AS pk
      FROM pg_trigger tg
      JOIN pg_class c     ON c.oid = tg.tgrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      JOIN pg_index i     ON i.indrelid = c.oid AND i.indisprimary AND array_length(i.indkey::int[], 1) = 1
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
     WHERE tg.tgname = 'trg_cdc_capture'
       AND EXISTS (
         SELECT 1 FROM information_schema.columns col
          WHERE col.table_schema = 'public' AND col.table_name = c.relname AND col.column_name = 'updated_at'
       )
  LOOP
    seq := pg_get_serial_sequence('public.' || quote_ident(r.tbl), r.pk);
    IF seq IS NULL THEN CONTINUE; END IF;
    EXECUTE format('ALTER SEQUENCE %s INCREMENT BY 1', seq);
  END LOOP;
END $$;
