-- Dedicated `labs` table + proper FKs from work_items and expenses; retire the
-- "Lab" / "Employees" expense-subcategory shadows in favour of entity FKs.
--
-- Why: the Bridge/Veneers work item's lab field (and lab/salary expenses) were keyed
-- by the "Lab"/"Employees" expense SUBCATEGORIES — a name-matched shadow (the employees
-- one was kept in sync by employee-queries.ts). A lab is a first-class entity like a
-- doctor or implant manufacturer, so it gets its own table and is referenced by a real
-- FK, exactly like works.dr_id -> employees and expenses.subcategory_id ->
-- expense_subcategories. The Lab (7) and Employees (5) CATEGORIES stay (per-category
-- reporting is unchanged); only their subcategory shadows go, and the sub-level detail
-- now comes from expenses.lab_id / expenses.employee_id.
--
-- CDC: `labs` carries a `cdc_capture('id','failover')` trigger (forward-only, local ->
-- Supabase — no `updated_at`, so NOT reverse-synced; same posture as implant_manufacturers
-- and the shade tables). The Supabase mirror MUST have the labs table + the new
-- work_items/expenses columns or the failover upsert silently drops the fields — applied
-- there FIRST (migrations/supabase/labs-normalization-2026-06-27.sql).
--
-- `id` is plain `GENERATED BY DEFAULT AS IDENTITY` (NOT the reverse-set ODD/EVEN split) —
-- forward-only, never reverse-inserted (same rationale as the lookup/shade tables).
--
-- Apply (squashed-baseline state — `node-pg-migrate up` would replay the baseline; run
-- directly). Run BOTH files with capture SUPPRESSED on each side (local 'reverse',
-- Supabase 'failover'); each seeds `labs` deterministically (ORDER BY subcategory_name)
-- from the identical mirrored `expense_subcategories`, so ids align with NO replication
-- between them (no dup-insert / cross-table delete-ordering hazard). Supabase FIRST:
--   scripts/psql.sh supa  -c "SET app.cdc_origin='failover';" -f migrations/supabase/labs-normalization-2026-06-27.sql
--   scripts/psql.sh local -c "SET app.cdc_origin='reverse';"  -f migrations/pg/1782500000000_labs-normalization.sql
-- Then regenerate types: npm run db:codegen
-- This file is the node-pg-migrate record AND the local DDL + data migration.

-- Up Migration

-- 1. Schema (additive) ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.labs (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_name  public.citext NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.labs
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('id', 'failover');

ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS lab_id      integer REFERENCES public.labs(id);
ALTER TABLE public.expenses   ADD COLUMN IF NOT EXISTS lab_id      integer REFERENCES public.labs(id);
ALTER TABLE public.expenses   ADD COLUMN IF NOT EXISTS employee_id integer REFERENCES public.employees(id);

CREATE INDEX IF NOT EXISTS ix_expenses_employee_id ON public.expenses(employee_id) WHERE employee_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_expenses_lab_id      ON public.expenses(lab_id)      WHERE lab_id IS NOT NULL;

-- 2. Data migration (LOCAL only — replicates to Supabase via the failover sink) ---
-- Seed labs from the existing "Lab" subcategories (ids originate here, replicate as-is).
INSERT INTO public.labs (lab_name)
  SELECT subcategory_name FROM public.expense_subcategories
  WHERE category_id = 7 ORDER BY subcategory_name;

-- Move lab expenses: subcategory(name) -> lab_id.
UPDATE public.expenses e SET lab_id = l.id
  FROM public.expense_subcategories s
  JOIN public.labs l ON l.lab_name = s.subcategory_name
  WHERE s.category_id = 7 AND e.subcategory_id = s.subcategory_id;

-- Move employee expenses: subcategory(name) -> employee_id.
UPDATE public.expenses e SET employee_id = emp.id
  FROM public.expense_subcategories s
  JOIN public.employees emp ON emp.employee_name = s.subcategory_name
  WHERE s.category_id = 5 AND e.subcategory_id = s.subcategory_id;

-- PRE-CHECK (run before the destructive steps below; expected 0 rows — resolve any by hand):
--   SELECT e.id, e.category_id, s.subcategory_name
--   FROM public.expenses e JOIN public.expense_subcategories s ON e.subcategory_id = s.subcategory_id
--   WHERE s.category_id IN (5,7) AND e.lab_id IS NULL AND e.employee_id IS NULL;

-- Detach the cat 5/7 expenses from the shadow rows, then delete the shadows.
UPDATE public.expenses SET subcategory_id = NULL WHERE category_id IN (5, 7);
DELETE FROM public.expense_subcategories WHERE category_id IN (5, 7);

-- 3. Drop the now-unused free-text lab column (0 non-empty rows). DDL — apply on BOTH DBs.
ALTER TABLE public.work_items DROP COLUMN IF EXISTS lab_name;

-- Down Migration
-- ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS lab_name public.citext;
-- ALTER TABLE public.expenses DROP COLUMN IF EXISTS employee_id;
-- ALTER TABLE public.expenses DROP COLUMN IF EXISTS lab_id;
-- ALTER TABLE public.work_items DROP COLUMN IF EXISTS lab_id;
-- DROP TABLE IF EXISTS public.labs;
-- (Note: the deleted "Lab"/"Employees" subcategory shadows are not restored by this down;
--  re-seed them from employees + a labs->subcategory backfill if ever reverted.)
