-- Maker-checker approval/notice queue for Front-Desk sensitive actions (typed-hatching-ripple
-- plan, Part C). Two `kind`s share one table:
--   'approval' — a hold: the underlying write is NOT applied yet; an admin must approve/reject.
--   'notice'   — informational only: the underlying write already applied; this is an FYI.
--
-- LOCAL-ONLY BY DESIGN — this table carries NO `cdc_capture` trigger, so it is deliberately
-- NOT replicated to the Supabase mirror (mirrors the `integration_oauth_tokens` precedent).
-- Defense-in-depth: it also has NO `updated_at` column, so it can never auto-enroll in
-- reverse sync either (the discovery query in `services/sync/cdc/cdc-schema.ts` only picks up
-- tables that have `updated_at`). `reviewed_at` is the closest analogue but is NOT named
-- `updated_at` and is nullable until reviewed, so it does not match that query's shape.
--
-- `request_id` is `GENERATED BY DEFAULT AS IDENTITY` — fine to use the plain default sequence
-- (not the ODD/EVEN local/Supabase split) because this table never replicates either direction.
--
-- `requested_at`/`reviewed_at` are `timestamp` WITHOUT time zone per CLAUDE.md (single-clinic
-- wall-clock; process TZ pinned to Asia/Baghdad).
--
-- Apply (squashed-baseline state — `node-pg-migrate up` would replay the baseline; run directly
-- instead), LOCAL only:
--   scripts/psql.sh local -f migrations/pg/1782100000000_approval-requests.sql
-- Then regenerate types: npm run db:codegen
-- This file is the node-pg-migrate record.

-- Up Migration
CREATE TABLE IF NOT EXISTS public.approval_requests (
  request_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind            text NOT NULL CHECK (kind IN ('approval', 'notice')),
  action_type     text NOT NULL,
  target_table    text NOT NULL,
  target_id       integer NOT NULL,
  person_id       integer,
  payload         jsonb NOT NULL,
  target_version  text,
  summary         text NOT NULL,
  requested_by    text NOT NULL,
  requested_at    timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'rejected', 'acknowledged', 'failed', 'stale')),
  reviewed_by     text,
  reviewed_at     timestamp,
  review_note     text
);

CREATE INDEX IF NOT EXISTS ix_approval_requests_pending
  ON public.approval_requests (request_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS ix_approval_requests_requested_by
  ON public.approval_requests (requested_by, requested_at DESC);

-- Down Migration
-- DROP TABLE IF EXISTS public.approval_requests;
