-- Dental shade lookup tables (Vita Classic + Vita 3D-Master) + work-item shade columns.
--
-- Why: lab-fabricated work types (Bridge id 17, Veneers id 9) need to record the target
-- tooth colour for the lab. The two industry-standard shade systems each get their own
-- physical lookup table (the user's chosen design — see the shade-tables plan), both
-- admin-editable via the generic Lookups admin (LOOKUP_TABLE_CONFIG). A work item stores
-- the chosen system + shade as TEXT (like `material`/`lab_name` — no FK), so later edits
-- to the shade lists never orphan a work item.
--
-- CDC: both lookup tables carry a `cdc_capture('id', 'failover')` trigger (forward-only,
-- local -> Supabase — no `updated_at`, so NOT reverse-synced; same posture as the other
-- lookup tables, e.g. patient_types). The Supabase mirror MUST have the same tables +
-- the new work_items columns or the failover upsert silently drops the fields — applied
-- there first (migrations/supabase/shade-tables-2026-06-27.sql, which also seeds the rows
-- so the mirror is self-sufficient regardless of replication timing).
--
-- `id` is plain `GENERATED BY DEFAULT AS IDENTITY` (NOT the reverse-set ODD/EVEN split) —
-- these tables are forward-only and never receive reverse inserts, so the default
-- sequence is fine (same rationale as approval_requests / the lookup tables).
--
-- Apply (squashed-baseline state — `node-pg-migrate up` would replay the baseline; run
-- directly instead). Apply the Supabase mirror FIRST, then LOCAL:
--   scripts/psql.sh supa  -f migrations/supabase/shade-tables-2026-06-27.sql
--   scripts/psql.sh local -f migrations/pg/1782300000000_shade-tables.sql
-- Then regenerate types: npm run db:codegen
-- This file is the node-pg-migrate record.

-- Up Migration
CREATE TABLE IF NOT EXISTS public.shade_vita_classic (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shade public.citext NOT NULL
);

CREATE TABLE IF NOT EXISTS public.shade_3d_master (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shade public.citext NOT NULL
);

CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.shade_vita_classic
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('id', 'failover');
CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.shade_3d_master
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('id', 'failover');

ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS shade_system public.citext;
ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS shade        public.citext;

-- Seed: the standard shade values, ordered as they should appear in the dropdown.
INSERT INTO public.shade_vita_classic (shade) VALUES
  ('A1'), ('A2'), ('A3'), ('A3.5'), ('A4'),
  ('B1'), ('B2'), ('B3'), ('B4'),
  ('C1'), ('C2'), ('C3'), ('C4'),
  ('D2'), ('D3'), ('D4');

INSERT INTO public.shade_3d_master (shade) VALUES
  ('0M1'), ('0M2'), ('0M3'),
  ('1M1'), ('1M2'),
  ('2L1.5'), ('2L2.5'), ('2M1'), ('2M2'), ('2M3'), ('2R1.5'), ('2R2.5'),
  ('3L1.5'), ('3L2.5'), ('3M1'), ('3M2'), ('3M3'), ('3R1.5'), ('3R2.5'),
  ('4L1.5'), ('4L2.5'), ('4M1'), ('4M2'), ('4M3'), ('4R1.5'), ('4R2.5'),
  ('5M1'), ('5M2'), ('5M3');

-- Down Migration
-- ALTER TABLE public.work_items DROP COLUMN IF EXISTS shade;
-- ALTER TABLE public.work_items DROP COLUMN IF EXISTS shade_system;
-- DROP TABLE IF EXISTS public.shade_3d_master;
-- DROP TABLE IF EXISTS public.shade_vita_classic;
