-- Saved slideshow configurations for the Patient Presentation Slideshow
-- (public/js/components/react/slideshow/). Two kinds share one table:
--   'literal'  — a PER-PATIENT saved sequence (person_id set): the exact picked
--                photos (gallery + patient-folder), rebuilt verbatim on apply.
--   'template' — a CLINIC-WIDE generic recipe (person_id NULL): photo-type +
--                first/latest session, resolved against whatever patient is open.
--
-- ⚠️ SUPERSEDED as of 2026-07-21 by
-- migrations/pg/1782900000000_mirror-approvals-slideshow.sql: this table is now
-- MIRRORED (forward-only, local → Supabase) and carries a `cdc_capture('id',
-- 'failover')` trigger. The paragraph below records the ORIGINAL local-only
-- decision and is kept for history — it no longer describes the live state.
--
-- [HISTORICAL] LOCAL-ONLY BY DESIGN — this table carries NO `cdc_capture` trigger,
-- so it is deliberately NOT replicated to the Supabase mirror (mirrors the
-- `approval_requests` / `integration_oauth_tokens` precedent).
--
-- Still true after the promotion: it has NO `updated_at` column, so it can never
-- auto-enroll in reverse sync (the discovery query in
-- `services/sync/cdc/cdc-schema.ts` only picks up tables that have `updated_at`).
-- `created_at` is the closest analogue but is NOT named `updated_at`, so it does
-- not match that query's shape. It is therefore FORWARD-ONLY, and its forward
-- upsert is a blind upsert, not an LWW one.
--
-- `id` is `GENERATED BY DEFAULT AS IDENTITY` — still the plain default sequence
-- (not the ODD/EVEN local/Supabase split), which stays correct: that split exists
-- only for the two-way reverse set, and Supabase never mints an id for a
-- forward-only table.
--
-- `created_at` is `timestamp` WITHOUT time zone per CLAUDE.md (single-clinic
-- wall-clock; process TZ pinned to Asia/Baghdad).
--
-- Apply (squashed-baseline state — `node-pg-migrate up` would replay the
-- baseline; run directly instead), LOCAL only:
--   scripts/psql.sh local -f migrations/pg/1782600000000_slideshow-configs.sql
-- Then regenerate types: npm run db:codegen
-- This file is the node-pg-migrate record.

-- Up Migration
CREATE TABLE IF NOT EXISTS public.slideshow_configs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id   integer REFERENCES public.patients(person_id) ON DELETE CASCADE, -- NULL = generic template
  name        public.citext NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('literal', 'template')),
  config      jsonb NOT NULL,
  created_at  timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

-- Hot path: list one patient's configs + the generic templates (person_id NULL).
CREATE INDEX IF NOT EXISTS ix_slideshow_configs_person
  ON public.slideshow_configs (person_id);

-- Seed a couple of generic templates (person_id NULL → apply to any patient).
-- i13 = Smile, i10 = Profile (see slideshow/photoTypes.ts PHOTO_TYPE_LABELS).
INSERT INTO public.slideshow_configs (person_id, name, kind, config)
SELECT NULL, 'Smile — Initial & Final', 'template',
  '{"kind":"template","slides":[{"photos":[{"tp":"first","type":"i13"},{"tp":"latest","type":"i13"}]}]}'::jsonb
WHERE NOT EXISTS (
  SELECT 1 FROM public.slideshow_configs WHERE person_id IS NULL AND name = 'Smile — Initial & Final'
);

INSERT INTO public.slideshow_configs (person_id, name, kind, config)
SELECT NULL, 'Profile — Initial & Final', 'template',
  '{"kind":"template","slides":[{"photos":[{"tp":"first","type":"i10"},{"tp":"latest","type":"i10"}]}]}'::jsonb
WHERE NOT EXISTS (
  SELECT 1 FROM public.slideshow_configs WHERE person_id IS NULL AND name = 'Profile — Initial & Final'
);

-- Down Migration
-- DROP TABLE IF EXISTS public.slideshow_configs;
