-- Announcements (aligner portal doctors) + Portal Activity feed (staff header bell).
--
-- Three pieces, three sync postures (docs/sync-cdc.md):
--
--   1. doctor_announcements — staff-app-authored, FORWARD-ONLY local → Supabase
--      (lab_cases pattern: cdc_capture('announcement_id','failover') trigger here,
--      none on the mirror; deliberately NO updated_at so the table stays OUT of
--      reverse sync; plain identity — the mirror never inserts announcements).
--      The portal reads it on the mirror under RLS (broadcast OR own dr_id —
--      aligner-portal-external/sql/phase3-announcements.sql).
--
--   2. doctor_announcement_reads — PORTAL-written on the mirror, REVERSE-synced home
--      (aligner_notes pattern): updated_at + odd/even identity split (local ODD
--      START 1 INCREMENT 2, mirror EVEN START 2 INCREMENT 2 — inserts never collide)
--      + set_updated_at()/cdc_capture() triggers. Both fns skip under
--      app.cdc_origin='reverse', so reverse-applied portal rows neither echo back
--      nor get their updated_at re-stamped (the LWW keystone).
--
--   3. aligner_activity_flags — generalized into the staff Portal-Activity feed:
--      ck_activitytype widened (+PhotoUploaded, +FileUploaded) and a `source`
--      column ('staff'|'portal', default 'staff') added. The staff bell reads only
--      source='portal' rows; existing staff-side flag writes stay 'staff' via the
--      default and never surface in the feed.
--
-- Apply (squashed-baseline state — `node-pg-migrate up` would replay the baseline;
-- run directly instead). Apply the Supabase mirror FIRST (CDC replicates row DATA,
-- never DDL — the mirror must have the tables/column before the first forward
-- upsert), then the portal RLS/grants, then LOCAL:
--   scripts/psql.sh supa  -f migrations/supabase/announcements-2026-07-11.sql
--   scripts/psql.sh supa  -f aligner-portal-external/sql/phase3-announcements.sql
--   scripts/psql.sh local -f migrations/pg/1782800000000_announcements-and-portal-activity.sql
-- Then regenerate types: npm run db:codegen
-- This file is the node-pg-migrate record.

-- Up Migration

-- ── 1. doctor_announcements (forward-only source) ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.doctor_announcements (
  announcement_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title             text NOT NULL,
  message           text NOT NULL,
  announcement_type text NOT NULL DEFAULT 'info'
                      CHECK (announcement_type IN ('success', 'info', 'warning', 'urgent')),
  -- NULL = broadcast to every portal doctor
  target_doctor_id  integer REFERENCES public.aligner_doctors(dr_id) ON DELETE CASCADE,
  is_dismissible    boolean NOT NULL DEFAULT true,
  link_url          text,
  link_text         text,
  expires_at        timestamp,
  -- NULL = manual staff-composed announcement; set = system-generated batch event
  auto_event        text CHECK (auto_event IN ('batch_manufactured', 'batch_delivered')),
  -- deliberately NO FK: deleting a batch must not break its announcement history
  related_batch_id  integer,
  created_by        text,
  created_at        timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_announcements_target_created
  ON public.doctor_announcements (target_doctor_id, created_at DESC);

-- UNDO manufacture/delivery deletes by (auto_event, related_batch_id)
CREATE INDEX IF NOT EXISTS ix_announcements_auto_batch
  ON public.doctor_announcements (related_batch_id)
  WHERE auto_event IS NOT NULL;

CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.doctor_announcements
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('announcement_id', 'failover');

-- ── 2. doctor_announcement_reads (reverse-synced home; local ids ODD) ───────────
CREATE TABLE IF NOT EXISTS public.doctor_announcement_reads (
  read_id         integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 2) PRIMARY KEY,
  announcement_id integer NOT NULL REFERENCES public.doctor_announcements(announcement_id) ON DELETE CASCADE,
  -- CASCADE: the default NO ACTION would block deleting an aligner doctor
  -- once they have read receipts
  dr_id           integer NOT NULL REFERENCES public.aligner_doctors(dr_id) ON DELETE CASCADE,
  read_at         timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  updated_at      timestamp,
  UNIQUE (announcement_id, dr_id)
);

-- Portal fetches receipts by dr_id (the UNIQUE index leads with announcement_id)
CREATE INDEX IF NOT EXISTS ix_announcement_reads_dr
  ON public.doctor_announcement_reads (dr_id);

CREATE TRIGGER trg_set_updated_at BEFORE INSERT OR UPDATE ON public.doctor_announcement_reads
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.doctor_announcement_reads
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('read_id', 'failover');

-- ── 3. aligner_activity_flags: widen types + add source ─────────────────────────
ALTER TABLE public.aligner_activity_flags
  DROP CONSTRAINT IF EXISTS ck_activitytype;
ALTER TABLE public.aligner_activity_flags
  ADD CONSTRAINT ck_activitytype CHECK (activity_type IN
    ('DaysChanged', 'DoctorNote', 'PhotoUploaded', 'FileUploaded'));

ALTER TABLE public.aligner_activity_flags
  ADD COLUMN IF NOT EXISTS source citext NOT NULL DEFAULT 'staff'
    CHECK (source IN ('staff', 'portal'));

-- Staff bell hot path: portal rows, newest first (5-min poll)
CREATE INDEX IF NOT EXISTS ix_activity_portal_created
  ON public.aligner_activity_flags (created_at DESC)
  WHERE source = 'portal';

-- Down Migration
-- DROP INDEX IF EXISTS ix_activity_portal_created;
-- ALTER TABLE public.aligner_activity_flags DROP COLUMN IF EXISTS source;
-- ALTER TABLE public.aligner_activity_flags DROP CONSTRAINT IF EXISTS ck_activitytype;
-- ALTER TABLE public.aligner_activity_flags ADD CONSTRAINT ck_activitytype
--   CHECK (activity_type IN ('DaysChanged', 'DoctorNote'));
-- DROP TABLE IF EXISTS public.doctor_announcement_reads;
-- DROP TABLE IF EXISTS public.doctor_announcements;
