-- Lab case tracker: a case header (`lab_cases`, one per prosthetic work item) + an
-- append-only event log (`lab_case_events`) recording every stage transition,
-- remake, hold/resume, note, and cancel. Tracks where a Crown/Bridge (work type 17)
-- or Veneers (work type 9) case physically sits between the clinic and the external
-- dental lab — see docs plan "Lab Tracking Feature".
--
-- Sync posture: FAILOVER-MIRRORED, forward-only (local -> Supabase) — clones the
-- shade-tables precedent (migrations/pg/1782300000000_shade-tables.sql). Both tables
-- carry a `cdc_capture('id', 'failover')` trigger; the Supabase mirror
-- (migrations/supabase/lab-cases-2026-07-02.sql) has the identical DDL minus the
-- trigger (a forward-only TARGET never captures back). Deliberately NO `updated_at`
-- column on either table: failover captures all INSERT/UPDATE/DELETE regardless, and
-- the absence of `updated_at` keeps both tables OUT of two-way reverse sync (the
-- reverse discovery query only enrolls tables that HAVE `updated_at`) — correct,
-- since the staff app is the sole writer and `lab_case_events` is append-only so
-- whole-row LWW would be meaningless. `id` is plain `GENERATED BY DEFAULT AS
-- IDENTITY` (not the reverse-set ODD/EVEN split) since these tables never receive
-- reverse inserts. No one-time row load — both tables are born empty.
--
-- Apply (squashed-baseline state — `node-pg-migrate up` would replay the baseline;
-- run directly instead). Apply the Supabase mirror FIRST, then LOCAL:
--   scripts/psql.sh supa  -f migrations/supabase/lab-cases-2026-07-02.sql
--   scripts/psql.sh local -f migrations/pg/1782700000000_lab-cases.sql
-- Then regenerate types: npm run db:codegen
-- This file is the node-pg-migrate record.

-- Up Migration
CREATE TABLE IF NOT EXISTS public.lab_cases (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id       integer NOT NULL REFERENCES public.work_items(id) ON DELETE CASCADE,
  person_id          integer NOT NULL REFERENCES public.patients(person_id),
  lab_id             integer REFERENCES public.labs(id),
  material           text,
  status             text NOT NULL DEFAULT 'sent_to_lab' CHECK (status IN (
                       'sent_to_lab', 'wax_up_tryin', 'pattern_fab', 'plastic_check',
                       'framework_fab', 'framework_tryin', 'ceramic_buildup', 'bisque_tryin',
                       'glaze', 'ready', 'delivered', 'cancelled'
                     )),
  is_on_hold         boolean NOT NULL DEFAULT false,
  is_rush            boolean NOT NULL DEFAULT false,
  due_date           date,
  sent_at            timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  delivered_at       timestamp,
  remake_count       integer NOT NULL DEFAULT 0,
  status_changed_at  timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  note               text,
  created_at         timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  created_by         text,
  delivered_by       text,
  UNIQUE (work_item_id)
);

CREATE INDEX IF NOT EXISTS ix_lab_cases_open_status
  ON public.lab_cases (status)
  WHERE status NOT IN ('delivered', 'cancelled');

CREATE INDEX IF NOT EXISTS ix_lab_cases_person
  ON public.lab_cases (person_id);

CREATE INDEX IF NOT EXISTS ix_lab_cases_open_due_date
  ON public.lab_cases (due_date)
  WHERE status NOT IN ('delivered', 'cancelled');

CREATE TABLE IF NOT EXISTS public.lab_case_events (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_case_id   integer NOT NULL REFERENCES public.lab_cases(id) ON DELETE CASCADE,
  event_type    text NOT NULL CHECK (event_type IN ('stage_change', 'remake', 'hold', 'resume', 'note', 'cancel')),
  from_status   text,
  to_status     text,
  occurred_at   timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  note          text,
  created_by    text,
  created_at    timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_lab_case_events_case_occurred
  ON public.lab_case_events (lab_case_id, occurred_at);

CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.lab_cases
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('id', 'failover');
CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.lab_case_events
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('id', 'failover');

-- Down Migration
-- DROP TABLE IF EXISTS public.lab_case_events;
-- DROP TABLE IF EXISTS public.lab_cases;
