-- Up Migration
--
-- The photo-session (time point) name list becomes a lookup table.
--
-- WHY. A session's name was free text when editing one (Photos → ⋮ → Edit) and a list of four
-- literals in the New Photo Session dialog. Both now offer one clinic-editable list, managed in
-- Settings → Lookups or by right-clicking the Name select (LOOKUP_TABLE_CONFIG key
-- `tblTimePointNames`). `time_points.tp_description` stays TEXT with no FK, like a work item's
-- shade: the list is a set of suggestions, a session may still carry any other name ("Custom
-- name…" in the edit dialog), and editing the list never rewrites an existing session.
--
-- THE ROWS. The clinic's common names, in the order the select shows them (by id): the three
-- phases, their phase-2 counterparts ("P2"), "Final+" for a procedure done after orthodontics
-- (e.g. cosmetic work), and "Retention", which the New Photo Session dialog already offered.
-- "Initial" and "Final" are also names the CODE matches on (the works' initial/final photo date
-- follows a session with exactly that name — photo-editor.routes.ts, patient-timepoint.routes.ts),
-- so services/database/fresh-install.test.ts requires them here. Explicit ids + ON CONFLICT make
-- the seed idempotent and identical on the mirror; the identity is then moved past them.
--
-- `name` is UNIQUE (citext, so case-insensitively): the select's value IS the name, and two rows
-- spelling one name would be two identical options.
--
-- CDC. Forward-only, like every lookup table: a `cdc_capture('id', 'failover')` trigger and no
-- `updated_at`, so it never enrols in reverse sync and keeps the plain identity increment.
--
-- Mirror half: migrations/supabase/time-point-names-2026-10-06.sql — apply it FIRST (additive DDL
-- goes on the mirror before local, so the failover upsert of these rows has a target table).

CREATE TABLE public.time_point_names (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name public.citext NOT NULL,
  CONSTRAINT time_point_names_name_key UNIQUE (name)
);

CREATE TRIGGER trg_cdc_capture AFTER INSERT OR DELETE OR UPDATE ON public.time_point_names
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture('id', 'failover');

INSERT INTO public.time_point_names (id, name) VALUES
  (1, 'Initial'),
  (2, 'Progress'),
  (3, 'Final'),
  (4, 'Initial P2'),
  (5, 'Progress P2'),
  (6, 'Final P2'),
  (7, 'Final+'),
  (8, 'Retention')
  ON CONFLICT DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.time_point_names', 'id'),
  (SELECT max(id) FROM public.time_point_names)
);

-- Down Migration
DROP TABLE IF EXISTS public.time_point_names;
