-- Supabase mirror half of migrations/pg/1782800000000_announcements-and-portal-activity.sql —
-- applied via scripts/psql.sh supa (small additive DDL), BEFORE the local migration, so the
-- first forward (failover) upsert has a target table/column.
--
-- Three pieces, three sync postures (docs/sync-cdc.md):
--
--   1. doctor_announcements — staff-app-authored, FORWARD-ONLY (lab_cases pattern):
--      identical DDL to local minus the cdc_capture trigger (a forward-only failover
--      TARGET never captures back). Deliberately NO updated_at, so the reverse-cdc
--      discovery query can never enroll it. Plain identity (never receives reverse
--      inserts). RLS enabled here with NO policy — the portal's SELECT policy + grant
--      land in aligner-portal-external/sql/phase3-announcements.sql.
--
--   2. doctor_announcement_reads — PORTAL-written on the mirror, reverse-synced home
--      (aligner_notes pattern): carries updated_at + EVEN identity (START 2 INCREMENT 2;
--      local is ODD) so portal inserts never collide with local ids, plus the two
--      remote triggers (set_updated_at_remote / cdc_capture_remote — both skip under
--      app.cdc_origin='failover', preserving updated_at verbatim on forward apply:
--      the LWW keystone). INSERT policy/grant: phase3-announcements.sql.
--
--   3. aligner_activity_flags — widen ck_activitytype (+PhotoUploaded, +FileUploaded)
--      and add `source` ('staff'|'portal') so portal-side uploads/notes/days-changes
--      can flag the staff bell. Already two-way synced; the new column must exist
--      HERE first or the next forward upsert of a flag row would drop the field.
--
-- New-table FKs are intentional (unlike the six phase-1 mirror tables): both tables
-- are born empty and their parents (aligner_doctors, doctor_announcements) are
-- forward-synced; a transient parent-after-child ordering self-heals via the sink's
-- defer/retry. ON DELETE CASCADE on reads.dr_id — the default NO ACTION would block
-- deleting an aligner doctor once they have read receipts.
--
-- Apply order: THIS FILE → aligner-portal-external/sql/phase3-announcements.sql →
-- migrations/pg/1782800000000_announcements-and-portal-activity.sql. Safe to re-run.

BEGIN;

-- ── 1. doctor_announcements (forward-only target: no trigger, no updated_at) ────
CREATE TABLE IF NOT EXISTS public.doctor_announcements (
  announcement_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title             text NOT NULL,
  message           text NOT NULL,
  announcement_type text NOT NULL DEFAULT 'info'
                      CHECK (announcement_type IN ('success', 'info', 'warning', 'urgent')),
  -- NULL = broadcast to every portal doctor
  target_doctor_id  integer REFERENCES public.aligner_doctors(dr_id) ON DELETE CASCADE,
  is_dismissible    boolean NOT NULL DEFAULT true,
  link_url          text,
  link_text         text,
  expires_at        timestamp,
  -- NULL = manual staff-composed announcement; set = system-generated batch event
  auto_event        text CHECK (auto_event IN ('batch_manufactured', 'batch_delivered')),
  -- deliberately NO FK: deleting a batch must not break its announcement history
  related_batch_id  integer,
  created_by        text,
  created_at        timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_announcements_target_created
  ON public.doctor_announcements (target_doctor_id, created_at DESC);

-- UNDO manufacture/delivery deletes by (auto_event, related_batch_id)
CREATE INDEX IF NOT EXISTS ix_announcements_auto_batch
  ON public.doctor_announcements (related_batch_id)
  WHERE auto_event IS NOT NULL;

-- No policy here → authenticated reads nothing until phase3-announcements.sql.
-- Owner (failover sink) bypasses RLS; do NOT FORCE.
ALTER TABLE public.doctor_announcements ENABLE ROW LEVEL SECURITY;

-- ── 2. doctor_announcement_reads (portal-written, reverse-synced home) ──────────
CREATE TABLE IF NOT EXISTS public.doctor_announcement_reads (
  read_id         integer GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 2) PRIMARY KEY,
  announcement_id integer NOT NULL REFERENCES public.doctor_announcements(announcement_id) ON DELETE CASCADE,
  dr_id           integer NOT NULL REFERENCES public.aligner_doctors(dr_id) ON DELETE CASCADE,
  read_at         timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  updated_at      timestamp,
  UNIQUE (announcement_id, dr_id)
);

-- Portal fetches receipts by dr_id (the UNIQUE index leads with announcement_id)
CREATE INDEX IF NOT EXISTS ix_announcement_reads_dr
  ON public.doctor_announcement_reads (dr_id);

ALTER TABLE public.doctor_announcement_reads ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_updated_at_remote ON public.doctor_announcement_reads;
CREATE TRIGGER trg_set_updated_at_remote BEFORE INSERT OR UPDATE ON public.doctor_announcement_reads
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_remote();

DROP TRIGGER IF EXISTS trg_cdc_capture_remote ON public.doctor_announcement_reads;
CREATE TRIGGER trg_cdc_capture_remote AFTER INSERT OR UPDATE OR DELETE ON public.doctor_announcement_reads
  FOR EACH ROW EXECUTE FUNCTION public.cdc_capture_remote('read_id');

-- ── 3. aligner_activity_flags: widen types + add source ─────────────────────────
ALTER TABLE public.aligner_activity_flags
  DROP CONSTRAINT IF EXISTS ck_activitytype;
ALTER TABLE public.aligner_activity_flags
  ADD CONSTRAINT ck_activitytype CHECK (activity_type IN
    ('DaysChanged', 'DoctorNote', 'PhotoUploaded', 'FileUploaded'));

ALTER TABLE public.aligner_activity_flags
  ADD COLUMN IF NOT EXISTS source citext NOT NULL DEFAULT 'staff'
    CHECK (source IN ('staff', 'portal'));

-- Staff bell hot path: unread/portal rows, newest first (5-min poll)
CREATE INDEX IF NOT EXISTS ix_activity_portal_created
  ON public.aligner_activity_flags (created_at DESC)
  WHERE source = 'portal';

COMMIT;
