-- Supabase mirror of migrations/pg/1782700000000_lab-cases.sql — applied via
-- SUPABASE_FAILOVER_DB_URL (small additive DDL), BEFORE the local migration, so the
-- first forward (failover) upsert has a target table.
--
-- Mirror parity rules (docs/sync-cdc.md): identical tables/columns/constraints/
-- indexes to local. The ONLY asymmetry: NO `cdc_capture` trigger here (these are
-- forward-only failover TARGETS; the mirror never captures lab-case changes back).
-- No seed rows — both tables are born empty (status values are CHECK-constrained,
-- not lookup rows).

CREATE TABLE IF NOT EXISTS public.lab_cases (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id       integer NOT NULL REFERENCES public.work_items(id) ON DELETE CASCADE,
  person_id          integer NOT NULL REFERENCES public.patients(person_id),
  lab_id             integer REFERENCES public.labs(id),
  material           text,
  status             text NOT NULL DEFAULT 'sent_to_lab' CHECK (status IN (
                       'sent_to_lab', 'wax_up_tryin', 'pattern_fab', 'plastic_check',
                       'framework_fab', 'framework_tryin', 'ceramic_buildup', 'bisque_tryin',
                       'glaze', 'ready', 'delivered', 'cancelled'
                     )),
  is_on_hold         boolean NOT NULL DEFAULT false,
  is_rush            boolean NOT NULL DEFAULT false,
  due_date           date,
  sent_at            timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  delivered_at       timestamp,
  remake_count       integer NOT NULL DEFAULT 0,
  status_changed_at  timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  note               text,
  created_at         timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  created_by         text,
  delivered_by       text,
  UNIQUE (work_item_id)
);

CREATE INDEX IF NOT EXISTS ix_lab_cases_open_status
  ON public.lab_cases (status)
  WHERE status NOT IN ('delivered', 'cancelled');

CREATE INDEX IF NOT EXISTS ix_lab_cases_person
  ON public.lab_cases (person_id);

CREATE INDEX IF NOT EXISTS ix_lab_cases_open_due_date
  ON public.lab_cases (due_date)
  WHERE status NOT IN ('delivered', 'cancelled');

CREATE TABLE IF NOT EXISTS public.lab_case_events (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_case_id   integer NOT NULL REFERENCES public.lab_cases(id) ON DELETE CASCADE,
  event_type    text NOT NULL CHECK (event_type IN ('stage_change', 'remake', 'hold', 'resume', 'note', 'cancel')),
  from_status   text,
  to_status     text,
  occurred_at   timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  note          text,
  created_by    text,
  created_at    timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_lab_case_events_case_occurred
  ON public.lab_case_events (lab_case_id, occurred_at);
