-- Supabase mirror of migrations/pg/1782500000000_labs-normalization.sql.
--
-- Mirror parity (docs/sync-cdc.md): identical tables/columns/data to local. The ONLY
-- asymmetry: NO `cdc_capture` trigger here (labs is a forward-only failover TARGET).
--
-- Execution: run this with capture SUPPRESSED so the data steps don't echo back through
-- the reverse sink, and run the LOCAL file with ITS capture suppressed too — both files
-- seed `labs` deterministically (ORDER BY subcategory_name) from the identical mirrored
-- `expense_subcategories`, so the ids line up on both sides with NO replication between
-- them (avoids dup-insert / cross-table delete-ordering hazards):
--   scripts/psql.sh supa  -c "SET app.cdc_origin='failover';" -f migrations/supabase/labs-normalization-2026-06-27.sql
--   scripts/psql.sh local -c "SET app.cdc_origin='reverse';"  -f migrations/pg/1782500000000_labs-normalization.sql
-- (Supabase cdc_capture_remote/set_updated_at_remote skip under 'failover'; local
--  cdc_capture/set_updated_at skip under 'reverse'.)

-- 1. Schema (additive) ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.labs (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_name  public.citext NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS lab_id      integer REFERENCES public.labs(id);
ALTER TABLE public.expenses   ADD COLUMN IF NOT EXISTS lab_id      integer REFERENCES public.labs(id);
ALTER TABLE public.expenses   ADD COLUMN IF NOT EXISTS employee_id integer REFERENCES public.employees(id);

CREATE INDEX IF NOT EXISTS ix_expenses_employee_id ON public.expenses(employee_id) WHERE employee_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_expenses_lab_id      ON public.expenses(lab_id)      WHERE lab_id IS NOT NULL;

-- 2. Data migration (deterministic — same result as local) ------------------
INSERT INTO public.labs (lab_name)
  SELECT subcategory_name FROM public.expense_subcategories
  WHERE category_id = 7 ORDER BY subcategory_name;

UPDATE public.expenses e SET lab_id = l.id
  FROM public.expense_subcategories s
  JOIN public.labs l ON l.lab_name = s.subcategory_name
  WHERE s.category_id = 7 AND e.subcategory_id = s.subcategory_id;

UPDATE public.expenses e SET employee_id = emp.id
  FROM public.expense_subcategories s
  JOIN public.employees emp ON emp.employee_name = s.subcategory_name
  WHERE s.category_id = 5 AND e.subcategory_id = s.subcategory_id;

UPDATE public.expenses SET subcategory_id = NULL WHERE category_id IN (5, 7);
DELETE FROM public.expense_subcategories WHERE category_id IN (5, 7);

-- 3. Drop the free-text lab column (DDL). Safe to run inline here since capture is
--    suppressed and there is no cross-DB lab_name data to replicate.
ALTER TABLE public.work_items DROP COLUMN IF EXISTS lab_name;
