-- Supabase mirror of `approval_requests` + `slideshow_configs` — the mirror half of
-- migrations/pg/1782900000000_mirror-approvals-slideshow.sql. Applied via
-- SUPABASE_FAILOVER_DB_URL (small additive DDL), BEFORE the local migration adds the
-- cdc_capture triggers, so the first forward (failover) upsert has a target table.
--
-- Both tables were originally LOCAL-ONLY BY DESIGN (see the headers of
-- migrations/pg/1782100000000_approval-requests.sql and
-- migrations/pg/1782600000000_slideshow-configs.sql, both now marked SUPERSEDED).
-- They are hereby promoted to the mirrored set, FORWARD-ONLY:
--   * neither table has an `updated_at` column, so neither auto-enrols in reverse sync
--     (the discovery query in services/sync/cdc/cdc-schema.ts#loadUpdatedAtTables only
--     picks up `updated_at` tables) — no denylist entry needed, and the forward upsert
--     is a blind upsert rather than an LWW one;
--   * consequently NO `cdc_capture_remote` / `set_updated_at_remote` trigger here, and
--     the identity sequences keep the plain default increment (NOT the ODD/EVEN
--     local/Supabase split, which only exists for the two-way reverse set).
--
-- RLS: enabled with NO policies, matching the mirror's prevailing posture (69 of 76
-- public tables have RLS on; policies exist only where the portal genuinely reads).
-- Deny-all to the PostgREST `anon`/`authenticated` roles — the forward sink connects as
-- the owner and `mirror_rw` is BYPASSRLS, so replication and the read-only web role are
-- unaffected. This matters most for `approval_requests.payload`, which carries the full
-- pending-edit row of a patient record.
--
-- Apply:
--   scripts/psql.sh supa -f migrations/supabase/mirror-approvals-slideshow-2026-07-21.sql

-- ---------------------------------------------------------------------------
-- approval_requests — maker-checker approval/notice queue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.approval_requests (
  request_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind            text NOT NULL CHECK (kind IN ('approval', 'notice')),
  action_type     text NOT NULL,
  target_table    text NOT NULL,
  target_id       integer NOT NULL,
  person_id       integer,
  payload         jsonb NOT NULL,
  target_version  text,
  summary         text NOT NULL,
  requested_by    text NOT NULL,
  requested_at    timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
  status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'rejected', 'acknowledged', 'failed', 'stale')),
  reviewed_by     text,
  reviewed_at     timestamp,
  review_note     text
);

CREATE INDEX IF NOT EXISTS ix_approval_requests_pending
  ON public.approval_requests (request_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS ix_approval_requests_requested_by
  ON public.approval_requests (requested_by, requested_at DESC);

ALTER TABLE public.approval_requests ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- slideshow_configs — saved Patient Presentation Slideshow sequences/templates
-- ---------------------------------------------------------------------------
-- NOTE: deliberately NOT seeded with the two generic templates the local migration
-- inserts. They arrive through the one-time row load with their LOCAL ids intact;
-- seeding here would mint duplicates under different ids that the forward upsert
-- could never reconcile.
CREATE TABLE IF NOT EXISTS public.slideshow_configs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id   integer REFERENCES public.patients(person_id) ON DELETE CASCADE, -- NULL = generic template
  name        public.citext NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('literal', 'template')),
  config      jsonb NOT NULL,
  created_at  timestamp NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_slideshow_configs_person
  ON public.slideshow_configs (person_id);

ALTER TABLE public.slideshow_configs ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Grants for the read-only web role (mirror-grants.sql covers future tables via
-- ALTER DEFAULT PRIVILEGES, but only for tables created by the role that ran it —
-- restate explicitly so this file stands alone). SELECT only: these are
-- forward-only targets, never writable from the mirror.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mirror_rw') THEN
    GRANT SELECT ON public.approval_requests TO mirror_rw;
    GRANT SELECT ON public.slideshow_configs TO mirror_rw;
  END IF;
END $$;
