-- Works-derived patient-type taxonomy — row data only (NO DDL; the failover CDC
-- sink forwards these rows to Supabase). Convention of seed-patient-types-ar.sql:
-- applied via scripts/psql.sh. Fully idempotent — safe to re-run and safe to apply
-- to LOCAL and Supabase both (ON CONFLICT DO NOTHING + value-set UPDATEs).
--
-- Patient type is now DERIVED from a patient's works by classifyPatient()
-- (shared/treatment-taxonomy.ts) and materialized into patients.patient_type_id.
-- The ids below are CODE CONSTANTS (work_type 23 = Consult, patient_type 10 =
-- X-ray) — this file MUST run before the code deploys on each instance.
--
-- AR strings authored by Claude — FLAG FOR DOCTOR REVIEW.
--
-- Rows 6/7/8 (OPG / Missing / Finisjed / No Photos) are NOT deleted here — they
-- stay FK-referenced until the Phase-7 backfill reclassifies every patient off
-- them (scripts/backfill-patient-types.mts).

-- 1. New 'Consult' work type (id 23). Identity is GENERATED BY DEFAULT → an explicit
--    id insert needs no OVERRIDING. Re-point the sequence past it afterwards.
INSERT INTO public.work_types (id, work_type) VALUES (23, 'Consult')
  ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.work_types', 'id'), (SELECT MAX(id) FROM public.work_types));

-- 2. Rename the reused patient-type rows to the derived-taxonomy labels. 4 (Consult)
--    and 9 (Aligner Lab) keep their names. 'Former Patient' (2) also catches
--    discontinued treatments and must NOT read as the work-status 'Finished'.
UPDATE public.patient_types SET patient_type = 'Active Ortho',     patient_type_name_ar = 'تقويم نشط'      WHERE id = 1;
UPDATE public.patient_types SET patient_type = 'Former Patient',   patient_type_name_ar = 'مريض سابق'      WHERE id = 2;
UPDATE public.patient_types SET patient_type = 'New / No Works',   patient_type_name_ar = 'جديد'           WHERE id = 3;
UPDATE public.patient_types SET patient_type = 'Active Non-Ortho', patient_type_name_ar = 'نشط غير تقويمي' WHERE id = 5;

-- 3. New 'X-ray' patient type (id 10) for imaging-only patients.
INSERT INTO public.patient_types (id, patient_type, patient_type_name_ar) VALUES (10, 'X-ray', 'أشعة')
  ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.patient_types', 'id'), (SELECT MAX(id) FROM public.patient_types));

-- 4. The 'Clinic' pseudo-doctor used for auto-created intake works (X-ray/Consult).
--    No-op locally (id 11 exists); insurance for other deployments. employee_name is
--    citext → the guard is case-insensitive.
INSERT INTO public.employees (employee_name, is_active)
SELECT 'Clinic', true
WHERE NOT EXISTS (SELECT 1 FROM public.employees WHERE employee_name = 'Clinic');
