-- ============================================================================================
-- Reverse CDC v2 (two-way sync) — SUPABASE side. Additive, Supabase-ONLY infra applied to the
-- single mirror via SUPABASE_FAILOVER_DB_URL (small additive DDL — may be applied directly per
-- CLAUDE.md, or run by the user). This is NOT a node-pg-migrate migration: it lives outside
-- migrations/pg/ on purpose. The mirror's schema is hand-managed for parity, and these
-- functions/triggers/feed-tables live on the MIRROR ONLY (local has its own cdc_capture()/
-- change_log; the symmetric local half is migrations/pg/..._reverse-sync-version-guard-and-odd-pk).
--
-- ⚠️ ORDERING HAZARD — apply this ONLY after the forward-write code (origin GUC) is live:
--   set_updated_at_remote() re-stamps updated_at on ANY write NOT tagged app.cdc_origin='failover'.
--   The forward mirror sink tags its pool origin='failover', so its writes skip the trigger and the
--   mirrored updated_at travels verbatim. But if this file is applied while an OLD forward sink
--   (no GUC) is still running, every live mirror write would clobber the mirrored updated_at and
--   spuriously fire cdc_capture_remote. So: deploy the new code FIRST, then apply this. See the
--   rollout runbook in CLAUDE.md › Sync.
--
-- ⚠️ FULL-RELOAD NOTE — a bulk reload that does NOT carry the origin flag will hit
--   set_updated_at_remote and stamp fresh Supabase timestamps over every reloaded updated_at
--   (mirror corruption). Run any reload with `SET app.cdc_origin='failover'` for its session
--   (e.g. PGOPTIONS=-c app.cdc_origin=failover) — or DISABLE TRIGGER trg_cdc_capture_remote +
--   trg_set_updated_at_remote for the load — then re-apply the even sequences (§5) afterward.
--   (Disabling the reverse sink alone is NOT enough: set_updated_at_remote is gated by the origin
--   flag, not by cdc_sink_control.)
-- ============================================================================================

-- ── 1. Sync-infra tables (same DDL as local; Supabase-only — NOT mirrored from local) ─────────────
CREATE TABLE IF NOT EXISTS "cdc_sink_control" (
  "sink"       text PRIMARY KEY,
  "enabled"    boolean NOT NULL DEFAULT false,
  "stale"      boolean NOT NULL DEFAULT false,
  "note"       text,
  "updated_at" timestamp NOT NULL DEFAULT now()
);
-- Reverse capture OFF by default — the engine flips it on at boot when REVERSE_SYNC_ENABLED=true.
INSERT INTO "cdc_sink_control" ("sink") VALUES ('reverse') ON CONFLICT ("sink") DO NOTHING;

CREATE TABLE IF NOT EXISTS "change_log" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sink"       text    NOT NULL,
  "tbl"        text    NOT NULL,
  "pk"         text    NOT NULL,
  "op"         char(1) NOT NULL,
  "changed_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "change_log_uq" UNIQUE ("sink", "tbl", "pk")
);
CREATE INDEX IF NOT EXISTS "IDX_change_log_drain" ON "change_log" ("sink", "changed_at", "id");

-- ── 2. Version trigger (Supabase side): preserve updated_at on forward mirror writes ──────────────
-- Symmetric to local set_updated_at()'s reverse-origin skip. A forward mirror write carries the
-- local-stamped updated_at and runs under origin='failover' → keep it verbatim. A genuine web/portal
-- edit on Supabase (no origin flag) gets a fresh wall-clock stamp, matching local semantics.
CREATE OR REPLACE FUNCTION set_updated_at_remote() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF current_setting('app.cdc_origin', true) = 'failover' THEN
    RETURN NEW;                                   -- forward mirror write: keep incoming updated_at
  END IF;
  NEW.updated_at := localtimestamp;               -- genuine Supabase edit: stamp it
  RETURN NEW;
END;
$$;

-- ── 3. Capture trigger (Supabase side): record genuine web/portal edits into change_log('reverse') ─
-- Same op-code/coalescing logic as local cdc_capture(), but skips forward mirror writes
-- (origin='failover') and fans out only to sink 'reverse'. TG_ARGV[0] = the table's PK column.
--
-- SECURITY DEFINER (runs as the function OWNER, which owns change_log + cdc_sink_control): the
-- trigger writes change_log on behalf of the writing role, but a web/portal writer is NOT the owner
-- — it is `mirror_rw` (raw web app) or `authenticated` (the aligner portal's RLS-scoped JWT), neither
-- of which holds INSERT/UPDATE on change_log. Without SECURITY DEFINER such a write would fail
-- `permission denied for table change_log` and never reach the reverse feed. The function only ever
-- records a (tbl, pk, op) pointer — no row data — and the actual row write it reacts to is still
-- governed by that role's RLS + table grants, so this does not widen what a doctor can change.
-- The origin guard below reads a session GUC, which is privilege-independent, so it is unaffected.
CREATE OR REPLACE FUNCTION cdc_capture_remote() RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  pk_col text := TG_ARGV[0];
  pk_val text;
  v_op   char(1);
BEGIN
  IF current_setting('app.cdc_origin', true) = 'failover' THEN
    RETURN NULL;                                  -- forward mirror write: do not echo back to local
  END IF;

  IF    TG_OP = 'DELETE' THEN v_op := 'D';
  ELSIF TG_OP = 'UPDATE' THEN v_op := 'U';
  ELSE                        v_op := 'I';
  END IF;

  IF EXISTS (SELECT 1 FROM cdc_sink_control c WHERE c.sink = 'reverse' AND c.enabled) THEN
    pk_val := (to_jsonb(CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END) ->> pk_col);
    IF pk_val IS NULL THEN
      RETURN NULL;
    END IF;
    INSERT INTO change_log ("sink", "tbl", "pk", "op", "changed_at")
    VALUES ('reverse', TG_TABLE_NAME, pk_val, v_op, now())
    ON CONFLICT ("sink", "tbl", "pk")
    DO UPDATE SET "op" = EXCLUDED."op", "changed_at" = EXCLUDED."changed_at";
  END IF;

  RETURN NULL;
END;
$$;

-- ── 4. Attach BOTH triggers to the reverse set (tables with updated_at, excluding infra) ──────────
-- The reverse set is discovered by the updated_at column (matches local's captured∧updated_at set,
-- since every captured updated_at table is mirrored here). Infra/session tables are excluded — in
-- particular cdc_sink_control HAS an updated_at column and MUST be excluded, or the engine's own
-- control writes would self-capture / loop.
DO $$
DECLARE
  r  record;
  pk text;
BEGIN
  FOR r IN
    SELECT col.table_name AS tbl
      FROM information_schema.columns col
      JOIN information_schema.tables t
        ON t.table_schema = col.table_schema AND t.table_name = col.table_name AND t.table_type = 'BASE TABLE'
     WHERE col.table_schema = 'public'
       AND col.column_name = 'updated_at'
       AND col.table_name NOT IN
           ('change_log', 'cdc_sink_control', 'pgmigrations', 'staff_sessions', 'portal_sessions', 'dolphin_sync_map')
  LOOP
    SELECT a.attname INTO pk
      FROM pg_index i
      JOIN pg_class c     ON c.oid = i.indrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
     WHERE c.relname = r.tbl AND i.indisprimary AND array_length(i.indkey::int[], 1) = 1;
    IF pk IS NULL THEN
      RAISE NOTICE 'reverse-cdc: % has no single-column PK — skipped', r.tbl;
      CONTINUE;
    END IF;
    EXECUTE format('DROP TRIGGER IF EXISTS trg_set_updated_at_remote ON %I', r.tbl);
    EXECUTE format(
      'CREATE TRIGGER trg_set_updated_at_remote BEFORE INSERT OR UPDATE ON %I '
      || 'FOR EACH ROW EXECUTE FUNCTION set_updated_at_remote()', r.tbl);
    EXECUTE format('DROP TRIGGER IF EXISTS trg_cdc_capture_remote ON %I', r.tbl);
    EXECUTE format(
      'CREATE TRIGGER trg_cdc_capture_remote AFTER INSERT OR UPDATE OR DELETE ON %I '
      || 'FOR EACH ROW EXECUTE FUNCTION cdc_capture_remote(%L)', r.tbl, pk);
    RAISE NOTICE 'reverse-cdc: attached triggers on % (PK %)', r.tbl, pk;
  END LOOP;
END $$;

-- ── 5. EVEN identity sequences (disjoint from local's ODD) ─────────────────────────────────────────
-- Run in the SAME quiet window as the local odd-sequence half so max(id) agrees on both DBs. Re-runs
-- are safe (max only grows → the even base only moves forward).
DO $$
DECLARE
  r         record;
  pk        text;
  seq       text;
  max_id    bigint;
  next_even bigint;
BEGIN
  FOR r IN
    SELECT col.table_name AS tbl
      FROM information_schema.columns col
      JOIN information_schema.tables t
        ON t.table_schema = col.table_schema AND t.table_name = col.table_name AND t.table_type = 'BASE TABLE'
     WHERE col.table_schema = 'public'
       AND col.column_name = 'updated_at'
       AND col.table_name NOT IN
           ('change_log', 'cdc_sink_control', 'pgmigrations', 'staff_sessions', 'portal_sessions', 'dolphin_sync_map')
  LOOP
    SELECT a.attname INTO pk
      FROM pg_index i
      JOIN pg_class c     ON c.oid = i.indrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
     WHERE c.relname = r.tbl AND i.indisprimary AND array_length(i.indkey::int[], 1) = 1;
    IF pk IS NULL THEN CONTINUE; END IF;
    seq := pg_get_serial_sequence('public.' || quote_ident(r.tbl), pk);
    IF seq IS NULL THEN
      RAISE NOTICE 'even-seq: % has no identity sequence (PK %) — skipped', r.tbl, pk;
      CONTINUE; -- text PK (options) / shared PK (patient_portal_auth) — still LWW-reverse-writable
    END IF;
    EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I', pk, r.tbl) INTO max_id;
    next_even := max_id + 2 - (max_id % 2); -- smallest even strictly greater than max_id
    EXECUTE format('ALTER SEQUENCE %s INCREMENT BY 2 RESTART WITH %s', seq, next_even);
    RAISE NOTICE 'even-seq: % (%) → INCREMENT BY 2 RESTART WITH %', r.tbl, seq, next_even;
  END LOOP;
END $$;
