-- Supabase mirror of migrations/pg/1782300000000_shade-tables.sql — applied via
-- SUPABASE_FAILOVER_DB_URL (small additive DDL), BEFORE the local migration, so the
-- forward (failover) upserts of the seed rows / future admin edits land.
--
-- Mirror parity rules (docs/sync-cdc.md): identical tables/columns to local. The ONLY
-- asymmetry: NO `cdc_capture` trigger here (these are forward-only failover TARGETS;
-- the mirror never captures lookup-table changes back). Seed is included + idempotent
-- (ON CONFLICT DO NOTHING) so the mirror is self-sufficient even before/without the
-- local seed replicating through the failover sink; the ids line up because both sides
-- seed in the same order from the default identity sequence.

CREATE TABLE IF NOT EXISTS public.shade_vita_classic (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shade public.citext NOT NULL
);

CREATE TABLE IF NOT EXISTS public.shade_3d_master (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shade public.citext NOT NULL
);

ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS shade_system public.citext;
ALTER TABLE public.work_items ADD COLUMN IF NOT EXISTS shade        public.citext;

INSERT INTO public.shade_vita_classic (shade) VALUES
  ('A1'), ('A2'), ('A3'), ('A3.5'), ('A4'),
  ('B1'), ('B2'), ('B3'), ('B4'),
  ('C1'), ('C2'), ('C3'), ('C4'),
  ('D2'), ('D3'), ('D4')
ON CONFLICT DO NOTHING;

INSERT INTO public.shade_3d_master (shade) VALUES
  ('0M1'), ('0M2'), ('0M3'),
  ('1M1'), ('1M2'),
  ('2L1.5'), ('2L2.5'), ('2M1'), ('2M2'), ('2M3'), ('2R1.5'), ('2R2.5'),
  ('3L1.5'), ('3L2.5'), ('3M1'), ('3M2'), ('3M3'), ('3R1.5'), ('3R2.5'),
  ('4L1.5'), ('4L2.5'), ('4M1'), ('4M2'), ('4M3'), ('4R1.5'), ('4R2.5'),
  ('5M1'), ('5M2'), ('5M3')
ON CONFLICT DO NOTHING;
