-- Supabase mirror of migrations/pg/1791294000000_time-point-names.sql — the photo-session
-- (time point) name lookup. Small additive DDL: apply via SUPABASE_FAILOVER_DB_URL BEFORE the
-- local migration, so the forward (failover) upsert of the seed rows has a target table.
--
--   scripts/psql.sh supa -f migrations/supabase/time-point-names-2026-10-06.sql
--
-- Mirror parity (docs/sync-cdc.md): the same table, columns and constraints as local. The
-- asymmetries are the usual ones for a forward-only lookup table: NO capture trigger here (no
-- `updated_at`, so it is not in the reverse set and the mirror never sends a change back) and
-- the plain identity increment. The seed is included with the same explicit ids, idempotently,
-- so the mirror is complete whether or not the local rows have replicated yet.
--
-- RLS: enabled with NO policies, the mirror's prevailing posture — deny-all to the PostgREST
-- `anon`/`authenticated` roles. The forward sink connects as the owner and `mirror_rw` is
-- BYPASSRLS, so replication and the read-only web role are unaffected.

CREATE TABLE IF NOT EXISTS public.time_point_names (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name public.citext NOT NULL,
  CONSTRAINT time_point_names_name_key UNIQUE (name)
);

ALTER TABLE public.time_point_names ENABLE ROW LEVEL SECURITY;

INSERT INTO public.time_point_names (id, name) VALUES
  (1, 'Initial'),
  (2, 'Progress'),
  (3, 'Final'),
  (4, 'Initial P2'),
  (5, 'Progress P2'),
  (6, 'Final P2'),
  (7, 'Final+'),
  (8, 'Retention')
  ON CONFLICT DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.time_point_names', 'id'),
  (SELECT max(id) FROM public.time_point_names)
);

-- Grant for the read-only web role (mirror-grants.sql's default privileges cover tables its
-- own role creates; this is explicit so it holds whichever role applies the file).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mirror_rw') THEN
    GRANT SELECT ON public.time_point_names TO mirror_rw;
  END IF;
END $$;
