/**
 * Unified CDC — shared schema helpers (used by BOTH the forward `failover` sink and the reverse
 * sink). Local and the Supabase mirror are DDL-parity-equal, so all of these are queried from the
 * LOCAL catalog and apply verbatim to either side:
 *   - `qIdent`            — double-quote an identifier for raw SQL.
 *   - `loadPks`           — table → single-PK column, for every cdc-captured table.
 *   - `loadGeneratedCols` — table → stored generated columns (must be dropped from a raw upsert).
 *   - `loadUpdatedAtTables` — the set of tables carrying an `updated_at` column (the reverse /
 *                            whole-row-LWW set; lookup tables have none and stay forward-only).
 *   - `lwwUpdateClause`   — the `ON CONFLICT … DO UPDATE … WHERE` last-write-wins guard both sinks
 *                            ride for `updated_at` tables.
 *
 * `loadPks`/`loadGeneratedCols`/`qIdent` were lifted verbatim from failover-sink.ts so both sinks
 * share one definition.
 */
import type { Pool } from 'pg';

/** Double-quote an SQL identifier (escaping embedded quotes). */
export function qIdent(id: string): string {
  return '"' + id.replace(/"/g, '""') + '"';
}

/**
 * table → single PK column, for every cdc-captured table (those carrying trg_cdc_capture with a
 * single-column PK). The reverse sink resolves the same map from the LOCAL catalog given parity —
 * the Supabase mirror has the identical PK on every table.
 */
export async function loadPks(local: Pool): Promise<Map<string, string>> {
  const { rows } = await local.query<{ tbl: string; pk: string }>(
    `SELECT c.relname AS tbl, a.attname AS pk
       FROM pg_trigger tg
       JOIN pg_class c     ON c.oid = tg.tgrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
       JOIN pg_index i     ON i.indrelid = c.oid AND i.indisprimary AND array_length(i.indkey::int[], 1) = 1
       JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
      WHERE tg.tgname = 'trg_cdc_capture'`
  );
  const m = new Map<string, string>();
  for (const r of rows) m.set(r.tbl, r.pk);
  return m;
}

/**
 * Stored generated columns (`GENERATED ALWAYS AS (...) STORED`, e.g. tblappointments."AppDay")
 * by table. PG rejects any non-DEFAULT value for these, so they must be dropped from the raw
 * upsert's column list — the receiving side recomputes them. Identity PKs are `GENERATED BY
 * DEFAULT` (attgenerated = '', not 's'), so they are NOT matched here and still get copied verbatim.
 */
export async function loadGeneratedCols(local: Pool): Promise<Map<string, Set<string>>> {
  const { rows } = await local.query<{ tbl: string; col: string }>(
    `SELECT c.relname AS tbl, a.attname AS col
       FROM pg_attribute a
       JOIN pg_class c     ON c.oid = a.attrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      WHERE a.attgenerated = 's' AND a.attnum > 0 AND NOT a.attisdropped`
  );
  const m = new Map<string, Set<string>>();
  for (const r of rows) {
    if (!m.has(r.tbl)) m.set(r.tbl, new Set());
    m.get(r.tbl)!.add(r.col);
  }
  return m;
}

/**
 * The set of public tables carrying an `updated_at` column — the whole-row last-write-wins set.
 * These are exactly the reverse-syncable tables (the forward sink also uses LWW for them); lookup
 * tables have no `updated_at` and stay forward-only / blind-upsert. Parity-equal on both DBs, so a
 * single local-catalog query serves both sinks.
 */
export async function loadUpdatedAtTables(local: Pool): Promise<Set<string>> {
  const { rows } = await local.query<{ tbl: string }>(
    `SELECT table_name AS tbl
       FROM information_schema.columns
      WHERE table_schema = 'public' AND column_name = 'updated_at'`
  );
  return new Set(rows.map((r) => r.tbl));
}

/**
 * The `ON CONFLICT (<pk>) DO UPDATE … WHERE` clause that makes an upsert whole-row last-write-wins
 * on `updated_at` — one round-trip, no pre-SELECT. The incoming row (`EXCLUDED`) overwrites the
 * stored row only when it carries a non-NULL `updated_at` that beats the stored one:
 *   - Forward (local→Supabase) uses `>=` (local wins ties).
 *   - Reverse (Supabase→local) uses `>`  (Supabase overwrites only when strictly newer).
 * The NULL arms keep pre-migration NULL-`updated_at` rows safe (any real edit stamps the column via
 * the BEFORE trigger, so a replicated change always carries a non-NULL value). `updated_at` tables
 * always have a non-PK column, so the SET list is never empty.
 */
export function lwwUpdateClause(
  table: string,
  pkCol: string,
  cols: string[],
  op: '>' | '>='
): string {
  const setList = cols
    .filter((c) => c !== pkCol)
    .map((c) => `${qIdent(c)} = EXCLUDED.${qIdent(c)}`)
    .join(', ');
  const qt = qIdent(table);
  const ua = qIdent('updated_at');
  return (
    `ON CONFLICT (${qIdent(pkCol)}) DO UPDATE SET ${setList} ` +
    `WHERE EXCLUDED.${ua} IS NOT NULL ` +
    `AND (${qt}.${ua} IS NULL OR EXCLUDED.${ua} ${op} ${qt}.${ua})`
  );
}

/**
 * Per-sink cache of the three schema facts a raw row-copy needs, all resolved from the LOCAL
 * catalog (local and the Supabase mirror are DDL-parity-equal, so one lookup serves both sinks).
 *
 * Each fact has the same subtlety: a table ABSENT from the loaded map means "no generated columns"
 * / "no updated_at" / "not captured", so cache membership alone can't distinguish "known absent"
 * from "loaded before this table existed". Every lookup therefore keeps a `seen` set and refreshes
 * exactly ONCE per table, which is what lets a newly-captured table (or one that just gained
 * `updated_at`) be picked up without a restart — and what stops an absent table from re-running the
 * catalog query on every single change row.
 *
 * Lifted out of FailoverSink/ReverseSink, which held byte-identical copies of all of this.
 */
export class SchemaMetaCache {
  private pkCache: Map<string, string> | null = null;
  private pkSeen: Set<string> | null = null;
  private genColsCache: Map<string, Set<string>> | null = null;
  private genColsSeen: Set<string> | null = null;
  private updatedAtCache: Set<string> | null = null;
  private updatedAtSeen: Set<string> | null = null;

  constructor(private readonly local: () => Pool) {}

  /** Drop everything — called from a sink's init()/close(). */
  reset(): void {
    this.pkCache = null;
    this.pkSeen = null;
    this.genColsCache = null;
    this.genColsSeen = null;
    this.updatedAtCache = null;
    this.updatedAtSeen = null;
  }

  /** The table's single PK column, or undefined when it isn't a single-PK captured table. */
  async pkFor(table: string): Promise<string | undefined> {
    if (!this.pkCache || !this.pkSeen) {
      this.pkCache = await loadPks(this.local());
      this.pkSeen = new Set();
    }
    if (!this.pkSeen.has(table)) {
      this.pkCache = await loadPks(this.local()); // refresh once for a newly-captured table
      this.pkSeen.add(table);
    }
    return this.pkCache.get(table);
  }

  /** Stored generated columns to drop from a raw upsert (PG rejects an explicit value for them). */
  async generatedColsFor(table: string): Promise<Set<string>> {
    if (!this.genColsCache || !this.genColsSeen) {
      this.genColsCache = await loadGeneratedCols(this.local());
      this.genColsSeen = new Set();
    }
    if (!this.genColsSeen.has(table)) {
      this.genColsCache = await loadGeneratedCols(this.local());
      this.genColsSeen.add(table);
    }
    return this.genColsCache.get(table) ?? new Set();
  }

  /** Whether `table` carries `updated_at` → the upsert rides the whole-row LWW conflict clause. */
  async isUpdatedAtTable(table: string): Promise<boolean> {
    if (!this.updatedAtCache || !this.updatedAtSeen) {
      this.updatedAtCache = await loadUpdatedAtTables(this.local());
      this.updatedAtSeen = new Set();
    }
    if (!this.updatedAtSeen.has(table)) {
      this.updatedAtCache = await loadUpdatedAtTables(this.local());
      this.updatedAtSeen.add(table);
    }
    return this.updatedAtCache.has(table);
  }
}

/** A ready-to-run upsert (`sql` + positional `params`) for one replicated row. */
export interface UpsertStatement {
  sql: string;
  params: unknown[];
}

/**
 * Build the raw INSERT … ON CONFLICT that replicates one row verbatim, shared by BOTH sinks (they
 * differ only in the LWW operator: forward `>=` so local wins ties, reverse `>` so Supabase must be
 * strictly newer). Stored generated columns are dropped — PG rejects an explicit value and the
 * receiving side recomputes them from the same expression. Tables with no `updated_at` (the lookup
 * tables, forward-only) fall back to a blind upsert.
 */
export async function buildRowUpsert(
  meta: SchemaMetaCache,
  table: string,
  pkCol: string,
  row: Record<string, unknown>,
  lwwOp: '>' | '>='
): Promise<UpsertStatement> {
  const generated = await meta.generatedColsFor(table);
  const cols = Object.keys(row).filter((c) => !generated.has(c));
  const colList = cols.map(qIdent).join(', ');
  const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ');

  let conflict: string;
  if (await meta.isUpdatedAtTable(table)) {
    conflict = lwwUpdateClause(table, pkCol, cols, lwwOp);
  } else {
    const setList = cols
      .filter((c) => c !== pkCol)
      .map((c) => `${qIdent(c)} = EXCLUDED.${qIdent(c)}`)
      .join(', ');
    conflict = setList
      ? `ON CONFLICT (${qIdent(pkCol)}) DO UPDATE SET ${setList}`
      : `ON CONFLICT (${qIdent(pkCol)}) DO NOTHING`;
  }

  return {
    sql: `INSERT INTO ${qIdent(table)} (${colList}) VALUES (${placeholders}) ${conflict}`,
    params: cols.map((c) => row[c]),
  };
}

/**
 * Read one row as jsonb — `to_jsonb` so wall-clock `date`/`timestamp` values transfer as text with
 * no UTC drift. Returns null when the row is gone (the caller propagates that as a delete).
 */
export async function readRowAsJson(
  pool: Pool,
  table: string,
  pkCol: string,
  pk: string
): Promise<Record<string, unknown> | null> {
  const { rows } = await pool.query<{ r: Record<string, unknown> }>(
    `SELECT to_jsonb(t.*) AS r FROM ${qIdent(table)} t WHERE ${qIdent(pkCol)} = $1`,
    [pk]
  );
  return rows.length === 0 ? null : rows[0].r;
}
