/**
 * Unified CDC — shared schema helpers (used by BOTH the forward `failover` sink and the reverse
 * sink). Local and the Supabase mirror are DDL-parity-equal, so all of these are queried from the
 * LOCAL catalog and apply verbatim to either side:
 *   - `qIdent`            — double-quote an identifier for raw SQL.
 *   - `loadPks`           — table → single-PK column, for every cdc-captured table.
 *   - `loadGeneratedCols` — table → stored generated columns (must be dropped from a raw upsert).
 *   - `loadUpdatedAtTables` — the set of tables carrying an `updated_at` column (the reverse /
 *                            whole-row-LWW set; lookup tables have none and stay forward-only).
 *   - `lwwUpdateClause`   — the `ON CONFLICT … DO UPDATE … WHERE` last-write-wins guard both sinks
 *                            ride for `updated_at` tables.
 *
 * `loadPks`/`loadGeneratedCols`/`qIdent` were lifted verbatim from failover-sink.ts so both sinks
 * share one definition.
 */
import type { Pool } from 'pg';

/** Double-quote an SQL identifier (escaping embedded quotes). */
export function qIdent(id: string): string {
  return '"' + id.replace(/"/g, '""') + '"';
}

/**
 * table → single PK column, for every cdc-captured table (those carrying trg_cdc_capture with a
 * single-column PK). The reverse sink resolves the same map from the LOCAL catalog given parity —
 * the Supabase mirror has the identical PK on every table.
 */
export async function loadPks(local: Pool): Promise<Map<string, string>> {
  const { rows } = await local.query<{ tbl: string; pk: string }>(
    `SELECT c.relname AS tbl, a.attname AS pk
       FROM pg_trigger tg
       JOIN pg_class c     ON c.oid = tg.tgrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
       JOIN pg_index i     ON i.indrelid = c.oid AND i.indisprimary AND array_length(i.indkey::int[], 1) = 1
       JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = i.indkey[0]
      WHERE tg.tgname = 'trg_cdc_capture'`
  );
  const m = new Map<string, string>();
  for (const r of rows) m.set(r.tbl, r.pk);
  return m;
}

/**
 * Stored generated columns (`GENERATED ALWAYS AS (...) STORED`, e.g. tblappointments."AppDay")
 * by table. PG rejects any non-DEFAULT value for these, so they must be dropped from the raw
 * upsert's column list — the receiving side recomputes them. Identity PKs are `GENERATED BY
 * DEFAULT` (attgenerated = '', not 's'), so they are NOT matched here and still get copied verbatim.
 */
export async function loadGeneratedCols(local: Pool): Promise<Map<string, Set<string>>> {
  const { rows } = await local.query<{ tbl: string; col: string }>(
    `SELECT c.relname AS tbl, a.attname AS col
       FROM pg_attribute a
       JOIN pg_class c     ON c.oid = a.attrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      WHERE a.attgenerated = 's' AND a.attnum > 0 AND NOT a.attisdropped`
  );
  const m = new Map<string, Set<string>>();
  for (const r of rows) {
    if (!m.has(r.tbl)) m.set(r.tbl, new Set());
    m.get(r.tbl)!.add(r.col);
  }
  return m;
}

/**
 * The set of public tables carrying an `updated_at` column — the whole-row last-write-wins set.
 * These are exactly the reverse-syncable tables (the forward sink also uses LWW for them); lookup
 * tables have no `updated_at` and stay forward-only / blind-upsert. Parity-equal on both DBs, so a
 * single local-catalog query serves both sinks.
 */
export async function loadUpdatedAtTables(local: Pool): Promise<Set<string>> {
  const { rows } = await local.query<{ tbl: string }>(
    `SELECT table_name AS tbl
       FROM information_schema.columns
      WHERE table_schema = 'public' AND column_name = 'updated_at'`
  );
  return new Set(rows.map((r) => r.tbl));
}

/**
 * The `ON CONFLICT (<pk>) DO UPDATE … WHERE` clause that makes an upsert whole-row last-write-wins
 * on `updated_at` — one round-trip, no pre-SELECT. The incoming row (`EXCLUDED`) overwrites the
 * stored row only when it carries a non-NULL `updated_at` that beats the stored one:
 *   - Forward (local→Supabase) uses `>=` (local wins ties).
 *   - Reverse (Supabase→local) uses `>`  (Supabase overwrites only when strictly newer).
 * The NULL arms keep pre-migration NULL-`updated_at` rows safe (any real edit stamps the column via
 * the BEFORE trigger, so a replicated change always carries a non-NULL value). `updated_at` tables
 * always have a non-PK column, so the SET list is never empty.
 */
export function lwwUpdateClause(
  table: string,
  pkCol: string,
  cols: string[],
  op: '>' | '>='
): string {
  const setList = cols
    .filter((c) => c !== pkCol)
    .map((c) => `${qIdent(c)} = EXCLUDED.${qIdent(c)}`)
    .join(', ');
  const qt = qIdent(table);
  const ua = qIdent('updated_at');
  return (
    `ON CONFLICT (${qIdent(pkCol)}) DO UPDATE SET ${setList} ` +
    `WHERE EXCLUDED.${ua} IS NOT NULL ` +
    `AND (${qt}.${ua} IS NULL OR EXCLUDED.${ua} ${op} ${qt}.${ua})`
  );
}
